-- SOptLib/Model/Bregman.lean
import Mathlib.Analysis.Calculus.Gradient.Basic
import Mathlib.Analysis.InnerProductSpace.Calculus
import Mathlib.Analysis.InnerProductSpace.Continuous
import Mathlib.Analysis.Convex.Strong
import Mathlib.Analysis.Convex.Deriv
import Mathlib.Analysis.Convex.Intrinsic
import Mathlib.Analysis.Calculus.AddTorsor.AffineMap
import Mathlib.Analysis.Seminorm
import Mathlib.Topology.Order.Basic
import Mathlib.MeasureTheory.Function.StronglyMeasurable.Inner


open scoped Gradient InnerProductSpace
open scoped BigOperators

/-- Canonical Bregman divergence generated by a differentiable potential `v`:
`D_v(x,z) = v z - v x - ⟪∇ v x, z - x⟫`.
Layer: Model | Concept: Bregman
Proof: (definitional construction; canonical three-term Bregman formula)
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Eq. (3.2.2).
Used in: stochastic mirror descent Bregman geometry
Book citation: `book/FOML/StochasticMirrorDescent.json#/assumptions/5/math`
Origin algorithm: FOML stochastic mirror descent -/
noncomputable def bregmanDivergence
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (v : E → ℝ) (x z : E) : ℝ :=
  v z - v x - ⟪∇ v x, z - x⟫_ℝ

/-- Literal interior-base Bregman divergence for mirror-descent geometry.

This construction packages the three-term Bregman formula using a potential on the
carrier space and an ambient differentiable representative to supply the
interior gradient term.

Layer: Model | Concept: Bregman
Proof: (definitional construction; literal Bregman divergence wrapper with an
  interior-base gradient correction term)
Source: Mathlib inner product spaces and Fréchet-derivative gradient notation
Used in: stochastic mirror descent prox objective and Bregman geometry setup
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
noncomputable def literalBregmanDivergence
    {E Xint P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (v : P → ℝ) (vInterior : E → ℝ) (toPoint : Xint → P)
    (evalInterior : Xint → E) (eval : P → E) (x : Xint) (z : P) : ℝ :=
  v z - v (toPoint x) - ⟪∇ vInterior (evalInterior x), eval z - evalInterior x⟫_ℝ

/-- Expanded literal formula for the interior-base Bregman divergence.

The model-level Bregman wrapper unfolds to `v z - v (toPoint x)` minus the
gradient linearization term at the interior representative of `x`.

Layer: Model | Gap: Level 0 (literal interior Bregman formula expansion)
Proof: by rfl after unfolding literalBregmanDivergence.
Source: Mathlib inner product space and gradient notation APIs
Used in: stochastic mirror descent prox-step algebra and literal Bregman formula audits
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
theorem literalBregmanDivergence_def
    {E Xint P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (v : P → ℝ) (vInterior : E → ℝ) (toPoint : Xint → P)
    (evalInterior : Xint → E) (eval : P → E) (x : Xint) (z : P) :
    literalBregmanDivergence v vInterior toPoint evalInterior eval x z =
      v z - v (toPoint x) - ⟪∇ vInterior (evalInterior x), eval z - evalInterior x⟫_ℝ := by
  rfl

/-- The literal Bregman formula for a carrier potential at topological-interior base points.

This packages the expansion of an interior ambient-gradient Bregman expression
for a potential defined on a feasible carrier, with the base point coerced from
`interior X` back to the carrier `X`.

Layer: Model | Gap: Level 1 (literal carrier Bregman formula expansion)
Proof: specialize an abstract definitional expansion hypothesis for the carrier
  Bregman value at the requested interior base point and feasible endpoint.
Source: Mathlib inner-product space and gradient notation APIs
Used in: stochastic mirror descent interior-base Bregman formula bridge
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec/parameters/2/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem literalCarrierBregmanDivergence
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} (v : {x : E // x ∈ X} → ℝ) (vInterior : E → ℝ)
    (V : {x : E // x ∈ interior X} → {x : E // x ∈ X} → ℝ)
    (hV : ∀ x z,
      V x z =
        v z - v ⟨x.1, interior_subset x.2⟩ -
          ⟪∇ vInterior x.1, z.1 - x.1⟫_ℝ)
    (x : {x : E // x ∈ interior X}) (z : {x : E // x ∈ X}) :
    V x z =
      v z - v ⟨x.1, interior_subset x.2⟩ -
        ⟪∇ vInterior x.1, z.1 - x.1⟫_ℝ := by
  exact hV x z



/-- The Bregman three-point identity for the canonical divergence
`D_v(x,z) = v z - v x - ⟪∇ v x, z - x⟫`.
Layer: Layer0 | Gap: Level 1 (Bregman algebra identity)
Proof: Expand the definition, split `z - x` through the intermediate point `y`,
  and normalize the resulting inner-product algebra.
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Eq. (3.2.6).
Used in: `bregman_three_point_identity`, stochastic mirror descent prox inequality
Book citation: `book/FOML/StochasticMirrorDescent.json#/assumptions/5/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem bregmanDivergence_three_point_identity
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (v : E → ℝ) (x y z : E) :
    bregmanDivergence v x z =
      bregmanDivergence v x y + ⟪∇ v y - ∇ v x, z - y⟫_ℝ +
        bregmanDivergence v y z := by
  unfold bregmanDivergence
  have hsplit : z - x = (z - y) + (y - x) := by
    abel
  rw [hsplit, inner_add_right, inner_sub_left]
  ring



/-- Strong convexity on an intrinsic interior gives the usual Bregman lower bound.
Layer: Layer0 | Gap: Level 2 (relative-interior Bregman lower bound)
Proof: Restrict the convexified function `v - (1 / 2)‖·‖²` to the segment
  from `x` to `z`, compare its one-sided derivative at `0` to the secant slope,
  and expand the squared norm identity.
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Proposition 3.1 / Bregman divergence lower bound.
Used in: `MirrorDescentSetup.V_lower_bound_of_intrinsicInterior_core`
Book citation: `book/FOML/StochasticMirrorDescent.json#/assumptions/5/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem bregman_lower_bound_of_strongConvexOn_intrinsicInterior
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {v : E → ℝ} {grad : E → E} {V : E → E → ℝ} {x z : E}
    (hV : V x z = v z - v x - ⟪grad x, z - x⟫_ℝ)
    (h_strong : StrongConvexOn (intrinsicInterior ℝ X) 1 v)
    (h_diff : DifferentiableOn ℝ v (intrinsicInterior ℝ X))
    (hgrad :
      ⟪grad x, z - x⟫_ℝ =
        ⟪gradientWithin v (intrinsicInterior ℝ X) x, z - x⟫_ℝ)
    (hx : x ∈ intrinsicInterior ℝ X) (hz : z ∈ intrinsicInterior ℝ X) :
    (1 / 2 : ℝ) * ‖x - z‖ ^ 2 ≤ V x z := by
  let s : Set E := intrinsicInterior ℝ X
  let φ : E → ℝ := fun y => v y - (1 / 2 : ℝ) * ‖y‖ ^ 2
  let line : ℝ → E := fun t => AffineMap.lineMap x z t
  have hφconv : ConvexOn ℝ s φ := by
    have hsc : StrongConvexOn s 1 v := by
      simpa [s] using h_strong
    rw [strongConvexOn_iff_convex] at hsc
    simpa [φ] using hsc
  have hline_mem : Set.Icc (0 : ℝ) 1 ⊆ line ⁻¹' s := by
    intro t ht
    have ht0 : 0 ≤ t := ht.1
    have ht1 : t ≤ 1 := ht.2
    have h1t : 0 ≤ 1 - t := sub_nonneg.mpr ht1
    have hsum : 1 - t + t = 1 := by ring
    have hconv : Convex ℝ s := hφconv.1
    have hmem : (1 - t) • x + t • z ∈ s :=
      hconv hx hz h1t ht0 hsum
    simpa [line, AffineMap.lineMap_apply_module] using hmem
  have hφline_conv : ConvexOn ℝ (Set.Icc (0 : ℝ) 1) (fun t => φ (line t)) := by
    simpa [line] using
      (hφconv.comp_affineMap (AffineMap.lineMap x z)).subset hline_mem (convex_Icc 0 1)
  have hmaps : Set.MapsTo line (Set.Icc (0 : ℝ) 1) s := by
    intro t ht
    exact hline_mem ht
  have hline_deriv :
      HasDerivWithinAt line (z - x) (Set.Icc (0 : ℝ) 1) 0 := by
    simpa [line] using
      (AffineMap.hasDerivWithinAt_lineMap (a := x) (b := z)
        (s := Set.Icc (0 : ℝ) 1) (x := (0 : ℝ)))
  have hvdiff : DifferentiableWithinAt ℝ v s x := by
    exact h_diff x hx
  have hvline :
      HasDerivWithinAt (fun t => v (line t))
        ((fderivWithin ℝ v s x) (z - x)) (Set.Icc (0 : ℝ) 1) 0 :=
    hvdiff.hasFDerivWithinAt.comp_hasDerivWithinAt_of_eq 0 hline_deriv hmaps (by simp [line])
  have hnormline :
      HasDerivWithinAt (fun t => ‖line t‖ ^ 2)
        ((2 • innerSL ℝ x) (z - x)) (Set.Icc (0 : ℝ) 1) 0 := by
    have hnormF :
        HasFDerivWithinAt (fun y : E => ‖y‖ ^ 2) (2 • innerSL ℝ x) s x :=
      (hasStrictFDerivAt_norm_sq x).hasFDerivAt.hasFDerivWithinAt
    exact hnormF.comp_hasDerivWithinAt_of_eq 0 hline_deriv hmaps (by simp [line])
  have hφderiv :
      HasDerivWithinAt (fun t => φ (line t))
        ((fderivWithin ℝ v s x) (z - x) -
          (1 / 2 : ℝ) * ((2 • innerSL ℝ x) (z - x)))
        (Set.Icc (0 : ℝ) 1) 0 := by
    simpa [φ] using hvline.sub (HasDerivWithinAt.const_mul (1 / 2 : ℝ) hnormline)
  have hslope :
      (fderivWithin ℝ v s x) (z - x) -
          (1 / 2 : ℝ) * ((2 • innerSL ℝ x) (z - x)) ≤
        slope (fun t => φ (line t)) 0 1 := by
    exact hφline_conv.le_slope_of_hasDerivWithinAt
      (x := (0 : ℝ)) (y := (1 : ℝ))
      (by norm_num) (by norm_num) (by norm_num) hφderiv
  have hgrad_apply :
      (fderivWithin ℝ v s x) (z - x) =
        ⟪gradientWithin v s x, z - x⟫_ℝ := by
    rw [gradientWithin, InnerProductSpace.toDual_symm_apply]
  have hnorm_deriv :
      ((2 • innerSL ℝ x) (z - x)) =
        2 * ⟪x, z - x⟫_ℝ := by
    simp
  have hslope_expanded :
      ⟪gradientWithin v s x, z - x⟫_ℝ -
          ⟪x, z - x⟫_ℝ ≤
        v z - (1 / 2 : ℝ) * ‖z‖ ^ 2 -
          (v x - (1 / 2 : ℝ) * ‖x‖ ^ 2) := by
    have hs := hslope
    rw [hgrad_apply, hnorm_deriv] at hs
    simpa [slope_def_field, φ, line] using hs
  have hnorm_id :
      (1 / 2 : ℝ) * ‖z - x‖ ^ 2 =
        (1 / 2 : ℝ) * ‖z‖ ^ 2 - (1 / 2 : ℝ) * ‖x‖ ^ 2 -
          ⟪x, z - x⟫_ℝ := by
    rw [norm_sub_sq_real, inner_sub_right, real_inner_comm x z,
      real_inner_self_eq_norm_sq]
    ring_nf
  rw [hV, hgrad, norm_sub_rev]
  nlinarith [hslope_expanded, hnorm_id]


/-- Definitional formula for the canonical ambient Bregman divergence.
Layer: Model | Gap: Level 0 (ambient Bregman formula)
Proof: expand the staged Bregman definition.
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Eq. (3.2.2).
Used in: stochastic mirror descent Bregman formula bridges
Book citation: `book/FOML/StochasticMirrorDescent.json#/assumptions/5/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem bregmanDivergence_def
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (v : E → ℝ) (x z : E) :
    bregmanDivergence v x z =
      v z - v x - ⟪∇ v x, z - x⟫_ℝ := by
  rfl

/-- Convexity gives nonnegativity of the canonical ambient Bregman divergence at a
point where the Mathlib gradient realizes the supporting hyperplane.
Layer: Model | Gap: Level 2 (Bregman nonnegativity)
Proof: Restrict `v` to the segment from `x` to `z`, compare the derivative at `0`
  with the secant slope for a convex one-dimensional restriction, and expand.
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Proposition 3.1 / Bregman divergence nonnegativity.
Used in: `V_nonneg`, stochastic mirror descent Bregman geometry
Book citation: `book/FOML/StochasticMirrorDescent.json#/assumptions/5/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem bregmanDivergence_nonneg_of_convexOn
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {v : E → ℝ} {x z : E}
    (hv : ConvexOn ℝ X v)
    (hx : x ∈ X) (hz : z ∈ X)
    (hgrad : HasGradientAt v (∇ v x) x) :
    0 ≤ bregmanDivergence v x z := by
  unfold bregmanDivergence
  have hsupport : v x + ⟪∇ v x, z - x⟫_ℝ ≤ v z := by
    set g : ℝ → ℝ := fun t => v (AffineMap.lineMap x z t)
    have hline_mem : Set.Icc (0 : ℝ) 1 ⊆ (AffineMap.lineMap x z) ⁻¹' X := by
      intro t ht
      have ht0 : 0 ≤ t := ht.1
      have ht1 : t ≤ 1 := ht.2
      have h1t : 0 ≤ 1 - t := sub_nonneg.mpr ht1
      have hsum : 1 - t + t = 1 := by ring
      have hmem : (1 - t) • x + t • z ∈ X := hv.1 hx hz h1t ht0 hsum
      change AffineMap.lineMap x z t ∈ X
      rw [AffineMap.lineMap_apply_module']
      convert hmem using 1
      module
    have hg_conv : ConvexOn ℝ (Set.Icc (0 : ℝ) 1) g := by
      simpa [g] using
        (hv.comp_affineMap (AffineMap.lineMap x z)).subset hline_mem (convex_Icc 0 1)
    have hg_deriv : HasDerivAt g (⟪∇ v x, z - x⟫_ℝ) 0 := by
      have hg_eq_line : g = fun t : ℝ => v (x + t • (z - x)) := by
        ext t
        simp only [g, AffineMap.lineMap_apply_module']
        congr 1
        module
      rw [hg_eq_line]
      have hfderiv : HasFDerivAt v (InnerProductSpace.toDual ℝ E (∇ v x))
          (x + (0 : ℝ) • (z - x)) := by
        simpa using hgrad.hasFDerivAt
      have hline : HasDerivAt (fun t : ℝ => x + t • (z - x)) ((1 : ℝ) • (z - x)) 0 := by
        exact (hasDerivAt_id 0).smul_const (z - x) |>.const_add x
      have hcomp := hfderiv.comp_hasDerivAt 0 (hline.congr_deriv (one_smul ℝ (z - x)))
      simpa [Function.comp_def, InnerProductSpace.toDual_apply_apply] using hcomp
    have hslope := hg_conv.le_slope_of_hasDerivAt (by norm_num) (by norm_num) zero_lt_one hg_deriv
    simp [g, slope_def_field, AffineMap.lineMap_apply_module'] at hslope
    linarith
  linarith

/-- Strong convexity implies nonnegativity of the canonical ambient Bregman divergence.
Layer: Model | Gap: Level 1 (Bregman nonnegativity)
Proof: Forget the strong-convexity modulus to convexity, then apply the convex
  supporting-hyperplane form.
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Proposition 3.1 / Bregman divergence nonnegativity.
Used in: `V_nonneg`, stochastic mirror descent Bregman geometry
Book citation: `book/FOML/StochasticMirrorDescent.json#/assumptions/5/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem bregmanDivergence_nonneg_of_strongConvexOn
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {v : E → ℝ} {x z : E}
    (hv : StrongConvexOn X 1 v)
    (hx : x ∈ X) (hz : z ∈ X)
    (hgrad : HasGradientAt v (∇ v x) x) :
    0 ≤ bregmanDivergence v x z := by
  have hconv : ConvexOn ℝ X v := by
    have hv0 : StrongConvexOn X 0 v := hv.mono (by norm_num : (0 : ℝ) ≤ 1)
    simpa using hv0
  exact bregmanDivergence_nonneg_of_convexOn hconv hx hz hgrad

/-- Symmetric half-squared-distance Bregman lower bounds give a squared-distance bound.

If each directed Bregman term lower-bounds one half of the squared norm distance,
then their two-direction sum lower-bounds the full squared norm distance.

Layer: Model | Gap: Level 0 (symmetric Bregman lower bound)
Proof: rewrite the reversed norm with `norm_sub_rev`, transfer the second
  half-bound to the same squared distance, and combine the two real inequalities
  by linear arithmetic.
Source: Mathlib normed additive groups and real linear arithmetic APIs
Used in: stochastic mirror descent conversion from symmetric Bregman control to
  squared-distance control under strong convexity
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem sq_norm_le_bregman_add_swap_of_half_lower_bound
    {P : Type*} {E : Type*} [NormedAddCommGroup E]
    (V : P → P → ℝ) (eval : P → E) (x y : P)
    (hxy : (1 / 2 : ℝ) * ‖eval x - eval y‖ ^ 2 ≤ V x y)
    (hyx : (1 / 2 : ℝ) * ‖eval y - eval x‖ ^ 2 ≤ V y x) :
    ‖eval x - eval y‖ ^ 2 ≤ V x y + V y x := by
  have hnorm : ‖eval y - eval x‖ = ‖eval x - eval y‖ := by
    simpa using norm_sub_rev (eval y) (eval x)
  have hyx' : (1 / 2 : ℝ) * ‖eval x - eval y‖ ^ 2 ≤ V y x := by
    simpa [hnorm] using hyx
  linarith

/-- A continuous real-valued function nonnegative on a dense set is nonnegative everywhere.

Layer: Model | Gap: Level 1 (dense-to-global nonnegativity transfer)
Proof: push the `MapsTo` nonnegativity statement through closure using
  `Set.MapsTo.closure_of_continuousOn`; density puts every point in `closure s`,
  and closedness of `Set.Ici 0` in `ℝ` removes the codomain closure.
Source: Mathlib dense-set closure and closed-order topology APIs
Used in: Bregman divergence nonnegativity on the full feasible carrier from a
  dense model domain
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
private theorem nonneg_of_continuousOn_of_dense_nonneg_for_model
    {α : Type*} [TopologicalSpace α]
    (D : α → ℝ) (s : Set α)
    (hcont : ContinuousOn D Set.univ)
    (hdense : Dense s)
    (hnonneg : Set.MapsTo D s (Set.Ici (0 : ℝ)))
    (a : α) :
    0 ≤ D a := by
  have hall :
      Set.MapsTo D (closure s) (closure (Set.Ici (0 : ℝ))) :=
    hnonneg.closure_of_continuousOn (by
      exact hcont.mono (by intro y hy; simp))
  have ha : a ∈ closure s := by
    rw [Dense.closure_eq hdense]
    simp
  have h := hall ha
  have hIci_closed : closure (Set.Ici (0 : ℝ)) = Set.Ici 0 := isClosed_Ici.closure_eq
  rw [hIci_closed] at h
  exact h

open Topology
open scoped Gradient InnerProductSpace

/-- Carrier-level Bregman divergence generated by a potential on a feasible carrier and an
abstract carrier-gradient selector.
Layer: Model | Concept: Bregman
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Eq. (3.2.2).
Used in: `MirrorDescentSetup.V`
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/parameters/2/math`
Origin algorithm: FOML stochastic mirror descent -/
noncomputable def carrierBregmanDivergence
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} (v : {x : E // x ∈ X} → ℝ)
    (grad : {x : E // x ∈ X} → E) (x z : {x : E // x ∈ X}) : ℝ :=
  v z - v x - ⟪grad x, z.1 - x.1⟫_ℝ

/-- Definitional formula for the carrier-level Bregman divergence.
Layer: Model | Gap: Level 0 (carrier Bregman formula)
Proof: Expand the canonical carrier definition.
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Eq. (3.2.2).
Used in: stochastic mirror descent Bregman formula bridges
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/parameters/2/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem carrierBregmanDivergence_def
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} (v : {x : E // x ∈ X} → ℝ)
    (grad : {x : E // x ∈ X} → E) (x z : {x : E // x ∈ X}) :
    carrierBregmanDivergence v grad x z =
      v z - v x - ⟪grad x, z.1 - x.1⟫_ℝ := by
  rfl

/-- Intrinsic-interior formula when the abstract carrier gradient agrees directionally
with Mathlib's `gradientWithin` selector.
Layer: Model | Gap: Level 1 (intrinsic-interior formula bridge)
Proof: Rewrite the carrier potential and directional gradient terms.
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Eq. (3.2.2).
Used in: `MirrorDescentSetup.V_eq_formula_of_intrinsicInterior`
Book citation: `book/FOML/StochasticMirrorDescent.json#/assumptions/5/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem carrierBregmanDivergence_eq_intrinsic_formula
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ} {vInterior : E → ℝ}
    {grad : {x : E // x ∈ X} → E} {x z : {x : E // x ∈ X}}
    (hvx : v x = vInterior x.1) (hvz : v z = vInterior z.1)
    (hgrad :
      ⟪grad x, z.1 - x.1⟫_ℝ =
        ⟪gradientWithin vInterior (intrinsicInterior ℝ X) x.1, z.1 - x.1⟫_ℝ) :
    carrierBregmanDivergence v grad x z =
      vInterior z.1 - vInterior x.1 -
        ⟪gradientWithin vInterior (intrinsicInterior ℝ X) x.1, z.1 - x.1⟫_ℝ := by
  simp [carrierBregmanDivergence, hvx, hvz, hgrad]

/-- Strong convexity on the intrinsic interior gives the carrier Bregman lower bound.
Layer: Model | Gap: Level 2 (relative-interior Bregman lower bound)
Proof: Delegate to the ambient intrinsic-interior lower-bound theorem and rewrite the
  carrier realization.
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Proposition 3.1 / Bregman divergence lower bound.
Used in: `MirrorDescentSetup.V_lower_bound_of_intrinsicInterior_core`
Book citation: `book/FOML/StochasticMirrorDescent.json#/assumptions/5/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem carrierBregmanDivergence_lower_bound_of_strongConvexOn_intrinsicInterior
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ} {vInterior : E → ℝ}
    {grad : {x : E // x ∈ X} → E} {x z : {x : E // x ∈ X}}
    (hvx : v x = vInterior x.1) (hvz : v z = vInterior z.1)
    (h_strong : StrongConvexOn (intrinsicInterior ℝ X) 1 vInterior)
    (h_diff : DifferentiableOn ℝ vInterior (intrinsicInterior ℝ X))
    (hgrad :
      ⟪grad x, z.1 - x.1⟫_ℝ =
        ⟪gradientWithin vInterior (intrinsicInterior ℝ X) x.1, z.1 - x.1⟫_ℝ)
    (hx : x.1 ∈ intrinsicInterior ℝ X) (hz : z.1 ∈ intrinsicInterior ℝ X) :
    (1 / 2 : ℝ) * ‖x.1 - z.1‖ ^ 2 ≤ carrierBregmanDivergence v grad x z := by
  have h :=
    bregman_lower_bound_of_strongConvexOn_intrinsicInterior
      (X := X) (v := vInterior) (grad := fun _ : E => grad x)
      (V := fun y w : E => vInterior w - vInterior y - ⟪grad x, w - y⟫_ℝ)
      (x := x.1) (z := z.1) rfl h_strong h_diff hgrad hx hz
  simpa [carrierBregmanDivergence, hvx, hvz] using h

/-- Continuity of the carrier Bregman divergence from continuity of the carrier potential
and carrier-gradient selector.
Layer: Model | Gap: Level 1 (carrier Bregman continuity)
Proof: Compose continuous potential, gradient, subtype projections, subtraction, normed
  group operations, and the inner product.
Source: Mathlib continuity API for inner-product spaces.
Used in: `MirrorDescentSetup.V_continuousOn_carrier`
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/parameters/2/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem carrierBregmanDivergence_continuous
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ}
    {grad : {x : E // x ∈ X} → E}
    (hv : Continuous v) (hgrad : Continuous grad) :
    Continuous (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
      carrierBregmanDivergence v grad p.1 p.2) := by
  have hleft : Continuous (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} => v p.2) :=
    hv.comp continuous_snd
  have hbase : Continuous (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} => v p.1) :=
    hv.comp continuous_fst
  have hinner : Continuous (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
      ⟪grad p.1, p.2.1 - p.1.1⟫_ℝ) :=
    (hgrad.comp continuous_fst).inner
      ((continuous_subtype_val.comp continuous_snd).sub
        (continuous_subtype_val.comp continuous_fst))
  simpa [carrierBregmanDivergence] using (hleft.sub hbase).sub hinner

/-- Carrier-continuity version on the full carrier product.
Layer: Model | Gap: Level 1 (carrier Bregman continuity)
Proof: Restrict the continuous carrier Bregman map to `Set.univ`.
Source: Mathlib continuity API for inner-product spaces.
Used in: `MirrorDescentSetup.V_continuousOn_carrier`
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/parameters/2/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem carrierBregmanDivergence_continuousOn_carrier
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ}
    {grad : {x : E // x ∈ X} → E}
    (hv : Continuous v) (hgrad : Continuous grad) :
    ContinuousOn (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
      carrierBregmanDivergence v grad p.1 p.2) Set.univ :=
  (carrierBregmanDivergence_continuous (v := v) (grad := grad) hv hgrad).continuousOn

/-- Extend a carrier Bregman lower bound from a dense intrinsic-interior carrier to the
full carrier under continuity.
Layer: Model | Gap: Level 2 (boundary extension of carrier lower bound)
Proof: Apply the closed-order density lemma to the residual
  `D(x,z) - (1 / 2)‖x - z‖²`.
Source: Mathlib topology and closed-order APIs.
Used in: `MirrorDescentSetup.V_lower_bound_all_carrier_from_intrinsicClosure`
Book citation: `book/FOML/StochasticMirrorDescent.json#/assumptions/5/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem carrierBregmanDivergence_lower_bound_all_carrier_from_dense
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ}
    {grad : {x : E // x ∈ X} → E}
    (hcont : ContinuousOn (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
      carrierBregmanDivergence v grad p.1 p.2) Set.univ)
    (hdense : Dense {x : {y : E // y ∈ X} | x.1 ∈ intrinsicInterior ℝ X})
    (hlocal : ∀ x z : {y : E // y ∈ X},
      x.1 ∈ intrinsicInterior ℝ X → z.1 ∈ intrinsicInterior ℝ X →
        (1 / 2 : ℝ) * ‖x.1 - z.1‖ ^ 2 ≤ carrierBregmanDivergence v grad x z)
    (x z : {y : E // y ∈ X}) :
    (1 / 2 : ℝ) * ‖x.1 - z.1‖ ^ 2 ≤ carrierBregmanDivergence v grad x z := by
  exact sub_nonneg.mp (nonneg_of_continuousOn_of_dense_nonneg_for_model
    (D := fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
      carrierBregmanDivergence v grad p.1 p.2 - (1 / 2 : ℝ) * ‖p.1.1 - p.2.1‖ ^ 2)
    (s := {x : {y : E // y ∈ X} | x.1 ∈ intrinsicInterior ℝ X} ×ˢ
      {x : {y : E // y ∈ X} | x.1 ∈ intrinsicInterior ℝ X})
    (by
      have hnorm :
          Continuous (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
            (1 / 2 : ℝ) * ‖p.1.1 - p.2.1‖ ^ 2) :=
        continuous_const.mul
          (((continuous_subtype_val.comp continuous_fst).sub
            (continuous_subtype_val.comp continuous_snd)).norm.pow 2)
      exact hcont.sub hnorm.continuousOn)
    (by
      rw [dense_iff_closure_eq] at hdense ⊢
      rw [closure_prod_eq, hdense]
      simp)
    (by
      rintro p ⟨hp1, hp2⟩
      change 0 ≤ carrierBregmanDivergence v grad p.1 p.2 -
        (1 / 2 : ℝ) * ‖p.1.1 - p.2.1‖ ^ 2
      have h := hlocal p.1 p.2 hp1 hp2
      linarith)
    (x, z))

/-- The value set of Bregman divergences over all ordered carrier pairs.

For a two-point divergence kernel `V`, `bregmanValueSet V` records exactly the
range of values `V x y` attained on the carrier product. This is the domain
over which Bregman diameter bounds and maximizing-pair witnesses are stated.

Layer: Model | Concept: Bregman
Proof: (definitional construction; range wrapper for the Bregman kernel on the
  carrier product)
Source: Mathlib set range and product projection APIs
Used in: stochastic mirror descent Bregman diameter range nonemptiness and
  maximizing-pair bookkeeping
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
def bregmanValueSet {P : Type*} (V : P → P → ℝ) : Set ℝ :=
  Set.range fun p : P × P => V p.1 p.2

/-- A maximizing pair witnesses that the Bregman value range is nonempty.

For a Bregman-value kernel `V`, if some pair `p : P × P` maximizes `V` over
all candidate pairs, then the value attained at `p` belongs to
`bregmanValueSet V`, so that set is nonempty.

Layer: Model | Gap: Level 0 (Bregman value range inhabited by maximizer)
Proof: destruct the existential maximizer and use the attained value
  `V p.1 p.2` as the set witness; membership is discharged by the defining
  image witness and `rfl`.
Source: Mathlib set image membership and existential witness APIs
Used in: stochastic mirror descent Bregman diameter construction from a maximizing pair
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem bregmanValueSet_nonempty {P : Type*} (V : P → P → ℝ)
    (hmax : ∃ p : P × P, ∀ q : P × P, V q.1 q.2 ≤ V p.1 p.2) :
    (bregmanValueSet V).Nonempty := by
  rcases hmax with ⟨p, _⟩
  exact ⟨V p.1 p.2, ⟨p, rfl⟩⟩

/-- A maximizing carrier pair makes the Bregman value range bounded above.

If an abstract Bregman value function `V` has a declared maximizer on the
carrier product, then every value in `bregmanValueSet V` is bounded by the value
at that maximizing pair.

Layer: Model | Gap: Level 0 (Bregman value-set boundedness from a maximum)
Proof: unpack the maximizing pair and use its universal inequality as the
  witness bound for `BddAbove`; membership in `bregmanValueSet` supplies the
  carrier pair whose value is being bounded.
Source: Mathlib order-theoretic boundedness and set range APIs
Used in: stochastic mirror descent Bregman diameter bounded-above construction
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem bregmanValueSet_bddAbove {P : Type*} (V : P → P → ℝ)
    (hmax : ∃ p : P × P, ∀ q : P × P, V q.1 q.2 ≤ V p.1 p.2) :
    BddAbove (bregmanValueSet V) := by
  rcases hmax with ⟨p, hp⟩
  refine ⟨V p.1 p.2, ?_⟩
  rintro y ⟨q, rfl⟩
  exact hp q

/-- Supremal squared Bregman diameter of an abstract carrier divergence.

`bregmanDiameterSq V` models the paper quantity `D_X^2` as the least upper
bound of all Bregman values generated by the carrier divergence `V`.

Layer: Model | Concept: Bregman
Proof: (definitional construction; supremum wrapper over the Bregman value set)
Source: Mathlib order-theoretic `sSup` API for conditionally complete lattices
Used in: stochastic mirror descent Bregman diameter bound for prox-step analysis
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def bregmanDiameterSq {P : Type*} (V : P → P → ℝ) : ℝ :=
  sSup (bregmanValueSet V)

/-- The abstract Bregman diameter square unfolds to the supremum of all Bregman values.

This exposes `bregmanDiameterSq V` as `sSup (bregmanValueSet V)`, the order-theoretic
least upper bound of the divergence values over carrier pairs.

Layer: Model | Gap: Level 0 (Bregman diameter definitional unfolding)
Proof: by rfl after unfolding bregmanDiameterSq.
Source: Mathlib order-theoretic supremum API for subsets of `ℝ`
Used in: stochastic mirror descent Bregman diameter constants and prox-step error bounds
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem bregmanDiameterSq_def {P : Type*} (V : P → P → ℝ) :
    bregmanDiameterSq V = sSup (bregmanValueSet V) := by
  rfl

/-- A declared maximizer realizes the supremal squared Bregman diameter.

If `pmax` maximizes the Bregman value kernel `V` on all carrier pairs, then
`bregmanDiameterSq V`, defined by `sSup` of the value set, is exactly
`V pmax.1 pmax.2`, and this diameter upper-bounds every pair value.

Layer: Model | Gap: Level 1 (Bregman diameter supremum from declared maximum)
Proof: build nonemptiness and boundedness of the Bregman value set from the
  declared maximizer, then combine `csSup_le`, `le_csSup`, `le_antisymm`, and
  `le_trans` in `ℝ`.
Source: Mathlib conditionally complete order and real supremum APIs
Used in: stochastic mirror descent Bregman diameter maximum and pairwise upper-bound estimates
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem bregmanDiameterSq_eq_declared_max
    {P : Type*} (V : P → P → ℝ) (pmax : P × P)
    (hmax : ∀ q : P × P, V q.1 q.2 ≤ V pmax.1 pmax.2) :
    ∃ p : P × P,
      bregmanDiameterSq V = V p.1 p.2 ∧
        ∀ q : P × P, V q.1 q.2 ≤ bregmanDiameterSq V := by
  have hexists : ∃ p : P × P, ∀ q : P × P, V q.1 q.2 ≤ V p.1 p.2 :=
    ⟨pmax, hmax⟩
  have hsne : (bregmanValueSet V).Nonempty :=
    bregmanValueSet_nonempty V hexists
  have hbdd : BddAbove (bregmanValueSet V) :=
    bregmanValueSet_bddAbove V hexists
  have hle : bregmanDiameterSq V ≤ V pmax.1 pmax.2 := by
    exact csSup_le hsne (by
      rintro y ⟨q, rfl⟩
      exact hmax q)
  have hge : V pmax.1 pmax.2 ≤ bregmanDiameterSq V := by
    exact le_csSup hbdd ⟨pmax, rfl⟩
  refine ⟨pmax, le_antisymm hle hge, ?_⟩
  intro q
  exact le_trans (hmax q) hge

/-- A Bregman formula at an interior representative gives the formula for the
corresponding next iterate.

If an interior point `xnextI` is transported to the carrier point `xNext`, and
the abstract Bregman kernel `V` satisfies the potential-gradient identity on
all interior representatives, then `V xNext x` expands to the literal formula
using the gradient selected at `xnextI`.

Layer: Model | Gap: Level 0 (interior Bregman formula transport)
Proof: substitute the carrier equality `toP xnextI = xNext`, then apply the
  assumed interior-point Bregman formula.
Source: Mathlib equality rewriting and real inner-product space APIs
Used in: stochastic mirror descent expansion of the prox-step Bregman term at
  an interior next iterate
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem bregmanDivergence_eq_formula_of_interior_iterate
    {E P IP : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (toP : IP → P) (v : P → ℝ) (grad : IP → E)
    (eval : P → E) {xNext x : P} (xnextI : IP)
    (hnext : toP xnextI = xNext)
    (h_formula :
      ∀ (y : IP) (z : P),
        V (toP y) z =
          v z - v (toP y) - ⟪grad y, eval z - eval (toP y)⟫_ℝ) :
    V xNext x =
      v x - v xNext - ⟪grad xnextI, eval x - eval xNext⟫_ℝ := by
  subst xNext
  exact h_formula xnextI x

/-- Carrier-level Bregman formula generated by a potential, an evaluation map into an
inner-product space, and an abstract carrier-gradient selector.

Layer: Model | Concept: Bregman
Proof: (definitional construction; all-carrier Bregman divergence formula using
  the potential difference and inner-product linearization at the base point)
Source: Mathlib inner product space and real vector space APIs
Used in: stochastic mirror descent carrier Bregman formula expansion with
  boundary-safe gradient extension
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def carrierBregmanFormula
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (v : P → ℝ) (eval : P → E) (grad : P → E) (x z : P) : ℝ :=
  v z - v x - ⟪grad x, eval z - eval x⟫_ℝ

/-- Definitional expansion of the carrier-level Bregman divergence formula.

Layer: Model | Gap: Level 0 (carrier Bregman formula unfolding)
Proof: by rfl after unfolding carrierBregmanFormula.
Source: Mathlib inner product space notation and definitional equality
Used in: stochastic mirror descent Bregman algebra simp normalization
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregmanFormula_def
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (v : P → ℝ) (eval : P → E) (grad : P → E) (x z : P) :
    carrierBregmanFormula v eval grad x z =
      v z - v x - ⟪grad x, eval z - eval x⟫_ℝ := by
  rfl

/-- Symmetric carrier Bregman divergence is the gradient monotonicity pairing.

The two carrier Bregman divergences in opposite directions sum to the inner
product of the gradient difference with the point difference.

Layer: Model | Gap: Level 0 (symmetric Bregman gradient pairing)
Proof: unfold `carrierBregmanDivergence`, rewrite the reverse displacement as a
  negation, distribute the inner product over subtraction, and normalize the
  additive terms with `abel`.
Source: Mathlib inner product space algebra and additive group normalization APIs
Used in: stochastic mirror descent symmetric Bregman expansion for gradient
  monotonicity and prox-step estimates
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregmanDivergence_add_swap_eq_inner_grad_sub
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} (v : {x : E // x ∈ X} → ℝ)
    (grad : {x : E // x ∈ X} → E) (z z' : {x : E // x ∈ X}) :
    carrierBregmanDivergence v grad z z' +
        carrierBregmanDivergence v grad z' z =
      ⟪grad z' - grad z, z'.1 - z.1⟫_ℝ := by
  unfold carrierBregmanDivergence
  have hrev : z.1 - z'.1 = -(z'.1 - z.1) := by
    abel
  rw [hrev, inner_neg_right, inner_sub_left]
  abel

/-- Carrier-level Bregman three-point identity for divergences realized by a
potential, carrier evaluation map, and carrier-gradient selector.

For any representation `V x z = v z - v x - ⟪grad x, eval z - eval x⟫_ℝ`,
the Bregman three-point identity holds after transporting points through the
carrier evaluation map.

Layer: Model | Gap: Level 0 (carrier-level Bregman three-point identity)
Proof: unfold the representation at the three point pairs, split
  `eval y - eval x` through `eval z`, and finish by inner-product linearity and
  ring normalization.
Source: Mathlib inner product algebra, additive group normalization, and ring
  normalization APIs
Used in: stochastic mirror descent carrier Bregman divergence algebra for
  prox-step three-point estimates
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregmanDivergence_three_point_identity
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (v : P → ℝ) (eval grad : P → E) (V : P → P → ℝ)
    (hV : ∀ x z, V x z = v z - v x - ⟪grad x, eval z - eval x⟫_ℝ)
    (x z y : P) :
    V x y = V x z + ⟪grad z - grad x, eval y - eval z⟫_ℝ + V z y := by
  rw [hV x y, hV x z, hV z y]
  have hsplit : eval y - eval x = (eval y - eval z) + (eval z - eval x) := by
    abel
  rw [hsplit, inner_add_right, inner_sub_left]
  ring

/-- The carrier Bregman divergence reduces to the ambient interior-gradient formula.

When the carrier gradient at an interior base point is the Fréchet gradient of the
ambient potential, the subtype-carrier Bregman wrapper is exactly the usual
formula `v z - v x - ⟪∇ vInterior x, z - x⟫_ℝ`.

Layer: Model | Gap: Level 0 (carrier Bregman interior formula)
Proof: unfold `carrierBregmanDivergence` and rewrite the carrier-gradient
  selector with `hgrad`; `simp` discharges the subtype coercions.
Source: Mathlib inner product spaces, Fréchet derivative notation, and Set
  interior APIs
Used in: stochastic mirror descent prox-step Bregman objective expansion on
  feasible carrier interiors
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregmanDivergence_eq_interior_formula
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ} {vInterior : E → ℝ}
    {grad : {x : E // x ∈ X} → E}
    {x : {x : E // x ∈ interior X}} {z : {x : E // x ∈ X}}
    (hgrad : grad ⟨x.1, interior_subset x.2⟩ = ∇ vInterior x.1) :
    carrierBregmanDivergence v grad ⟨x.1, interior_subset x.2⟩ z =
      v z - v ⟨x.1, interior_subset x.2⟩ -
        ⟪∇ vInterior x.1, z.1 - x.1⟫_ℝ := by
  simp [carrierBregmanDivergence, hgrad]

/-- Carrier Bregman divergence has the literal intrinsic-interior relative-gradient form.

When the carrier-gradient selector at an intrinsic-interior base point agrees with
a prescribed intrinsic-interior gradient, the carrier Bregman divergence unfolds
to the standard relative-gradient formula.

Layer: Model | Gap: Level 0 (literal intrinsic-interior Bregman formula)
Proof: unfold `carrierBregmanDivergence` and rewrite the carrier-gradient equality
  `hgrad`; `simpa` discharges the subtype coercions.
Source: Mathlib intrinsic-interior convex geometry and real inner product APIs
Used in: stochastic mirror descent relative-gradient Bregman prox-step algebra
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem literalIntrinsicCarrierBregmanDivergence
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ}
    {grad : {x : E // x ∈ X} → E}
    {gradI : {x : E // x ∈ intrinsicInterior ℝ X} → E}
    {x : {x : E // x ∈ intrinsicInterior ℝ X}} {z : {x : E // x ∈ X}}
    (hgrad : grad ⟨x.1, intrinsicInterior_subset x.2⟩ = gradI x) :
    carrierBregmanDivergence v grad ⟨x.1, intrinsicInterior_subset x.2⟩ z =
      v z - v ⟨x.1, intrinsicInterior_subset x.2⟩ -
        ⟪gradI x, z.1 - x.1⟫_ℝ := by
  simpa [carrierBregmanDivergence, hgrad]

/-- Interior carrier points have nonnegative carrier Bregman divergence.

For carrier points `x` and `z` in the topological interior of `X`, a strongly
convex differentiable intrinsic-interior extension of the potential makes the
carrier Bregman divergence nonnegative.

Layer: Model | Gap: Level 1 (interior Bregman nonnegativity for carrier points)
Proof: topological-interior membership is promoted to intrinsic-interior
  membership, then the intrinsic-interior strong-convexity lower bound is
  applied; `nlinarith` with `sq_nonneg` discharges the remaining norm-square
  lower bound.
Source: Mathlib convex analysis, intrinsic interior, strong convexity, and
  ordered-ring linear arithmetic APIs
Used in: stochastic mirror descent prox-step Bregman nonnegativity for interior
  carrier iterates
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregmanDivergence_nonneg_of_interior
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ} {vInterior : E → ℝ}
    {grad : {x : E // x ∈ X} → E} {x z : {x : E // x ∈ X}}
    (hvx : v x = vInterior x.1) (hvz : v z = vInterior z.1)
    (h_strong : StrongConvexOn (intrinsicInterior ℝ X) 1 vInterior)
    (h_diff : DifferentiableOn ℝ vInterior (intrinsicInterior ℝ X))
    (hgrad :
      ⟪grad x, z.1 - x.1⟫_ℝ =
        ⟪gradientWithin vInterior (intrinsicInterior ℝ X) x.1, z.1 - x.1⟫_ℝ)
    (hx : x.1 ∈ interior X) (hz : z.1 ∈ interior X) :
    0 ≤ carrierBregmanDivergence v grad x z := by
  have hxi : x.1 ∈ intrinsicInterior ℝ X := interior_subset_intrinsicInterior hx
  have hzi : z.1 ∈ intrinsicInterior ℝ X := interior_subset_intrinsicInterior hz
  have h :=
    carrierBregmanDivergence_lower_bound_of_strongConvexOn_intrinsicInterior
      (X := X) (v := v) (vInterior := vInterior) (grad := grad)
      (x := x) (z := z) hvx hvz h_strong h_diff hgrad hxi hzi
  nlinarith [sq_nonneg ‖x.1 - z.1‖]

/-- Interior-safe Bregman nonnegativity from an interior quadratic lower bound.

If a carrier Bregman-like value `V x z` dominates one half of the squared
distance between evaluated carrier points whenever both points are interior,
then every such interior value is nonnegative.

Layer: Model | Gap: Level 1 (interior-safe Bregman nonnegativity)
Proof: specialize the quadratic lower bound at the two interior points, use
  nonnegativity of squared norms, and close the real arithmetic goal with
  `nlinarith`.
Source: Mathlib real normed-space order and nonlinear arithmetic APIs
Used in: stochastic mirror descent interior Bregman lower-bound safety
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregman_nonneg_of_interior
    {P E : Type*} [NormedAddCommGroup E]
    (V : P → P → ℝ) (eval : P → E) (interiorPred : P → Prop)
    (h_lower : ∀ x z : P, interiorPred x → interiorPred z →
      (1 / 2 : ℝ) * ‖eval x - eval z‖ ^ 2 ≤ V x z)
    {x z : P} (hx : interiorPred x) (hz : interiorPred z) :
    0 ≤ V x z := by
  have h := h_lower x z hx hz
  nlinarith [sq_nonneg ‖eval x - eval z‖]

/-- Every carrier Bregman value is bounded by the carrier diameter square.

The Bregman diameter square is the supremum of all carrier-pair divergence
values, so any realized pair value lies below it when the range is bounded above.

Layer: Model | Gap: Level 0 (carrier Bregman diameter upper bound)
Proof: apply `le_csSup` to the bounded-above range of carrier-pair values,
  using `(x, z)` as the witnessing pair in the range.
Source: Mathlib order bounds and conditionally complete lattice supremum APIs
Used in: stochastic mirror descent carrier Bregman diameter control
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
theorem carrierBregmanDivergence_le_diameterSq
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} (V : {x : E // x ∈ X} → {x : E // x ∈ X} → ℝ)
    (h_bddAbove :
      BddAbove (Set.range fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
        V p.1 p.2))
    (x z : {x : E // x ∈ X}) :
    V x z ≤ sSup (Set.range fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
      V p.1 p.2) := by
  exact le_csSup h_bddAbove ⟨(x, z), rfl⟩

/-- A carrier Bregman lower bound extends from a dense carrier subset to all carrier pairs.

If the carrier Bregman divergence is continuous on the product carrier and the
quadratic lower bound holds on a dense subset of carrier points, then the same
bound holds for every pair of carrier points.

Layer: Model | Gap: Level 1 (dense carrier lower-bound extension)
Proof: subtract the quadratic term and apply dense-extension nonnegativity for
  continuous functions; product density and continuity of norms supply the
  hypotheses, and `linarith` converts the local bound.
Source: Mathlib topology APIs for dense sets, products, continuous functions,
  and ordered real inequalities
Used in: stochastic mirror descent carrier Bregman lower-bound transfer from
  dense interior points to boundary carrier pairs
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregmanDivergence_lower_bound_all_carrier_from_dense_set
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ}
    {grad : {x : E // x ∈ X} → E}
    (s : Set {x : E // x ∈ X})
    (hcont : ContinuousOn (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
      carrierBregmanDivergence v grad p.1 p.2) Set.univ)
    (hdense : Dense s)
    (hlocal : ∀ x z : {x : E // x ∈ X}, x ∈ s → z ∈ s →
      (1 / 2 : ℝ) * ‖x.1 - z.1‖ ^ 2 ≤ carrierBregmanDivergence v grad x z)
    (x z : {x : E // x ∈ X}) :
    (1 / 2 : ℝ) * ‖x.1 - z.1‖ ^ 2 ≤ carrierBregmanDivergence v grad x z := by
  exact sub_nonneg.mp (nonneg_of_continuousOn_of_dense_nonneg_for_model
    (D := fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
      carrierBregmanDivergence v grad p.1 p.2 - (1 / 2 : ℝ) * ‖p.1.1 - p.2.1‖ ^ 2)
    (s := s ×ˢ s)
    (by
      have hnorm :
          Continuous (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} =>
            (1 / 2 : ℝ) * ‖p.1.1 - p.2.1‖ ^ 2) :=
        continuous_const.mul
          (((continuous_subtype_val.comp continuous_fst).sub
            (continuous_subtype_val.comp continuous_snd)).norm.pow 2)
      exact hcont.sub hnorm.continuousOn)
    (by
      rw [dense_iff_closure_eq] at hdense ⊢
      rw [closure_prod_eq, hdense]
      simp)
    (by
      rintro p ⟨hp1, hp2⟩
      change 0 ≤ carrierBregmanDivergence v grad p.1 p.2 -
        (1 / 2 : ℝ) * ‖p.1.1 - p.2.1‖ ^ 2
      have h := hlocal p.1 p.2 hp1 hp2
      linarith)
    (x, z))

/-- Carrier Bregman continuity follows from a full-dimensional convex carrier.

If a convex carrier `X` has nonempty topological interior, then `X` is a
`UniqueDiffOn` set, so any all-carrier Bregman divergence whose paired carrier
map is continuous under `UniqueDiffOn` is continuous on the full carrier
product.

Layer: Model | Gap: Level 1 (Bregman carrier continuity from nonempty interior)
Proof: apply `uniqueDiffOn_convex` to convert convexity and nonempty interior
  into `UniqueDiffOn`, then use the supplied continuity transfer hypothesis.
Source: Mathlib convex analysis `UniqueDiffOn` API
Used in: stochastic mirror descent Bregman prox-step carrier continuity
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregmanDivergence_continuousOn_of_nonempty_interior
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} {V : {x : E // x ∈ X} → {x : E // x ∈ X} → ℝ}
    (hX_convex : Convex ℝ X)
    (hV_uniqueDiffOn : UniqueDiffOn ℝ X →
      ContinuousOn (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} => V p.1 p.2) Set.univ)
    (hXint : (interior X).Nonempty) :
    ContinuousOn (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} => V p.1 p.2) Set.univ := by
  exact hV_uniqueDiffOn (uniqueDiffOn_convex hX_convex hXint)

/-- A fixed-right left section of an all-carrier Bregman kernel is measurable.

If the paired carrier map `(x, z) ↦ V x z` is continuous on the full product
carrier, then for every fixed `z` the section `x ↦ V x z` is measurable.

Layer: Model | Gap: Level 0 (Bregman left-section measurability)
Proof: convert continuity on `Set.univ` to global continuity, compose with the
  continuous embedding `x ↦ (x, z)`, and use the continuous-to-measurable API.
Source: Mathlib topology and Borel measurability APIs
Used in: stochastic mirror descent Bregman prox objective measurability
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregman_measurable_left
    {P : Type*} [TopologicalSpace P] [MeasurableSpace P] [BorelSpace P]
    (V : P → P → ℝ)
    (hcont : ContinuousOn (fun p : P × P => V p.1 p.2) Set.univ)
    (z : P) :
    Measurable (fun x : P => V x z) := by
  have hcont' : Continuous (fun p : P × P => V p.1 p.2) := by
    exact continuousOn_univ.mp hcont
  exact (hcont'.comp (continuous_id.prodMk continuous_const)).measurable

/-- A carrier Bregman left section is measurable from measurable value, evaluation,
and gradient data.

For a fixed carrier point `z`, the map
`x ↦ v z - v x - ⟪grad x, eval z - eval x⟫_ℝ` is measurable whenever the
carrier potential, carrier evaluation map, and carrier-gradient selector are
measurable.

Layer: Model | Gap: Level 0 (Bregman left-section measurability)
Proof: combine measurability of subtraction with measurability of the inner
  product, using `continuous_inner.measurable` composed with the measurable
  gradient and displacement maps.
Source: Mathlib measure-theory measurability APIs and continuous inner-product topology
Used in: stochastic mirror descent Bregman formula measurability for prox-step integrands
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregman_measurable_left_of_measurable_grad
    {P : Type*} [MeasurableSpace P]
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [MeasurableSpace E] [MeasurableSub₂ E] [OpensMeasurableSpace (E × E)]
    {v : P → ℝ} {eval grad : P → E}
    (hv : Measurable v) (heval : Measurable eval) (hgrad : Measurable grad)
    (z : P) :
    Measurable (fun x : P => v z - v x - ⟪grad x, eval z - eval x⟫_ℝ) := by
  have hdisp : Measurable (fun x : P => eval z - eval x) :=
    measurable_const.sub heval
  have hinner :
      Measurable (fun x : P => ⟪grad x, eval z - eval x⟫_ℝ) := by
    simpa [Function.comp_def] using
      (continuous_inner.measurable.comp (hgrad.prodMk hdisp))
  exact (measurable_const.sub hv).sub hinner

/-- A carrier Bregman left section is measurable under nonempty-interior carrier regularity.

For a convex carrier `X`, if the two-argument carrier Bregman kernel becomes
jointly continuous whenever `X` is uniquely differentiable, then nonempty
interior gives measurability of every left section `x ↦ V x z`.

Layer: Model | Gap: Level 1 (Bregman section measurability via nonempty interior)
Proof: reduce to the left-section measurability lemma for jointly continuous
  carrier kernels, using the nonempty-interior bridge from convexity to
  carrier Bregman continuity.
Source: Mathlib topology continuity, Borel measurability, and convex
  unique-differentiability APIs
Used in: stochastic mirror descent Bregman prox objective section measurability
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem carrierBregman_measurable_left_of_nonemptyInterior
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [MeasurableSpace E] [BorelSpace E]
    {X : Set E} {V : {x : E // x ∈ X} → {x : E // x ∈ X} → ℝ}
    (hX_convex : Convex ℝ X)
    (hV_uniqueDiffOn : UniqueDiffOn ℝ X →
      ContinuousOn (fun p : {x : E // x ∈ X} × {x : E // x ∈ X} => V p.1 p.2) Set.univ)
    (hXint : (interior X).Nonempty) (z : {x : E // x ∈ X}) :
    Measurable (fun x : {x : E // x ∈ X} => V x z) := by
  exact carrierBregman_measurable_left (V := V)
    (carrierBregmanDivergence_continuousOn_of_nonempty_interior
      hX_convex hV_uniqueDiffOn hXint) z

namespace SOptLib

/-- Compatibility alias for the carrier-level Bregman divergence in the `SOptLib` namespace. -/
noncomputable abbrev carrierBregmanDivergence
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} (v : {x : E // x ∈ X} → ℝ)
    (grad : {x : E // x ∈ X} → E) (x z : {x : E // x ∈ X}) : ℝ :=
  _root_.carrierBregmanDivergence v grad x z

/-- Carrier-restricted Bregman divergence obtained by reusing an existing
two-point divergence on the same carrier.

Layer: Model | Concept: Bregman
Proof: (definitional construction; identity wrapper for a two-point Bregman divergence on a feasible carrier)
Source: Mathlib function application and real-valued model-object notation
Used in: nonconvex stochastic mirror descent constrained prox-step Bregman divergence
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
noncomputable def carrierBregmanDivergenceAlias
    {P : Type*} (V : P → P → ℝ) (z x : P) : ℝ :=
  V z x

/-- The carrier-restricted Bregman divergence alias unfolds to the underlying
two-point divergence.

Layer: Model | Gap: Level 0 (carrier Bregman divergence alias unfolding)
Proof: by rfl after unfolding carrierBregmanDivergenceAlias.
Source: Mathlib function application and definitional equality APIs
Used in: nonconvex stochastic mirror descent constrained prox-step Bregman divergence
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
@[simp]
theorem carrierBregmanDivergenceAlias_apply
    {P : Type*} (V : P → P → ℝ) (z x : P) :
    carrierBregmanDivergenceAlias V z x = V z x := by
  rfl

/-- Centered quadratic potential `x ↦ (μ / 2) * ‖x - z‖ ^ 2`.

This names the Euclidean squared-distance regularizer used in proximal
subproblems, with center and weight left as explicit parameters.

Layer: Model | Concept: Prox quadratic potential
Proof: (definitional construction; centered squared-distance regularizer)
Source: Mathlib normed additive group norm algebra and Hilbert-space
  squared-distance calculus
Used in: randomized accelerated proximal-point quadratic subproblem potential
  and Bregman expansion
Book citation: book/FOML/RandomizedAcceleratedProximalPoint.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, randomized accelerated proximal-point method -/
noncomputable def centeredQuadraticPotential
    {E : Type*} [NormedAddCommGroup E] (μ : ℝ) (z x : E) : ℝ :=
  (μ / 2) * ‖x - z‖ ^ 2

/-- The centered quadratic potential unfolds to its squared-distance formula.

Layer: Model | Gap: Level 0 (centered quadratic potential unfolding)
Proof: by rfl after unfolding `centeredQuadraticPotential`.
Source: Mathlib normed additive group norm algebra and Hilbert-space
  squared-distance calculus
Used in: randomized accelerated proximal-point quadratic subproblem potential
  and Bregman expansion
Book citation: book/FOML/RandomizedAcceleratedProximalPoint.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, randomized accelerated proximal-point method -/
@[simp] theorem centeredQuadraticPotential_def
    {E : Type*} [NormedAddCommGroup E] (μ : ℝ) (z x : E) :
    centeredQuadraticPotential μ z x = (μ / 2) * ‖x - z‖ ^ 2 :=
  rfl

/-- The centered quadratic potential is nonnegative when its weight is
nonnegative.

Layer: Model | Gap: Level 0 (centered quadratic potential nonnegativity)
Proof: product of the nonnegative coefficient `μ / 2` and a squared norm.
Source: Mathlib ordered-ring algebra and norm-square nonnegativity
Used in: proximal subproblem lower bounds and Lyapunov-potential estimates -/
theorem centeredQuadraticPotential_nonneg_of_nonneg
    {E : Type*} [NormedAddCommGroup E] {μ : ℝ} (hμ : 0 ≤ μ) (z x : E) :
    0 ≤ centeredQuadraticPotential μ z x := by
  rw [centeredQuadraticPotential_def]
  exact mul_nonneg (div_nonneg hμ (by norm_num)) (sq_nonneg ‖x - z‖)

/-- The centered quadratic potential vanishes at its center.

Layer: Model | Gap: Level 0 (centered quadratic potential at center)
Proof: the displacement from the center to itself is zero.
Source: Mathlib normed additive group simplification
Used in: proximal-center simplifications and Bregman endpoint reductions -/
@[simp] theorem centeredQuadraticPotential_self
    {E : Type*} [NormedAddCommGroup E] (μ : ℝ) (z : E) :
    centeredQuadraticPotential μ z z = 0 := by
  simp [centeredQuadraticPotential]

/-- Centered quadratic Bregman divergence generated by
`x ↦ (μ / 2) * ‖x - z‖ ^ 2`.

This packages the three-term Bregman expression with the canonical gradient
`μ • (y - z)` at the base point `y`.

Layer: Model | Concept: Bregman
Proof: (definitional construction; centered quadratic potential minus its
  linearization at the base point)
Source: Mathlib real inner-product spaces and norm-square proximal geometry
Used in: randomized accelerated proximal-point quadratic subproblem Bregman
  expansion and nonnegativity
Book citation: book/FOML/RandomizedAcceleratedProximalPoint.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, randomized accelerated proximal-point method -/
noncomputable def centeredQuadraticBregman
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (μ : ℝ) (z x y : E) : ℝ :=
  centeredQuadraticPotential μ z x -
    centeredQuadraticPotential μ z y - ⟪μ • (y - z), x - y⟫_ℝ

/-- The centered quadratic Bregman divergence unfolds to the potential
difference minus the linearization at the base point.

Layer: Model | Gap: Level 0 (centered quadratic Bregman unfolding)
Proof: by rfl after unfolding `centeredQuadraticBregman`.
Source: Mathlib real inner-product spaces and norm-square proximal geometry
Used in: randomized accelerated proximal-point quadratic subproblem Bregman
  expansion and nonnegativity
Book citation: book/FOML/RandomizedAcceleratedProximalPoint.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, randomized accelerated proximal-point method -/
@[simp] theorem centeredQuadraticBregman_def
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (μ : ℝ) (z x y : E) :
    centeredQuadraticBregman μ z x y =
      centeredQuadraticPotential μ z x -
        centeredQuadraticPotential μ z y - ⟪μ • (y - z), x - y⟫_ℝ := by
  rfl

/-- The centered quadratic Bregman divergence is exactly the weighted squared
distance between its endpoint and base point.

Layer: Model | Gap: Level 0 (centered quadratic Bregman closed form)
Proof: expand the two squared norms and the linearization term, then collect.
Source: Mathlib real inner-product norm-square identities
Used in: proximal and mirror-style nonnegativity and descent estimates -/
theorem centeredQuadraticBregman_eq_norm_sq
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (μ : ℝ) (z x y : E) :
    centeredQuadraticBregman μ z x y = (μ / 2) * ‖x - y‖ ^ 2 := by
  rw [centeredQuadraticBregman_def]
  rw [centeredQuadraticPotential_def, centeredQuadraticPotential_def]
  rw [norm_sub_sq_real x z, norm_sub_sq_real y z, norm_sub_sq_real x y]
  simp [inner_sub_left, inner_sub_right, inner_smul_left, real_inner_comm]
  ring_nf

/-- The centered quadratic Bregman divergence is nonnegative for nonnegative
weight.

Layer: Model | Gap: Level 0 (centered quadratic Bregman nonnegativity)
Proof: use the weighted squared-distance closed form.
Source: Mathlib ordered-ring algebra and norm-square nonnegativity
Used in: proximal and mirror-style Lyapunov estimates -/
theorem centeredQuadraticBregman_nonneg_of_nonneg
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {μ : ℝ} (hμ : 0 ≤ μ) (z x y : E) :
    0 ≤ centeredQuadraticBregman μ z x y := by
  rw [centeredQuadraticBregman_eq_norm_sq]
  exact mul_nonneg (div_nonneg hμ (by norm_num)) (sq_nonneg ‖x - y‖)

/-- Three-point identity for centered quadratic Bregman divergence.

For the kernel generated by `x ↦ (μ / 2) * ‖x - z‖ ^ 2`, the Bregman term
from base `a` to endpoint `c` splits through an intermediate base `b`, with
the correction written as the explicit difference of centered quadratic
gradients.

Layer: Model | Gap: Level 0 (centered quadratic Bregman three-point identity)
Proof: expand the centered quadratic Bregman definition and centered quadratic
  potential, normalize inner-product algebra, and collect real scalar terms.
Source: Mathlib real inner-product norm-square algebra and Bregman geometry
Used in: randomized accelerated proximal-point two-anchor prox optimality
  conversion from first-order terms to Bregman differences
Book citation: book/FOML/RandomizedAcceleratedProximalPoint.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, randomized accelerated proximal-point method -/
theorem centeredQuadraticBregman_three_point_identity
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (μ : ℝ) (z a b c : E) :
    centeredQuadraticBregman μ z c a =
      centeredQuadraticBregman μ z b a +
        ⟪μ • (b - z) - μ • (a - z), c - b⟫_ℝ +
      centeredQuadraticBregman μ z c b := by
  unfold centeredQuadraticBregman centeredQuadraticPotential
  simp [inner_sub_left, inner_sub_right, inner_smul_left]
  ring_nf

end SOptLib

/-- Carrier Bregman divergence agrees with a literal interior-gradient formula.

For a feasible carrier `X`, if the carrier gradient at every topological
interior representative agrees with a supplied interior gradient selector, then
the carrier Bregman divergence based at that interior point unfolds to the
paper-literal potential difference and linearization term.

Layer: Model | Gap: Level 0 (carrier Bregman literal interior formula)
Proof: unfold the carrier Bregman divergence and rewrite the carrier-gradient
  selector using the interior bridge hypothesis.
Source: Mathlib real inner-product spaces and subtype coercion APIs
Used in: nonconvex stochastic mirror descent Bregman distance expansion at
  feasible interior prox bases
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic mirror descent -/
theorem carrierBregmanDivergence_eq_literal_of_interior
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} (nu : {x : E // x ∈ X} → ℝ)
    (grad : {x : E // x ∈ X} → E)
    (gradInterior : {x : E // x ∈ interior X} → E)
    (hgrad :
      ∀ z : {x : E // x ∈ interior X},
        grad ⟨z.1, interior_subset z.2⟩ = gradInterior z)
    (z : {x : E // x ∈ interior X}) (x : {x : E // x ∈ X}) :
    SOptLib.carrierBregmanDivergence nu grad ⟨z.1, interior_subset z.2⟩ x =
      nu x - nu ⟨z.1, interior_subset z.2⟩ - ⟪gradInterior z, x.1 - z.1⟫_ℝ := by
  unfold SOptLib.carrierBregmanDivergence
  simp [_root_.carrierBregmanDivergence, hgrad z]

/-- Along a feasible segment, the carrier Bregman difference has the expected
right derivative at the segment base point.

For a carrier potential represented by an ambient differentiable function, this
identifies the derivative at `0` of
`t ↦ V x (lineMap xp u t) - V x xp` with the difference of the carrier
gradients paired against the segment direction.

Layer: Model | Gap: Level 1 (carrier Bregman segment derivative)
Proof: compose the ambient derivative of the potential with the affine segment,
then expand the Bregman formula and normalize the inner-product algebra.
Source: Mathlib within-derivative chain rule and inner-product affine segment APIs
Used in: stochastic mirror descent prox-step variational inequality
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
theorem carrierBregman_segment_difference_hasDerivWithinAt_zero
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} (hX_convex : Convex ℝ X)
    (nu : {x : E // x ∈ X} → ℝ) (nuAmbient : E → ℝ)
    (grad : {x : E // x ∈ X} → E)
    (V : {x : E // x ∈ X} → {x : E // x ∈ X} → ℝ)
    (hnu_eq : ∀ y : {x : E // x ∈ X}, nu y = nuAmbient y.1)
    (hnu_diff : DifferentiableOn ℝ nuAmbient X)
    (hgrad_apply :
      ∀ (y : {x : E // x ∈ X}) (d : E),
        (fderivWithin ℝ nuAmbient X y.1) d = ⟪grad y, d⟫_ℝ)
    (hV :
      ∀ x z : {x : E // x ∈ X},
        V x z = nu z - nu x - ⟪grad x, z.1 - x.1⟫_ℝ)
    (x xp u : {x : E // x ∈ X}) :
    let d : E := u.1 - xp.1
    let β : ℝ → ℝ := fun t =>
      if ht : t ∈ Set.Icc (0 : ℝ) 1 then
        V x ⟨AffineMap.lineMap xp.1 u.1 t,
          hX_convex.lineMap_mem xp.2 u.2 ht⟩ - V x xp
      else 0
    HasDerivWithinAt β
      ⟪grad xp - grad x, d⟫_ℝ
      (Set.Icc (0 : ℝ) 1) 0 := by
  classical
  let d : E := u.1 - xp.1
  let s : Set ℝ := Set.Icc (0 : ℝ) 1
  let line : ℝ → E := fun t => AffineMap.lineMap xp.1 u.1 t
  let β : ℝ → ℝ := fun t =>
    if ht : t ∈ Set.Icc (0 : ℝ) 1 then
      V x ⟨AffineMap.lineMap xp.1 u.1 t,
        hX_convex.lineMap_mem xp.2 u.2 ht⟩ - V x xp
    else 0
  have hline_mem : ∀ t ∈ s, line t ∈ X := by
    intro t ht
    exact hX_convex.lineMap_mem xp.2 u.2 ht
  have hmaps : Set.MapsTo line s X := by
    intro t ht
    exact hline_mem t ht
  have hline_deriv : HasDerivWithinAt line d s 0 := by
    simpa [line, d] using
      (AffineMap.hasDerivWithinAt_lineMap (a := xp.1) (b := u.1)
        (s := s) (x := (0 : ℝ)))
  have hνdiff : DifferentiableWithinAt ℝ nuAmbient X xp.1 :=
    hnu_diff xp.1 xp.2
  have hνseg : HasDerivWithinAt (fun t => nuAmbient (line t))
      ((fderivWithin ℝ nuAmbient X xp.1) d) s 0 := by
    simpa [Function.comp_def] using
      hνdiff.hasFDerivWithinAt.comp_hasDerivWithinAt_of_eq 0 hline_deriv hmaps
        (by simp [line])
  have hνseg' : HasDerivWithinAt (fun t => nuAmbient (line t))
      ⟪grad xp, d⟫_ℝ s 0 := by
    simpa [hgrad_apply xp d] using hνseg
  have hlin : HasDerivWithinAt (fun t : ℝ => t * ⟪grad x, d⟫_ℝ)
      ⟪grad x, d⟫_ℝ s 0 := by
    simpa using (hasDerivWithinAt_id (x := (0 : ℝ)) (s := s)).mul_const
      ⟪grad x, d⟫_ℝ
  have hderiv_expr : HasDerivWithinAt
      (fun t : ℝ => (nuAmbient (line t) - nuAmbient xp.1) -
        t * ⟪grad x, d⟫_ℝ)
      (⟪grad xp, d⟫_ℝ - ⟪grad x, d⟫_ℝ) s 0 := by
    exact (hνseg'.sub_const (nuAmbient xp.1)).sub hlin
  have heq : ∀ t ∈ s, β t =
      (fun t : ℝ => (nuAmbient (line t) - nuAmbient xp.1) -
        t * ⟪grad x, d⟫_ℝ) t := by
    intro t ht
    have htI : t ∈ Set.Icc (0 : ℝ) 1 := by simpa [s] using ht
    have hseg_sub : (AffineMap.lineMap xp.1 u.1 t) - xp.1 = t • d := by
      simp [d, AffineMap.lineMap_apply_module']
    have hnu_line : nu ⟨AffineMap.lineMap xp.1 u.1 t,
        hX_convex.lineMap_mem xp.2 u.2 htI⟩ = nuAmbient (line t) := by
      simpa [line] using
        hnu_eq ⟨AffineMap.lineMap xp.1 u.1 t,
          hX_convex.lineMap_mem xp.2 u.2 htI⟩
    have hnu_xp : nu xp = nuAmbient xp.1 := by
      simpa using hnu_eq xp
    have hinner_diff :
        ⟪grad x, (AffineMap.lineMap xp.1 u.1 t) - x.1⟫_ℝ -
            ⟪grad x, xp.1 - x.1⟫_ℝ =
          t * ⟪grad x, d⟫_ℝ := by
      calc
        ⟪grad x, (AffineMap.lineMap xp.1 u.1 t) - x.1⟫_ℝ -
            ⟪grad x, xp.1 - x.1⟫_ℝ =
            ⟪grad x,
              ((AffineMap.lineMap xp.1 u.1 t) - x.1) - (xp.1 - x.1)⟫_ℝ := by
          rw [← inner_sub_right]
        _ = ⟪grad x, (AffineMap.lineMap xp.1 u.1 t) - xp.1⟫_ℝ := by
          congr 1
          abel
        _ = ⟪grad x, t • d⟫_ℝ := by
          rw [hseg_sub]
        _ = t * ⟪grad x, d⟫_ℝ := by
          simp [inner_smul_right]
    calc
      β t = V x ⟨AffineMap.lineMap xp.1 u.1 t,
          hX_convex.lineMap_mem xp.2 u.2 htI⟩ - V x xp := by
        simp only [β]
        rw [dif_pos htI]
      _ = (nuAmbient (line t) - nuAmbient xp.1) - t * ⟪grad x, d⟫_ℝ := by
        rw [hV, hV, hnu_line, hnu_xp]
        rw [← hinner_diff]
        ring
  have hβ : HasDerivWithinAt β
      (⟪grad xp, d⟫_ℝ - ⟪grad x, d⟫_ℝ) s 0 := by
    exact hderiv_expr.congr heq (heq 0 (by norm_num [s]))
  have hval : ⟪grad xp, d⟫_ℝ - ⟪grad x, d⟫_ℝ =
      ⟪grad xp - grad x, d⟫_ℝ := by
    rw [inner_sub_left]
  simpa [d, s, β, hval] using hβ

/-- A strongly monotone distance-generator gradient controls squared distance.

For an abstract feasible carrier `P`, an evaluation map into an ambient Hilbert
space, and a selected gradient map, the paper's one-strong-convexity gradient
inequality can be used directly at any two carrier points.

Layer: Model | Gap: Level 0 (distance-generator gradient strong monotonicity)
Proof: specialize the assumed strong-monotonicity inequality to the requested
  carrier points.
Source: Mathlib real inner-product spaces and normed additive group APIs
Used in: nonconvex stochastic mirror descent prox-step stability from
  distance-generator strong convexity
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/assumptions/3
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic mirror descent -/
theorem sq_norm_le_inner_gradient_sub_of_strong_distance_generator
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (grad : P → E) (eval : P → E)
    (hstrong :
      ∀ x z : P,
        ‖eval x - eval z‖ ^ 2 ≤
          ⟪eval x - eval z, grad x - grad z⟫_ℝ)
    (x z : P) :
    ‖eval x - eval z‖ ^ 2 ≤
      ⟪eval x - eval z, grad x - grad z⟫_ℝ := by
  exact hstrong x z

/-- Strong convexity on a set with respect to a supplied gauge.

`StrongConvexOnWithGauge s mu rho f` is the Jensen-form strong-convexity
inequality where the quadratic penalty is measured by an externally supplied
function `rho : E -> Real`, rather than by the ambient norm.

Layer: Model | Concept: Objective
Proof: (definitional construction; gauge-relative Jensen strong-convexity predicate)
Source: Mathlib convex analysis APIs for `ConvexOn` and `StrongConvexOn`
Used in: stochastic block mirror descent block DGF assumptions and seminorm
  Bregman lower bounds
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
def StrongConvexOnWithGauge
    {E : Type*} [AddCommGroup E] [Module ℝ E]
    (s : Set E) (mu : ℝ) (rho : E → ℝ) (f : E → ℝ) : Prop :=
  ∀ ⦃x⦄, x ∈ s → ∀ ⦃y⦄, y ∈ s → ∀ ⦃a b : ℝ⦄,
    0 ≤ a → 0 ≤ b → a + b = 1 →
      f (a • x + b • y) ≤
        a * f x + b * f y - mu / 2 * a * b * (rho (x - y)) ^ 2

/-- The supplied-gauge strong-convexity predicate unfolds to its Jensen inequality.

Layer: Model | Gap: Level 0 (gauge-relative strong-convexity formula)
Proof: by rfl after unfolding `StrongConvexOnWithGauge`.
Source: Mathlib convex analysis APIs for `ConvexOn` and `StrongConvexOn`
Used in: stochastic block mirror descent block DGF assumptions and seminorm
  Bregman lower bounds
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem strongConvexOnWithGauge_def
    {E : Type*} [AddCommGroup E] [Module ℝ E]
    (s : Set E) (mu : ℝ) (rho : E → ℝ) (f : E → ℝ) :
    StrongConvexOnWithGauge s mu rho f =
      (∀ ⦃x⦄, x ∈ s → ∀ ⦃y⦄, y ∈ s → ∀ ⦃a b : ℝ⦄,
        0 ≤ a → 0 ≤ b → a + b = 1 →
          f (a • x + b • y) ≤
            a * f x + b * f y - mu / 2 * a * b * (rho (x - y)) ^ 2) := by
  rfl

/-- Weighted product-space Bregman potential from block divergences.

Given block coordinates, a sampling weight for each block, and a family of
block divergences, this is the inverse-probability weighted aggregate
`∑ᵢ pᵢ⁻¹ Vᵢ(zᵢ, xᵢ)` used as the Lyapunov potential for randomized block
mirror-descent updates.

Layer: Model | Concept: Bregman
Proof: (definitional construction; finite inverse-weighted sum of block
  Bregman kernels after coordinate projection)
Source: finite block-coordinate Bregman geometry in randomized coordinate
  mirror descent
Used in: stochastic block mirror descent aggregate Lyapunov potential for
  one-block prox-step telescoping
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/main_theorem/proof/0
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
noncomputable def weightedBlockBregmanPotential
    {ι : Type*} {E : Type*} [Fintype ι]
    (B : ι → Type*) (p : ι → ℝ) (coord : ∀ i, E → B i)
    (V : ∀ i, B i → B i → ℝ) (z x : E) : ℝ :=
  Finset.sum Finset.univ fun i => (p i)⁻¹ * V i (coord i z) (coord i x)

/-- The weighted block Bregman potential unfolds to its inverse-probability
finite block sum.

Layer: Model | Gap: Level 0 (weighted block Bregman potential formula)
Proof: by rfl after unfolding weightedBlockBregmanPotential.
Source: finite block-coordinate Bregman geometry in randomized coordinate
  mirror descent
Used in: stochastic block mirror descent aggregate Lyapunov potential for
  one-block prox-step telescoping
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/main_theorem/proof/0
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
@[simp] theorem weightedBlockBregmanPotential_def
    {ι : Type*} {E : Type*} [Fintype ι]
    (B : ι → Type*) (p : ι → ℝ) (coord : ∀ i, E → B i)
    (V : ∀ i, B i → B i → ℝ) (z x : E) :
    weightedBlockBregmanPotential B p coord V z x =
      Finset.sum Finset.univ (fun i => (p i)⁻¹ * V i (coord i z) (coord i x)) := by
  rfl

/-- Joint continuity of an evaluated carrier Bregman formula.

For a topological carrier `P` evaluated in a real Hilbert space `E`, the map
`(z, x) ↦ ν x - ν z - ⟪grad z, eval x - eval z⟫` is continuous whenever the
potential, selected gradient, and evaluation map are continuous.

Layer: Model | Gap: Level 1 (evaluated carrier Bregman continuity)
Proof: compose the continuous potential, gradient, and evaluation maps with
  product projections, then combine Mathlib continuity rules for subtraction
  and inner products.
Source: Mathlib topology of product spaces and continuous inner-product APIs
Used in: stochastic block mirror descent sampled block prox-step continuity
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/assumptions/3/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem evaluatedCarrierBregmanDivergence_continuous
    {P E : Type*} [TopologicalSpace P] [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {nu : P → ℝ} {grad : P → E} {eval : P → E}
    (hnu : Continuous nu) (hgrad : Continuous grad) (heval : Continuous eval) :
    Continuous (fun p : P × P =>
      nu p.2 - nu p.1 - ⟪grad p.1, eval p.2 - eval p.1⟫_ℝ) := by
  have hleft : Continuous (fun p : P × P => nu p.2) :=
    hnu.comp continuous_snd
  have hbase : Continuous (fun p : P × P => nu p.1) :=
    hnu.comp continuous_fst
  have hinner : Continuous (fun p : P × P =>
      ⟪grad p.1, eval p.2 - eval p.1⟫_ℝ) :=
    (hgrad.comp continuous_fst).inner
      ((heval.comp continuous_snd).sub (heval.comp continuous_fst))
  exact (hleft.sub hbase).sub hinner

/-- A carrier Bregman divergence using `gradientWithin` expands to the ambient
within-gradient formula.

If a carrier potential is the restriction of an ambient potential `ν` to a
feasible carrier `X`, then the carrier Bregman divergence whose gradient
selector is Mathlib's `gradientWithin ν X` is the usual potential difference
minus the within-gradient linearization at the base point.

Layer: Model | Gap: Level 0 (carrier Bregman within-gradient formula)
Proof: unfold the carrier Bregman definition, rewrite the two carrier potential
  values by the ambient realization hypothesis, and normalize the subtraction
  into the displayed `ν x - (ν z + inner)` form.
Source: Mathlib inner-product gradient notation and SOptLib carrier Bregman
  formula
Used in: stochastic block mirror descent block Bregman Eq. (4.6.7) expansion
  and restricted-potential prox algebra
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/assumptions/3
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem blockBregmanDivergence_eq_gradientWithin_formula
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {v : {x : E // x ∈ X} → ℝ} {ν : E → ℝ}
    (z x : {x : E // x ∈ X})
    (hv_eq : ∀ y : {x : E // x ∈ X}, v y = ν y.1) :
    carrierBregmanDivergence v
        (fun y : {x : E // x ∈ X} => gradientWithin ν X y.1) z x =
      ν x.1 - (ν z.1 + ⟪gradientWithin ν X z.1, x.1 - z.1⟫_ℝ) := by
  simp [carrierBregmanDivergence, hv_eq]
  ring

/-- A carrier Bregman divergence is unchanged by replacing the gradient selector
when the selected gradients have the same pairing with the endpoint displacement.

The carrier Bregman formula uses the gradient selector only through the scalar
`⟪grad z, x.1 - z.1⟫`.  This lemma records the corresponding pointwise
replacement rule for boundary-safe and source-facing carrier-gradient
realizations.

Layer: Model | Gap: Level 0 (carrier Bregman gradient-selector replacement)
Proof: unfold the carrier Bregman definition and rewrite the single gradient
  pairing scalar by the supplied pointwise equality.
Source: Mathlib real inner-product algebra and SOptLib carrier Bregman formula
Used in: stochastic block mirror descent boundary-safe block Bregman kernel
  replacement and mirror-prox Bregman algebra
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/assumptions/3
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem carrierBregmanDivergence_eq_of_gradient_pairing
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} (v : {x : E // x ∈ X} → ℝ)
    (grad grad' : {x : E // x ∈ X} → E) (z x : {x : E // x ∈ X})
    (hgrad : ⟪grad z, x.1 - z.1⟫_ℝ = ⟪grad' z, x.1 - z.1⟫_ℝ) :
    SOptLib.carrierBregmanDivergence v grad z x =
      SOptLib.carrierBregmanDivergence v grad' z x := by
  simp [SOptLib.carrierBregmanDivergence, carrierBregmanDivergence, hgrad]

private theorem right_derivative_nonneg_of_min_on_Icc_for_bregman
    {φ : ℝ → ℝ} {D : ℝ}
    (hderiv : HasDerivWithinAt φ D (Set.Icc (0 : ℝ) 1) 0)
    (hmin : ∀ t ∈ Set.Icc (0 : ℝ) 1, φ 0 ≤ φ t) :
    0 ≤ D := by
  have hderivIoc : HasDerivWithinAt φ D (Set.Ioc (0 : ℝ) 1) 0 :=
    hderiv.mono Set.Ioc_subset_Icc_self
  have htendIoc :
      Filter.Tendsto (slope φ 0) (𝓝[Set.Ioc (0 : ℝ) 1] 0) (𝓝 D) := by
    exact (hasDerivWithinAt_iff_tendsto_slope' (by simp)).mp hderivIoc
  have htend : Filter.Tendsto (slope φ 0) (𝓝[>] (0 : ℝ)) (𝓝 D) := by
    simpa [nhdsWithin_Ioc_eq_nhdsGT (by norm_num : (0 : ℝ) < 1)] using htendIoc
  haveI : Filter.NeBot (𝓝[>] (0 : ℝ)) := nhdsGT_neBot 0
  apply ge_of_tendsto htend
  filter_upwards [Ioc_mem_nhdsGT (by norm_num : (0 : ℝ) < 1)] with t ht
  have hdiff : 0 ≤ φ t - φ 0 :=
    sub_nonneg.mpr (hmin t ⟨ht.1.le, ht.2⟩)
  have hden : 0 ≤ t - 0 := sub_nonneg.mpr ht.1.le
  have hslope : 0 ≤ (φ t - φ 0) / (t - 0) := div_nonneg hdiff hden
  simpa [slope_def_field] using hslope

/-- A seminorm-strongly convex differentiable potential lower-bounds its Bregman
divergence by one half of the squared seminorm distance.

This is the seminorm analogue of the standard Bregman lower bound.  The
strong-convexity hypothesis is written directly as the Jensen inequality with
the supplied seminorm, so callers can instantiate it from local norm-specific
strong-convexity predicates without importing those predicates.

Layer: Model | Gap: Level 2 (seminorm Bregman lower bound)
Proof: restrict the potential to the segment from `z` to `x`, use the
  seminorm-strong convexity inequality to show an auxiliary residual has a
  minimum at `0`, and identify its right derivative using `gradientWithin`.
Source: Mathlib convex analysis, seminorm, within-derivative, and inner-product
  gradient APIs
Used in: stochastic block mirror descent block DGF lower bound and mirror-prox
  residual coercivity
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem bregman_lower_bound_of_strongConvexOnWithSeminorm_differentiableWithinAt
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {ν : E → ℝ} {p : Seminorm ℝ E} {z x : E}
    (hX : Convex ℝ X) (hνdiff : DifferentiableWithinAt ℝ ν X z)
    (hstrong :
      ∀ ⦃y⦄, y ∈ X → ∀ ⦃w⦄, w ∈ X → ∀ ⦃a b : ℝ⦄,
        0 ≤ a → 0 ≤ b → a + b = 1 →
          ν (a • y + b • w) ≤
            a * ν y + b * ν w - (1 : ℝ) / 2 * a * b * p (y - w) ^ 2)
    (hz : z ∈ X) (hx : x ∈ X) :
    (1 / 2 : ℝ) * p (x - z) ^ 2 ≤
      ν x - (ν z + ⟪gradientWithin ν X z, x - z⟫_ℝ) := by
  let d : E := x - z
  let s : Set ℝ := Set.Icc (0 : ℝ) 1
  let line : ℝ → E := fun t => AffineMap.lineMap z x t
  let q : ℝ := p (x - z) ^ 2
  let A : ℝ := ν x - ν z - (1 / 2 : ℝ) * q
  let r : ℝ → ℝ := fun t =>
    t * A + (1 / 2 : ℝ) * t ^ 2 * q - (ν (line t) - ν z)
  have hline_mem : ∀ t ∈ s, line t ∈ X := by
    intro t ht
    exact hX.lineMap_mem hz hx ht
  have hmaps : Set.MapsTo line s X := by
    intro t ht
    exact hline_mem t ht
  have hmin : ∀ t ∈ s, r 0 ≤ r t := by
    intro t ht
    have ht0 : 0 ≤ t := ht.1
    have ht1 : t ≤ 1 := ht.2
    have h1t : 0 ≤ 1 - t := sub_nonneg.mpr ht1
    have hsum : 1 - t + t = 1 := by ring
    have hsc := hstrong hz hx h1t ht0 hsum
    have hpnorm : p (z - x) = p (x - z) := by
      have hsub : z - x = -(x - z) := by abel
      rw [hsub, map_neg_eq_map]
    have hsc_line :
        ν (line t) ≤
          (1 - t) * ν z + t * ν x - (1 : ℝ) / 2 * (1 - t) * t * q := by
      simpa [line, q, hpnorm, AffineMap.lineMap_apply_module] using hsc
    have hr0 : r 0 = 0 := by simp [r, line]
    rw [hr0]
    dsimp [r, A]
    nlinarith [hsc_line]
  have hline_deriv : HasDerivWithinAt line d s 0 := by
    simpa [line, d] using
      (AffineMap.hasDerivWithinAt_lineMap (a := z) (b := x)
        (s := s) (x := (0 : ℝ)))
  have hνline : HasDerivWithinAt (fun t => ν (line t))
      ((fderivWithin ℝ ν X z) d) s 0 := by
    simpa [Function.comp_def] using
      hνdiff.hasFDerivWithinAt.comp_hasDerivWithinAt_of_eq 0 hline_deriv hmaps
        (by simp [line])
  have hgrad_apply :
      (fderivWithin ℝ ν X z) d = ⟪gradientWithin ν X z, d⟫_ℝ := by
    rw [gradientWithin, InnerProductSpace.toDual_symm_apply]
  have hνline_grad : HasDerivWithinAt (fun t => ν (line t))
      ⟪gradientWithin ν X z, d⟫_ℝ s 0 := by
    simpa [hgrad_apply] using hνline
  have hAderiv : HasDerivWithinAt (fun t : ℝ => t * A) A s 0 := by
    simpa using (hasDerivWithinAt_id (x := (0 : ℝ)) (s := s)).mul_const A
  have hquad : HasDerivWithinAt (fun t : ℝ => (1 / 2 : ℝ) * t ^ 2 * q) 0 s 0 := by
    have hp : HasDerivWithinAt (fun t : ℝ => t ^ 2)
        (2 * (0 : ℝ) ^ (2 - 1)) s 0 := by
      simpa using (hasDerivWithinAt_pow (2 : ℕ) (x := (0 : ℝ)) (s := s))
    have h := (hp.const_mul (1 / 2 : ℝ)).mul_const q
    convert h using 1
    ring
  have hνsub : HasDerivWithinAt (fun t : ℝ => ν (line t) - ν z)
      ⟪gradientWithin ν X z, d⟫_ℝ s 0 := by
    simpa using hνline_grad.sub_const (ν z)
  have hrderiv : HasDerivWithinAt r
      (A - ⟪gradientWithin ν X z, d⟫_ℝ) s 0 := by
    have hsum := hAderiv.add hquad
    have h := hsum.sub hνsub
    convert h using 1
    ring
  have hnonneg : 0 ≤ A - ⟪gradientWithin ν X z, d⟫_ℝ :=
    right_derivative_nonneg_of_min_on_Icc_for_bregman (φ := r) hrderiv hmin
  dsimp [A, q, d] at hnonneg
  linarith

/-- A gauge-strong convex differentiable potential lower-bounds the carrier
Bregman divergence by one half of the squared gauge distance.

This is the block-coordinate carrier form of the standard Bregman lower bound:
the potential lives on an ambient carrier `X`, the divergence is the named
carrier Bregman object using `gradientWithin`, and the quadratic term uses the
supplied seminorm/gauge rather than the ambient Hilbert norm.

Layer: Model | Gap: Level 1 (carrier seminorm Bregman lower bound)
Proof: specialize the staged seminorm Bregman lower bound to the segment between
  the two feasible endpoints, then rewrite the carrier Bregman divergence to
  the ambient within-gradient formula using endpoint realization.
Source: Mathlib convex analysis, seminorms, within-gradients, and SOptLib
  carrier Bregman divergence APIs
Used in: stochastic block mirror descent block distance-generator lower bound
  and mirror-prox coercivity on nonambient block norms
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem blockBregmanDivergence_lower_bound_of_strongConvexOnWithNorm
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {ν : E → ℝ} {p : Seminorm ℝ E}
    {v : {x : E // x ∈ X} → ℝ}
    (hv_eq : ∀ y : {x : E // x ∈ X}, v y = ν y.1)
    (hX : Convex ℝ X) (hνdiff : ContDiffOn ℝ 1 ν X)
    (hstrong : StrongConvexOnWithGauge X 1 p ν)
    (z x : {x : E // x ∈ X}) :
    (1 / 2 : ℝ) * p (x.1 - z.1) ^ 2 ≤
      SOptLib.carrierBregmanDivergence v
        (fun y : {x : E // x ∈ X} => gradientWithin ν X y.1) z x := by
  have hcore :
      (1 / 2 : ℝ) * p (x.1 - z.1) ^ 2 ≤
        ν x.1 - (ν z.1 + ⟪gradientWithin ν X z.1, x.1 - z.1⟫_ℝ) := by
    exact bregman_lower_bound_of_strongConvexOnWithSeminorm_differentiableWithinAt
      (X := X) (ν := ν) (p := p) (z := z.1) (x := x.1)
      hX (hνdiff.differentiableOn_one z.1 z.2)
      (by
        intro y hy w hw a b ha hb hab
        simpa [StrongConvexOnWithGauge] using
          hstrong (x := y) hy (y := w) hw (a := a) (b := b) ha hb hab)
      z.2 x.2
  change (1 / 2 : ℝ) * p (x.1 - z.1) ^ 2 ≤
    carrierBregmanDivergence v
      (fun y : {x : E // x ∈ X} => gradientWithin ν X y.1) z x
  rw [blockBregmanDivergence_eq_gradientWithin_formula
    (X := X) (v := v) (ν := ν) z x hv_eq]
  exact hcore

/-- A divergence lower-bounded by one half of a squared gauge is nonnegative.

This packages the standard final step in Bregman coercivity arguments: once a
block or carrier Bregman divergence dominates `1 / 2 * p z x ^ 2`, the
right-hand divergence is nonnegative because the half-squared gauge term is
nonnegative.

Layer: Model | Gap: Level 0 (Bregman nonnegativity from lower bound)
Proof: prove nonnegativity of the half-squared gauge term by ordered-ring
  positivity of squares, then compose with the supplied lower bound.
Source: Mathlib ordered real arithmetic and Bregman lower-bound coercivity
  arguments from convex optimization
Used in: stochastic block mirror descent block Bregman nonnegativity after the
  distance-generator lower-bound step
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem blockBregmanDivergence_nonneg_of_lower_bound
    {P : Type*} (V p : P → P → ℝ) (z x : P)
    (hlower : (1 / 2 : ℝ) * p z x ^ 2 ≤ V z x) :
    0 ≤ V z x := by
  have hleft : 0 ≤ (1 / 2 : ℝ) * p z x ^ 2 := by
    exact mul_nonneg (by norm_num) (sq_nonneg _)
  exact le_trans hleft hlower

/-- A distance-generating function on a feasible set with a selected ambient gradient.

The predicate records the usual C1 selected-gradient data together with the
one-strong Bregman lower bound used to control squared distances in mirror and
accelerated proximal arguments.

Layer: Model | Concept: Bregman
Proof: (definitional construction; conjunction of continuous selected gradient,
  pointwise gradient realization, and one-strong Bregman lower bound)
Source: Convex optimization distance-generating functions and Mathlib
  inner-product gradient APIs
Used in: stochastic accelerated gradient descent prox recursion and stochastic
  mirror-descent Bregman geometry assumptions
Book citation: book/FOML/StochasticAcceleratedGradientDescent.json#/assumptions/3
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic accelerated gradient descent -/
def IsDistanceGeneratingFunctionOn
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (X : Set E) (nu : E → ℝ) (grad : E → E) : Prop :=
  ContinuousOn grad X ∧
  (∀ x, x ∈ X → HasGradientAt nu (grad x) x) ∧
  (∀ x, x ∈ X → ∀ z, z ∈ X →
    (1 / 2 : ℝ) * ‖x - z‖ ^ 2 ≤ carrierBregmanFormula nu id grad x z)

/-- A distance-generating function makes its realized Bregman kernel dominate
one half of the squared ambient distance.

The statement is phrased for a named kernel `V`, provided only that the
particular value `V x z` realizes the carrier Bregman formula associated with
the selected gradient in the distance-generating-function predicate.

Layer: Model | Gap: Level 0 (distance-generating Bregman coercivity projection)
Proof: project the lower-bound field from `IsDistanceGeneratingFunctionOn` and
  rewrite the requested named kernel through its pointwise Bregman realization.
Source: Convex optimization distance-generating functions and Mathlib
  inner-product norm APIs
Used in: stochastic accelerated gradient descent prox recursion squared-distance
  absorption and mirror-descent Bregman coercivity
Book citation: book/FOML/StochasticAcceleratedGradientDescent.json#/assumptions/3
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic accelerated gradient descent -/
theorem IsDistanceGeneratingFunctionOn.half_sq_norm_le_bregman
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    {X : Set E} {nu : E → ℝ} {grad : E → E} {V : E → E → ℝ}
    (hdgf : IsDistanceGeneratingFunctionOn X nu grad)
    (x : E) (hx : x ∈ X) (z : E) (hz : z ∈ X)
    (hV : V x z = carrierBregmanFormula nu id grad x z) :
    (1 / 2 : ℝ) * ‖x - z‖ ^ 2 ≤ V x z := by
  simpa [hV] using hdgf.2.2 x hx z hz

/-- Along an ambient segment, the Bregman difference has the expected right
derivative at the segment base point.

For a potential with a prescribed gradient at `xp`, the derivative at `0` of
`t ↦ D_v(x, lineMap xp u t) - D_v(x, xp)` is the gradient difference
`grad xp - grad x` paired with the segment direction `u - xp`.

Layer: Model | Gap: Level 1 (ambient Bregman segment derivative)
Proof: compose the pointwise gradient derivative with the affine segment, expand
  `carrierBregmanFormula`, and normalize the inner-product algebra.
Source: Mathlib `HasGradientAt` chain rule, affine line-map derivatives, and
  real inner-product algebra
Used in: stochastic accelerated and mirror-descent prox-step Bregman derivative
Book citation: book/FOML/StochasticAcceleratedGradientDescent.json#/algorithm_spec/steps
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  stochastic accelerated gradient descent -/
theorem bregman_segment_difference_hasDerivWithinAt_zero
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (v : E → ℝ) (grad : E → E) {x xp u : E}
    (hgrad_xp : HasGradientAt v (grad xp) xp) :
    let d : E := u - xp
    let β : ℝ → ℝ := fun t =>
      if _ht : t ∈ Set.Icc (0 : ℝ) 1 then
        carrierBregmanFormula v id grad x (AffineMap.lineMap xp u t) -
          carrierBregmanFormula v id grad x xp
      else 0
    HasDerivWithinAt β
      ⟪grad xp - grad x, d⟫_ℝ
      (Set.Icc (0 : ℝ) 1) 0 := by
  classical
  let d : E := u - xp
  let s : Set ℝ := Set.Icc (0 : ℝ) 1
  let line : ℝ → E := fun t => AffineMap.lineMap xp u t
  let β : ℝ → ℝ := fun t =>
    if _ht : t ∈ Set.Icc (0 : ℝ) 1 then
      carrierBregmanFormula v id grad x (AffineMap.lineMap xp u t) -
        carrierBregmanFormula v id grad x xp
    else 0
  have hline_deriv : HasDerivWithinAt line d s 0 := by
    simpa [line, d] using
      (AffineMap.hasDerivWithinAt_lineMap (a := xp) (b := u)
        (s := s) (x := (0 : ℝ)))
  have hvseg : HasDerivWithinAt (fun t => v (line t))
      ⟪grad xp, d⟫_ℝ s 0 := by
    have hcomp :=
      hgrad_xp.hasFDerivAt.comp_hasDerivWithinAt_of_eq
        (x := (0 : ℝ)) hline_deriv (by simp [line])
    simpa [Function.comp_def, line, d, InnerProductSpace.toDual_apply_apply] using hcomp
  have hlin : HasDerivWithinAt (fun t : ℝ => t * ⟪grad x, d⟫_ℝ)
      ⟪grad x, d⟫_ℝ s 0 := by
    simpa using (hasDerivWithinAt_id (x := (0 : ℝ)) (s := s)).mul_const
      ⟪grad x, d⟫_ℝ
  have hderiv_expr : HasDerivWithinAt
      (fun t : ℝ => (v (line t) - v xp) - t * ⟪grad x, d⟫_ℝ)
      (⟪grad xp, d⟫_ℝ - ⟪grad x, d⟫_ℝ) s 0 := by
    exact (hvseg.sub_const (v xp)).sub hlin
  have heq : ∀ t ∈ s, β t =
      (fun t : ℝ => (v (line t) - v xp) - t * ⟪grad x, d⟫_ℝ) t := by
    intro t ht
    have htI : t ∈ Set.Icc (0 : ℝ) 1 := by simpa [s] using ht
    have hseg_sub : AffineMap.lineMap xp u t - xp = t • d := by
      simp [d, AffineMap.lineMap_apply_module']
    have hinner_diff :
        ⟪grad x, AffineMap.lineMap xp u t - x⟫_ℝ -
            ⟪grad x, xp - x⟫_ℝ =
          t * ⟪grad x, d⟫_ℝ := by
      calc
        ⟪grad x, AffineMap.lineMap xp u t - x⟫_ℝ -
            ⟪grad x, xp - x⟫_ℝ =
            ⟪grad x, (AffineMap.lineMap xp u t - x) - (xp - x)⟫_ℝ := by
          rw [← inner_sub_right]
        _ = ⟪grad x, AffineMap.lineMap xp u t - xp⟫_ℝ := by
          congr 1
          abel
        _ = ⟪grad x, t • d⟫_ℝ := by
          rw [hseg_sub]
        _ = t * ⟪grad x, d⟫_ℝ := by
          simp [inner_smul_right]
    calc
      β t =
          carrierBregmanFormula v id grad x (AffineMap.lineMap xp u t) -
            carrierBregmanFormula v id grad x xp := by
        simp only [β]
        rw [dif_pos htI]
      _ = (v (line t) - v xp) - t * ⟪grad x, d⟫_ℝ := by
        unfold carrierBregmanFormula
        rw [← hinner_diff]
        simp [line]
        ring
  have hβ : HasDerivWithinAt β
      (⟪grad xp, d⟫_ℝ - ⟪grad x, d⟫_ℝ) s 0 := by
    exact hderiv_expr.congr heq (heq 0 (by norm_num [s]))
  have hval : ⟪grad xp, d⟫_ℝ - ⟪grad x, d⟫_ℝ =
      ⟪grad xp - grad x, d⟫_ℝ := by
    rw [inner_sub_left]
  simpa [d, s, β, hval] using hβ

/-- A one-sided half-squared-distance lower bound gives squared-distance control.

If a two-point potential `V` lower-bounds one half of the squared seminorm
distance at `(x,z)`, then twice `V x z` controls the full squared distance.

Layer: Model | Gap: Level 0 (one-sided Bregman-radius normalization)
Proof: rearrange the pointwise real inequality `(1 / 2) * ‖x - z‖ ^ 2 ≤ V x z`
  by linear arithmetic over ordered rings.
Source: Mathlib seminormed additive groups and ordered real arithmetic APIs
Used in: accelerated stochastic approximation conversion from DGF Bregman
  control to squared-distance control for L2 radius estimates
Book citation: book/FOML/StochasticAcceleratedGradientDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  accelerated stochastic approximation -/
theorem sq_norm_le_two_mul_of_half_sq_norm_le
    {E : Type*} [SeminormedAddCommGroup E]
    (V : E → E → ℝ) (eval : E → E) (x z : E)
    (h : (1 / 2 : ℝ) * ‖eval x - eval z‖ ^ 2 ≤ V x z) :
    ‖eval x - eval z‖ ^ 2 ≤ 2 * V x z := by
  nlinarith
