import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Analysis.InnerProductSpace.Calculus
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.Topology.Order.Compact
import Mathlib.Tactic
import SOptLib.Glue.Analysis

open Topology
open scoped InnerProductSpace

namespace SOptLib

open Topology
open scoped InnerProductSpace


/-- Paper mirror-prox objective generated by an abstract Bregman-like divergence on a
candidate carrier and an ambient evaluation map.
Layer: Model | Concept: Prox
Proof: (definitional construction; mirror-prox objective combining linear term + Bregman regularizer)
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Eq. (3.2.5).
Used in: stochastic mirror descent compact prox selector
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
noncomputable def paperMirrorObjective
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (eval : P → E) (x : P) (g : E) (γ : ℝ) (y : P) : ℝ :=
  γ * ⟪g, eval y⟫_ℝ + V x y

/-- Expanded formula for the abstract paper mirror-prox objective.
Layer: Model | Gap: Level 0 (prox objective formula)
Proof: expand the staged objective definition.
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Eq. (3.2.5).
Used in: stochastic mirror descent objective formula bridge
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem paperMirrorObjective_def
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (eval : P → E) (x : P) (g : E) (γ : ℝ) (y : P) :
    paperMirrorObjective V eval x g γ y = γ * ⟪g, eval y⟫_ℝ + V x y := by
  rfl

/-- Literal mirror-prox objective with an interior base and separate candidate carrier.

Defines the prox objective `γ * ⟪g, eval y⟫_ℝ + Vlit x y` used when the
Bregman term is supplied literally on an interior/base point and a candidate.

Layer: Model | Concept: Prox
Proof: (definitional construction; literal mirror-prox objective as a weighted
  linear inner-product term plus the supplied Bregman divergence term)
Source: Mathlib inner product space notation and real scalar algebra APIs
Used in: stochastic mirror descent prox-step literal objective expansion for
  interior-base mirror updates
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def literalMirrorObjective
    {E Xint P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (Vlit : Xint → P → ℝ) (eval : P → E) (x : Xint) (g : E) (γ : ℝ) (y : P) : ℝ :=
  γ * ⟪g, eval y⟫_ℝ + Vlit x y

/-- Expanded formula for the literal interior-base mirror-prox objective.

The literal mirror objective at candidate `y` is exactly the linearized loss term
`γ * ⟪g, eval y⟫_ℝ` plus the supplied literal divergence from the base point `x`.

Layer: Model | Gap: Level 0 (literal mirror objective expansion)
Proof: by rfl after unfolding literalMirrorObjective.
Source: Mathlib inner product space notation and real algebra APIs
Used in: stochastic mirror descent prox-step objective normalization
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem literalMirrorObjective_def
    {E Xint P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (Vlit : Xint → P → ℝ) (eval : P → E) (x : Xint) (g : E) (γ : ℝ) (y : P) :
    literalMirrorObjective Vlit eval x g γ y = γ * ⟪g, eval y⟫_ℝ + Vlit x y := by
  rfl

/-- The literal interior-base mirror objective is the carrier paper mirror objective after
pulling the divergence back along the base-point map.

Layer: Model | Gap: Level 0 (literal prox objective bridge)
Proof: unfold both objective definitions and rewrite the divergence term with the
  point-map compatibility hypothesis.
Source: Mathlib simplification and rewriting APIs for real inner-product expressions
Used in: stochastic mirror descent bridge from literal prox objectives to carrier paper objectives
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine
  Learning, stochastic mirror descent -/
theorem literalMirrorObjective_eq_paperMirrorObjective
    {E Xint P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (Vlit : Xint → P → ℝ) (toPoint : Xint → P) (eval : P → E)
    (hV : ∀ x y, V (toPoint x) y = Vlit x y)
    (x : Xint) (g : E) (γ : ℝ) (y : P) :
    literalMirrorObjective Vlit eval x g γ y =
      paperMirrorObjective V eval (toPoint x) g γ y := by
  rw [literalMirrorObjective_def, paperMirrorObjective_def, hV x y]

/-- Continuity of the abstract paper mirror-prox objective in the candidate point.
Layer: Model | Gap: Level 1 (prox objective continuity)
Proof: compose the continuous linear oracle term with the continuous divergence section.
Source: Mathlib continuity API for inner-product spaces.
Used in: stochastic mirror descent compact prox selector
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem paperMirrorObjective_continuous
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [TopologicalSpace P]
    {V : P → P → ℝ} {eval : P → E}
    (hV : Continuous (fun p : P × P => V p.1 p.2))
    (heval : Continuous eval) (x : P) (g : E) (γ : ℝ) :
    Continuous (paperMirrorObjective V eval x g γ) := by
  have hinner : Continuous (fun y : P => ⟪g, eval y⟫_ℝ) :=
    continuous_const.inner heval
  have hlin : Continuous (fun y : P => γ * ⟪g, eval y⟫_ℝ) :=
    continuous_const.mul hinner
  have hsection : Continuous (fun y : P => V x y) :=
    hV.comp (continuous_const.prodMk continuous_id)
  simpa [paperMirrorObjective] using hlin.add hsection

/-- Abstract argmin predicate for the paper mirror-prox step.
Layer: Model | Concept: Prox
Proof: (definitional construction; predicate asserting a point realises a mirror-step argmin)
Source: Lan, First-order and Stochastic Optimization Methods for Machine Learning,
  Eq. (3.2.5).
Used in: stochastic mirror descent compact prox selector
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
def IsMirrorStep
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (eval : P → E) (x : P) (g : E) (γ : ℝ) (z : P) : Prop :=
  IsMinOn (paperMirrorObjective V eval x g γ) Set.univ z

/-- Expanded form of the abstract paper mirror-step argmin predicate.
Layer: Model | Gap: Level 0 (prox argmin predicate)
Proof: rewrite `IsMinOn` over `Set.univ`.
Source: Mathlib order/topology argmin predicates.
Used in: stochastic mirror descent compact prox selector
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem isMirrorStep_iff
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (eval : P → E) (x : P) (g : E) (γ : ℝ) (z : P) :
    IsMirrorStep V eval x g γ z ↔
      ∀ y : P, paperMirrorObjective V eval x g γ z ≤
        paperMirrorObjective V eval x g γ y := by
  rw [IsMirrorStep, isMinOn_univ_iff]

/-- Compactness/continuity existence route for an abstract paper mirror-prox argmin.
Layer: Model | Gap: Level 1 (compact prox argmin existence)
Proof: apply Mathlib's compact extreme-value theorem to the continuous staged objective.
Source: Mathlib `IsCompact.exists_isMinOn`.
Used in: stochastic mirror descent compact prox selector
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem mirrorStep_exists_compact
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [TopologicalSpace P]
    {V : P → P → ℝ} {eval : P → E}
    (hcompact : IsCompact (Set.univ : Set P))
    (hV : Continuous (fun p : P × P => V p.1 p.2))
    (heval : Continuous eval) (x : P) (g : E) (γ : ℝ) :
    ∃ z : P, IsMirrorStep V eval x g γ z := by
  rcases hcompact.exists_isMinOn
      (⟨x, trivial⟩ : (Set.univ : Set P).Nonempty)
      (paperMirrorObjective_continuous hV heval x g γ).continuousOn with
    ⟨z, _hz, hzmin⟩
  exact ⟨z, hzmin⟩

/-- Canonical compact argmin object for the abstract paper mirror-prox objective.
Layer: Model | Concept: Prox
Proof: (definitional construction; argmin selector for the mirror-prox objective)
Source: Mathlib compact extreme-value theorem.
Used in: stochastic mirror descent compact prox selector
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
noncomputable def proxStepArgmin
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [TopologicalSpace P]
    {V : P → P → ℝ} {eval : P → E}
    (hcompact : IsCompact (Set.univ : Set P))
    (hV : Continuous (fun p : P × P => V p.1 p.2))
    (heval : Continuous eval) (x : P) (g : E) (γ : ℝ) :
    {z : P // IsMirrorStep V eval x g γ z} :=
  let h := mirrorStep_exists_compact hcompact hV heval x g γ
  ⟨Classical.choose h, Classical.choose_spec h⟩

/-- Canonical compact argmin selector for the abstract paper mirror-prox objective.
Layer: Model | Concept: Prox
Proof: (definitional construction; canonical mirror-prox update operator)
Source: Mathlib compact extreme-value theorem.
Used in: stochastic mirror descent compact prox selector
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
noncomputable def proxStep
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [TopologicalSpace P]
    {V : P → P → ℝ} {eval : P → E}
    (hcompact : IsCompact (Set.univ : Set P))
    (hV : Continuous (fun p : P × P => V p.1 p.2))
    (heval : Continuous eval) (x : P) (g : E) (γ : ℝ) : P :=
  (proxStepArgmin hcompact hV heval x g γ).1

/-- The canonical compact argmin selector satisfies the abstract paper mirror-step
predicate.
Layer: Model | Gap: Level 0 (prox selector specification)
Proof: project the proof component from the chosen argmin subtype.
Source: Mathlib compact extreme-value theorem.
Used in: stochastic mirror descent compact prox selector
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem proxStep_isMirrorStep
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [TopologicalSpace P]
    {V : P → P → ℝ} {eval : P → E}
    (hcompact : IsCompact (Set.univ : Set P))
    (hV : Continuous (fun p : P × P => V p.1 p.2))
    (heval : Continuous eval) (x : P) (g : E) (γ : ℝ) :
    IsMirrorStep V eval x g γ (proxStep hcompact hV heval x g γ) := by
  exact (proxStepArgmin hcompact hV heval x g γ).2

/-- The canonical compact argmin selector minimizes the abstract paper mirror-prox
objective.
Layer: Model | Gap: Level 0 (prox selector minimizes)
Proof: expand the argmin predicate supplied by the selector specification.
Source: Mathlib compact extreme-value theorem.
Used in: stochastic mirror descent compact prox selector
Book citation: `book/FOML/StochasticMirrorDescent.json#/algorithm_spec/steps/0/math`
Origin algorithm: FOML stochastic mirror descent -/
theorem proxStep_minimizes
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [TopologicalSpace P]
    {V : P → P → ℝ} {eval : P → E}
    (hcompact : IsCompact (Set.univ : Set P))
    (hV : Continuous (fun p : P × P => V p.1 p.2))
    (heval : Continuous eval) (x : P) (g : E) (γ : ℝ) (y : P) :
    paperMirrorObjective V eval x g γ (proxStep hcompact hV heval x g γ) ≤
      paperMirrorObjective V eval x g γ y := by
  exact (isMirrorStep_iff V eval x g γ
    (proxStep hcompact hV heval x g γ)).1
      (proxStep_isMirrorStep hcompact hV heval x g γ) y

/-- Joint continuity of the paper mirror-prox objective in the base point, oracle
vector, step size, and candidate point.

The objective `(x,g,γ,y) ↦ γ * ⟪g, eval y⟫ + V x y` is continuous whenever
the Bregman term is jointly continuous and the model evaluation map is
continuous.

Layer: Model | Gap: Level 1 (mirror-prox objective joint continuity)
Proof: compose product projections with the continuous evaluation and Bregman
  maps, then combine Mathlib continuity rules for inner products,
  multiplication, and addition.
Source: Mathlib topology of product spaces and continuous inner-product APIs
Used in: stochastic mirror descent prox-step objective continuity
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
theorem paperMirrorObjective_joint_continuous
    {P E : Type*} [TopologicalSpace P] [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {V : P → P → ℝ} {eval : P → E}
    (hV : Continuous (fun p : P × P => V p.1 p.2))
    (heval : Continuous eval) :
    Continuous (fun q : (P × E × ℝ) × P =>
      SOptLib.paperMirrorObjective V eval q.1.1 q.1.2.1 q.1.2.2 q.2) := by
  have hg : Continuous (fun q : (P × E × ℝ) × P => q.1.2.1) :=
    continuous_fst.comp (continuous_snd.comp continuous_fst)
  have hγ : Continuous (fun q : (P × E × ℝ) × P => q.1.2.2) :=
    continuous_snd.comp (continuous_snd.comp continuous_fst)
  have hy : Continuous (fun q : (P × E × ℝ) × P => eval q.2) :=
    heval.comp continuous_snd
  have hinner : Continuous (fun q : (P × E × ℝ) × P =>
      ⟪q.1.2.1, eval q.2⟫_ℝ) :=
    hg.inner hy
  have hlin : Continuous (fun q : (P × E × ℝ) × P =>
      q.1.2.2 * ⟪q.1.2.1, eval q.2⟫_ℝ) :=
    hγ.mul hinner
  have hx : Continuous (fun q : (P × E × ℝ) × P => q.1.1) :=
    continuous_fst.comp continuous_fst
  have hz : Continuous (fun q : (P × E × ℝ) × P => q.2) :=
    continuous_snd
  have hVcomp : Continuous (fun q : (P × E × ℝ) × P => V q.1.1 q.2) :=
    hV.comp (hx.prodMk hz)
  simpa [SOptLib.paperMirrorObjective] using hlin.add hVcomp

/-- A strongly convex mirror objective has at most one mirror-prox minimizer.

If two candidates minimize the same mirror objective and both satisfy the mirror
variational inequality, the symmetric Bregman identity makes the summed
first-order inequalities bound the symmetric Bregman gap by zero. The strict
lower bound then forces zero evaluation distance, and injectivity of `eval`
identifies the minimizers.

Layer: Model | Gap: Level 1 (unique argmin for strongly convex mirror objective)
Proof: add the two variational inequalities, rewrite their sum with the
  symmetric Bregman identity, use the norm-square lower bound to force
  `‖eval z - eval z'‖ = 0`, then apply injectivity of `eval`.
Source: Mathlib inner product space algebra and real norm/order APIs
Used in: stochastic mirror descent prox-step unique argmin for the mirror objective
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem paperMirrorObjective_argmin_unique_of_strict_bregman
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {V : P → P → ℝ} {eval grad : P → E} {obj : P → ℝ}
    (heval_inj : Function.Injective eval)
    (x : P) (g : E) (γ : ℝ) (z z' : P)
    (hvariational : ∀ {a b : P}, (∀ y : P, obj a ≤ obj y) →
      0 ≤ ⟪γ • g + grad a - grad x, eval b - eval a⟫_ℝ)
    (hsymm : ∀ a b : P,
      V a b + V b a = ⟪grad b - grad a, eval b - eval a⟫_ℝ)
    (hlower : ∀ a b : P, ‖eval a - eval b‖ ^ 2 ≤ V a b + V b a)
    (hzmin : ∀ y : P, obj z ≤ obj y)
    (hz'min : ∀ y : P, obj z' ≤ obj y) :
    z = z' := by
  have hzvar : 0 ≤ ⟪γ • g + grad z - grad x, eval z' - eval z⟫_ℝ :=
    hvariational hzmin
  have hz'var : 0 ≤ ⟪γ • g + grad z' - grad x, eval z - eval z'⟫_ℝ :=
    hvariational hz'min
  have hsum_nonneg := add_nonneg hzvar hz'var
  have hsum_eq :
      ⟪γ • g + grad z - grad x, eval z' - eval z⟫_ℝ +
        ⟪γ • g + grad z' - grad x, eval z - eval z'⟫_ℝ =
          -(V z z' + V z' z) := by
    rw [hsymm z z']
    have hrev : eval z - eval z' = -(eval z' - eval z) := by
      abel
    rw [hrev, inner_neg_right]
    simp [inner_add_left, inner_sub_left, inner_smul_left]
  have hsym_nonpos : V z z' + V z' z ≤ 0 := by
    linarith
  have hnormsq_le_zero : ‖eval z - eval z'‖ ^ 2 ≤ 0 :=
    le_trans (hlower z z') hsym_nonpos
  have hnorm_zero : ‖eval z - eval z'‖ = 0 := by
    have hsquare : ‖eval z - eval z'‖ ^ 2 = 0 :=
      le_antisymm hnormsq_le_zero (sq_nonneg ‖eval z - eval z'‖)
    exact sq_eq_zero_iff.mp hsquare
  apply heval_inj
  have hsub : eval z - eval z' = 0 := norm_eq_zero.mp hnorm_zero
  exact sub_eq_zero.mp hsub

/-- A chosen compact mirror-prox step satisfies the expanded objective inequality.

For the canonical compact mirror-prox selector, the selected prox point minimizes the
literal objective `γ * ⟪g, eval ·⟫_ℝ + V x ·` against every candidate `y`.

Layer: Model | Gap: Level 0 (expanded prox-step minimization inequality)
Proof: unfolds `paperMirrorObjective` and reuses `proxStep_minimizes` by `simpa`.
Source: Mathlib compactness and continuous real-valued optimization APIs
Used in: stochastic mirror descent prox-step optimality in expanded source form
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem proxStep_minimizes_expanded
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [TopologicalSpace P]
    {V : P → P → ℝ} {eval : P → E}
    (hcompact : IsCompact (Set.univ : Set P))
    (hV : Continuous (fun p : P × P => V p.1 p.2))
    (heval : Continuous eval) (x : P) (g : E) (γ : ℝ) (y : P) :
    γ * ⟪g, eval (proxStep (V := V) (eval := eval) hcompact hV heval x g γ)⟫_ℝ +
        V x (proxStep (V := V) (eval := eval) hcompact hV heval x g γ) ≤
      γ * ⟪g, eval y⟫_ℝ + V x y := by
  simpa [SOptLib.paperMirrorObjective] using
    (proxStep_minimizes (V := V) (eval := eval) hcompact hV heval x g γ y)

end SOptLib

namespace SOptLib

/-- A bundled positive-stepsize composite prox selector supplies an existing prox point.

For any abstract candidate type, if each current point, oracle vector, and
positive stepsize has a selected minimizer of the composite prox objective, then
the corresponding `IsCompositeProxPoint` existence statement follows.

Layer: Model | Gap: Level 0 (composite prox selector existence bridge)
Proof: choose the point component supplied by the selector at `(x, g, γ)` and
  use its stored `IsMinOn` certificate after unfolding the composite objective
  predicate.
Source: Mathlib subtype projections and order argmin predicates for real-valued
  objective minimization
Used in: nonconvex stochastic mirror descent prox-step existence from the
  paper argmin update selector
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic mirror descent -/
theorem compositeProxPoint_exists_of_selector
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (h : P → ℝ) (eval : P → E)
    (proxMap :
      ∀ p : P × E × {γ : ℝ // 0 < γ},
        {z : P //
          IsMinOn
            (fun u : P => ⟪p.2.1, eval u⟫_ℝ + p.2.2.1⁻¹ * V p.1 u + h u)
            Set.univ z})
    (x : P) (g : E) {γ : ℝ} (hγ : 0 < γ) :
    ∃ xplus : P,
      IsMinOn
        (fun u : P => ⟪g, eval u⟫_ℝ + γ⁻¹ * V x u + h u)
        Set.univ xplus := by
  let p : P × E × {γ : ℝ // 0 < γ} := (x, g, ⟨γ, hγ⟩)
  refine ⟨(proxMap p).1, ?_⟩
  simpa [p] using (proxMap p).2

/-- A selected positive-stepsize composite prox point satisfies the paper prox predicate
whenever the local and paper argmin predicates are pointwise equivalent.

This abstracts the common bridge where an algorithm-local prox predicate is
proved for a selected update, while the paper-facing statement uses a
definitionally equal argmin predicate with different notation.

Layer: Model | Gap: Level 0 (selected prox predicate transport)
Proof: specialize the local selected-point certificate and transport it across
  the pointwise iff between local and paper argmin predicates.
Source: Mathlib propositional equivalence and dependent function specialization APIs
Used in: nonconvex stochastic mirror descent prox-step selected argmin
  certificate normalized to the paper prox predicate
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic mirror descent -/
theorem compositeProxPoint_isPaperProxPoint
    {E P : Type*}
    (selector : P → E → ∀ γ : ℝ, 0 < γ → P)
    (localPred paperPred : P → E → ℝ → P → Prop)
    (hlocal : ∀ (x : P) (g : E) (γ : ℝ) (hγ : 0 < γ),
      localPred x g γ (selector x g γ hγ))
    (hiff : ∀ (x : P) (g : E) (γ : ℝ) (z : P),
      localPred x g γ z ↔ paperPred x g γ z)
    (x : P) (g : E) (γ : ℝ) (hγ : 0 < γ) :
    paperPred x g γ (selector x g γ hγ) := by
  exact (hiff x g γ (selector x g γ hγ)).1 (hlocal x g γ hγ)

/-- A selected composite prox point satisfies the composite prox argmin predicate.

For an abstract candidate type, a bundled positive-stepsize prox selector
returns a point together with its `IsMinOn` certificate; the point projection is
therefore a composite prox point for the corresponding objective.

Layer: Model | Gap: Level 0 (composite prox selector specification bridge)
Proof: unfold the selected prox point, composite prox predicate, and composite
  prox objective, then project the stored `IsMinOn` certificate from the
  bundled selector.
Source: Mathlib subtype projections and order argmin predicates for real-valued
  objective minimization
Used in: nonconvex stochastic mirror descent prox-step selected argmin
  certificate from the paper update selector
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic mirror descent -/
theorem compositeProxPoint_isProxPoint
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (h : P → ℝ) (eval : P → E)
    (proxMap :
      ∀ p : P × E × {γ : ℝ // 0 < γ},
        {z : P //
          IsMinOn
            (fun u : P => ⟪p.2.1, eval u⟫_ℝ + p.2.2.1⁻¹ * V p.1 u + h u)
            Set.univ z})
    (x : P) (g : E) (γ : ℝ) (hγ : 0 < γ) :
    IsMinOn
      (fun u : P => ⟪g, eval u⟫_ℝ + γ⁻¹ * V x u + h u)
      Set.univ ((proxMap (x, g, ⟨γ, hγ⟩)).1) := by
  let p : P × E × {γ : ℝ // 0 < γ} := (x, g, ⟨γ, hγ⟩)
  simpa [p] using (proxMap p).2

/-- Exact projected-gradient mapping evaluated at a run-selected output point.

This is the abstract model wrapper for quantities of the form `g_X(\bar x_s)`:
first choose the run output at `s` and sample point `ω`, then evaluate the exact
projected-gradient map at that output using the selected run stepsize.

Layer: Model | Concept: Iterates
Proof: (definitional construction; run-output evaluation followed by exact projected-gradient evaluation at the selected positive stepsize)
Source: Mathlib dependent function application over real positive step-size proofs and normed-space stationarity notation
Used in: nonconvex stochastic mirror descent exact stationarity at randomized run output
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/output/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
noncomputable def runExactProjectedGradient
    {Run Ω X E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (runOutput : Run → Ω → X)
    (exactProjectedGradient : X → (gamma : ℝ) → 0 < gamma → E)
    (stepsize : Run → ℝ)
    (hstepsize : ∀ s : Run, 0 < stepsize s)
    (s : Run) (ω : Ω) : E :=
  exactProjectedGradient (runOutput s ω) (stepsize s) (hstepsize s)

/-- The run exact projected-gradient wrapper unfolds to exact projected-gradient
evaluation at the selected run output and selected stepsize.

Layer: Model | Gap: Level 0 (run exact projected-gradient unfolding)
Proof: by rfl after unfolding `runExactProjectedGradient`.
Source: Mathlib dependent function application over real positive step-size proofs and normed-space stationarity notation
Used in: nonconvex stochastic mirror descent exact stationarity at randomized run output
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/output/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
@[simp]
theorem runExactProjectedGradient_apply
    {Run Ω X E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (runOutput : Run → Ω → X)
    (exactProjectedGradient : X → (gamma : ℝ) → 0 < gamma → E)
    (stepsize : Run → ℝ)
    (hstepsize : ∀ s : Run, 0 < stepsize s)
    (s : Run) (ω : Ω) :
    runExactProjectedGradient runOutput exactProjectedGradient stepsize hstepsize s ω =
      exactProjectedGradient (runOutput s ω) (stepsize s) (hstepsize s) := by
  rfl

/-- Empirical projected gradient evaluated at a run-selected output point.

This is the abstract model wrapper for quantities of the form
`\bar g_X(\bar x_s)`: first choose the run output at `s` and sample point `ω`,
then evaluate the empirical projected-gradient map at that output.

Layer: Model | Concept: Iterates
Proof: (definitional construction; run-output evaluation followed by empirical projected-gradient evaluation)
Source: Mathlib normed vector space function application APIs and Lan empirical stationarity notation
Used in: nonconvex stochastic mirror descent selected-run empirical stationarity comparison
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/output/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
noncomputable def runEmpiricalProjectedGradient
    {Run Ω X E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (runOutput : Run → Ω → X)
    (empiricalProjectedGradient : Run → X → Ω → E)
    (s : Run) (ω : Ω) : E :=
  empiricalProjectedGradient s (runOutput s ω) ω

/-- The run empirical projected-gradient wrapper unfolds to empirical evaluation at
the selected run output.

Layer: Model | Gap: Level 0 (run empirical projected-gradient unfolding)
Proof: by rfl after unfolding `runEmpiricalProjectedGradient`.
Source: Mathlib normed vector space function application APIs and Lan empirical stationarity notation
Used in: nonconvex stochastic mirror descent selected-run empirical stationarity comparison
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/output/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
@[simp]
theorem runEmpiricalProjectedGradient_apply
    {Run Ω X E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (runOutput : Run → Ω → X)
    (empiricalProjectedGradient : Run → X → Ω → E)
    (s : Run) (ω : Ω) :
    runEmpiricalProjectedGradient runOutput empiricalProjectedGradient s ω =
      empiricalProjectedGradient s (runOutput s ω) ω := by
  rfl

/-- Exact projected gradient at the run selected by a sample-dependent selector.

This abstracts the post-optimization stationarity quantity `g_X(\bar x_*)`:
the exact projected-gradient process is evaluated at the run index chosen from
the same sample point.

Layer: Model | Concept: Iterates
Proof: (definitional construction; compose the run-wise exact projected-gradient process with the selected-run map)
Source: Mathlib dependent function application and normed-space stationarity notation
Used in: nonconvex stochastic mirror descent selected exact stationarity after empirical run selection
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/output/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
noncomputable def selectedExactProjectedGradient
    {Run Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (runExactPG : Run → Ω → E) (selectedRun : Ω → Run) (ω : Ω) : E :=
  runExactPG (selectedRun ω) ω

/-- The selected exact projected-gradient wrapper unfolds to the run-wise exact
projected gradient at the selected run and the same sample point.

Layer: Model | Gap: Level 0 (selected exact projected-gradient unfolding)
Proof: by rfl after unfolding `selectedExactProjectedGradient`.
Source: Mathlib dependent function application and normed-space stationarity notation
Used in: nonconvex stochastic mirror descent selected exact stationarity after empirical run selection
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/output/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
@[simp]
theorem selectedExactProjectedGradient_apply
    {Run Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (runExactPG : Run → Ω → E) (selectedRun : Ω → Run) (ω : Ω) :
    selectedExactProjectedGradient runExactPG selectedRun ω =
      runExactPG (selectedRun ω) ω := by
  rfl

/-- Stochastic projected-gradient mapping from a time-indexed oracle average.

For an abstract state type `P`, oracle-value type `E`, and sample space `Ω`, this
names the stochastic projected-gradient vector obtained by evaluating a
projected-gradient mapping at the mini-batch oracle average and scheduled
stepsize.

Layer: Model | Concept: Prox
Proof: (definitional construction; projected-gradient map applied to a stochastic oracle average and positive scheduled stepsize)
Source: Lan projected-gradient stationarity notation and Mathlib dependent function application over real stepsizes
Used in: nonconvex stochastic mirror descent stochastic projected-gradient stationarity mapping at a mini-batch oracle value
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/optimization_phase/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
noncomputable def stochasticProjectedGradientMapping
    {Ω P E : Type*}
    (oracleAvg : ℕ → P → Ω → E)
    (gamma : ℕ → ℝ)
    (projectedGradient : (x : P) → E → (gamma : ℝ) → 0 < gamma → E)
    (hgamma : ∀ k : ℕ, 1 ≤ k → 0 < gamma k)
    (k : ℕ) (hk : 1 ≤ k) (x : P) (omega : Ω) : E :=
  projectedGradient x (oracleAvg k x omega) (gamma k) (hgamma k hk)

/-- The stochastic projected-gradient mapping unfolds to the projected-gradient
map at the current stochastic oracle average and scheduled stepsize.

Layer: Model | Gap: Level 0 (stochastic projected-gradient unfolding)
Proof: by rfl after unfolding stochasticProjectedGradientMapping.
Source: Lan projected-gradient stationarity notation and Mathlib dependent function application over real stepsizes
Used in: nonconvex stochastic mirror descent stochastic projected-gradient stationarity mapping at a mini-batch oracle value
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/optimization_phase/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
@[simp]
theorem stochasticProjectedGradientMapping_apply
    {Ω P E : Type*}
    (oracleAvg : ℕ → P → Ω → E)
    (gamma : ℕ → ℝ)
    (projectedGradient : (x : P) → E → (gamma : ℝ) → 0 < gamma → E)
    (hgamma : ∀ k : ℕ, 1 ≤ k → 0 < gamma k)
    (k : ℕ) (hk : 1 ≤ k) (x : P) (omega : Ω) :
    stochasticProjectedGradientMapping oracleAvg gamma projectedGradient hgamma k hk x omega =
      projectedGradient x (oracleAvg k x omega) (gamma k) (hgamma k hk) := by
  rfl

/-- Two prox points at the same positive stepsize are Lipschitz in state and oracle data.

The abstract hypotheses are exactly the two one-sided prox variational
inequalities for the selected points, plus strong monotonicity of the gradient
map after evaluation into the ambient Hilbert space.

Layer: Model | Gap: Level 1 (prox-step state-oracle stability)
Proof: add the two variational inequalities so the simple-term contributions
  cancel, use strong monotonicity for the prox-point displacement, and finish
  with Cauchy-Schwarz and division by the positive displacement norm.
Source: Mathlib real inner-product Cauchy-Schwarz and ordered-field algebra APIs
Used in: nonconvex stochastic mirror descent fixed-stepsize prox-step continuity
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, randomized stochastic mirror descent -/
theorem proxStep_state_oracle_distance_bound
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (prox : (x : P) → E → (γ : ℝ) → 0 < γ → P) (eval grad : P → E) (h : P → ℝ)
    (hvi :
      ∀ (x u : P) (g : E) (γ : ℝ) (hγ : 0 < γ),
        0 ≤
          ⟪g, eval u - eval (prox x g γ hγ)⟫_ℝ +
            γ⁻¹ * ⟪grad (prox x g γ hγ) - grad x,
              eval u - eval (prox x g γ hγ)⟫_ℝ +
            (h u - h (prox x g γ hγ)))
    (hstrong :
      ∀ y z : P,
        ‖eval y - eval z‖ ^ 2 ≤
          ⟪eval y - eval z, grad y - grad z⟫_ℝ)
    (x₁ x₂ : P) (g₁ g₂ : E) (γ : ℝ) (hγ : 0 < γ) :
    ‖eval (prox x₁ g₁ γ hγ) - eval (prox x₂ g₂ γ hγ)‖ ≤
      γ * ‖g₁ - g₂‖ + ‖grad x₁ - grad x₂‖ := by
  let xp₁ := prox x₁ g₁ γ hγ
  let xp₂ := prox x₂ g₂ γ hγ
  let δ : E := eval xp₁ - eval xp₂
  let C : ℝ := ⟪δ, grad xp₁ - grad xp₂⟫_ℝ
  let B : ℝ := ⟪grad x₁ - grad x₂, δ⟫_ℝ
  have hvi₁ := hvi x₁ xp₂ g₁ γ hγ
  have hvi₂ := hvi x₂ xp₁ g₂ γ hγ
  have hsum :
      0 ≤
        (⟪g₁, eval xp₂ - eval xp₁⟫_ℝ +
            γ⁻¹ * ⟪grad xp₁ - grad x₁, eval xp₂ - eval xp₁⟫_ℝ +
            (h xp₂ - h xp₁)) +
          (⟪g₂, eval xp₁ - eval xp₂⟫_ℝ +
            γ⁻¹ * ⟪grad xp₂ - grad x₂, eval xp₁ - eval xp₂⟫_ℝ +
            (h xp₁ - h xp₂)) := by
    dsimp [xp₁, xp₂] at hvi₁ hvi₂
    exact add_nonneg hvi₁ hvi₂
  have hcombine :
      (⟪g₁, eval xp₂ - eval xp₁⟫_ℝ +
            γ⁻¹ * ⟪grad xp₁ - grad x₁, eval xp₂ - eval xp₁⟫_ℝ +
            (h xp₂ - h xp₁)) +
          (⟪g₂, eval xp₁ - eval xp₂⟫_ℝ +
            γ⁻¹ * ⟪grad xp₂ - grad x₂, eval xp₁ - eval xp₂⟫_ℝ +
            (h xp₁ - h xp₂)) =
        ⟪g₂ - g₁, δ⟫_ℝ - γ⁻¹ * C + γ⁻¹ * B := by
    dsimp [δ, C, B]
    simp only [sub_eq_add_neg, inner_add_left, inner_add_right, inner_neg_left,
      inner_neg_right, real_inner_comm]
    ring
  have hsum' : 0 ≤ ⟪g₂ - g₁, δ⟫_ℝ - γ⁻¹ * C + γ⁻¹ * B := by
    rwa [hcombine] at hsum
  have hstrong' : ‖δ‖ ^ 2 ≤ C := by
    dsimp [δ, C]
    exact hstrong xp₁ xp₂
  have hγinv_nonneg : 0 ≤ γ⁻¹ := inv_nonneg.mpr (le_of_lt hγ)
  have hquad :
      γ⁻¹ * ‖δ‖ ^ 2 ≤
        ‖g₁ - g₂‖ * ‖δ‖ + γ⁻¹ * ‖grad x₁ - grad x₂‖ * ‖δ‖ := by
    have hmain :
        γ⁻¹ * ‖δ‖ ^ 2 ≤
          ⟪g₂ - g₁, δ⟫_ℝ + γ⁻¹ * B := by
      nlinarith
    have hg :
        ⟪g₂ - g₁, δ⟫_ℝ ≤ ‖g₁ - g₂‖ * ‖δ‖ := by
      calc
        ⟪g₂ - g₁, δ⟫_ℝ ≤ |⟪g₂ - g₁, δ⟫_ℝ| := le_abs_self _
        _ ≤ ‖g₂ - g₁‖ * ‖δ‖ := abs_real_inner_le_norm (g₂ - g₁) δ
        _ = ‖g₁ - g₂‖ * ‖δ‖ := by rw [norm_sub_rev]
    have hB :
        γ⁻¹ * B ≤ γ⁻¹ * ‖grad x₁ - grad x₂‖ * ‖δ‖ := by
      have hB_le :
          B ≤ ‖grad x₁ - grad x₂‖ * ‖δ‖ := by
        calc
          B ≤ |B| := le_abs_self _
          _ ≤ ‖grad x₁ - grad x₂‖ * ‖δ‖ := by
            simpa [B] using abs_real_inner_le_norm (grad x₁ - grad x₂) δ
      nlinarith
    nlinarith
  by_cases hδ : ‖δ‖ = 0
  · have hzero : ‖δ‖ ≤ γ * ‖g₁ - g₂‖ + ‖grad x₁ - grad x₂‖ := by
      rw [hδ]
      positivity
    simpa [δ] using hzero
  · have hδpos : 0 < ‖δ‖ := lt_of_le_of_ne (norm_nonneg δ) (Ne.symm hδ)
    have hquad' :
        γ⁻¹ * ‖δ‖ * ‖δ‖ ≤
          (‖g₁ - g₂‖ + γ⁻¹ * ‖grad x₁ - grad x₂‖) * ‖δ‖ := by
      nlinarith [hquad]
    have hdiv :
        γ⁻¹ * ‖δ‖ ≤
          ‖g₁ - g₂‖ + γ⁻¹ * ‖grad x₁ - grad x₂‖ :=
      le_of_mul_le_mul_right hquad' hδpos
    have hγ_nonneg : 0 ≤ γ := le_of_lt hγ
    have hscaled :
        γ * (γ⁻¹ * ‖δ‖) ≤
          γ * (‖g₁ - g₂‖ + γ⁻¹ * ‖grad x₁ - grad x₂‖) :=
      mul_le_mul_of_nonneg_left hdiv hγ_nonneg
    have hleft : γ * (γ⁻¹ * ‖δ‖) = ‖δ‖ := by
      field_simp [hγ.ne']
    have hright :
        γ * (‖g₁ - g₂‖ + γ⁻¹ * ‖grad x₁ - grad x₂‖) =
          γ * ‖g₁ - g₂‖ + ‖grad x₁ - grad x₂‖ := by
      field_simp [hγ.ne']
    simpa [δ, hleft, hright] using hscaled

/-- A fixed-stepsize prox selector is jointly continuous from a state-oracle distance bound.

If the prox selector is controlled by `γ` times oracle distance plus the
distance between gradients at the two states, then continuity of the gradient
map upgrades the bound to joint continuity in the state and oracle arguments.

Layer: Model | Gap: Level 1 (prox-step joint continuity from state-oracle stability)
Proof: use the metric epsilon-delta criterion. Split `ε` in half, use
  continuity of `grad` for the state contribution, and use the positive
  fixed stepsize bound to control the oracle contribution.
Source: Mathlib metric-space continuity and ordered-field algebra APIs
Used in: nonconvex stochastic mirror descent fixed-stepsize prox selector continuity
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, randomized stochastic mirror descent -/
theorem continuous_proxStep_of_state_oracle_bound
    {P E : Type*} [PseudoMetricSpace P] [NormedAddCommGroup E]
    (prox : P → E → P) (grad : P → E) (γ : ℝ) (hγ : 0 < γ)
    (hgrad : Continuous grad)
    (hbound :
      ∀ (x₁ x₂ : P) (g₁ g₂ : E),
        dist (prox x₁ g₁) (prox x₂ g₂) ≤
          γ * dist g₁ g₂ + dist (grad x₁) (grad x₂)) :
    Continuous (fun p : P × E => prox p.1 p.2) := by
  refine continuous_iff_continuousAt.2 ?_
  intro p₀
  rw [Metric.continuousAt_iff]
  intro ε hε
  have hε2 : 0 < ε / 2 := half_pos hε
  rcases Metric.continuousAt_iff.1 (hgrad.continuousAt (x := p₀.1)) (ε / 2) hε2 with
    ⟨δν, hδν_pos, hδν⟩
  let δ : ℝ := min (ε / (2 * max γ 1)) δν
  have hmax_pos : 0 < max γ 1 :=
    lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1) (le_max_right γ 1)
  have hδ_pos : 0 < δ := by
    exact lt_min (div_pos hε (mul_pos (by norm_num) hmax_pos)) hδν_pos
  refine ⟨δ, hδ_pos, ?_⟩
  intro p hp
  rw [Prod.dist_eq] at hp
  have hp_fst_delta : dist p.1 p₀.1 < δ := (max_lt_iff.mp hp).1
  have hp_snd_delta : dist p.2 p₀.2 < δ := (max_lt_iff.mp hp).2
  have hp_fst : dist p.1 p₀.1 < δν := by
    have hle : δ ≤ δν := min_le_right _ _
    exact lt_of_lt_of_le hp_fst_delta hle
  have hp_snd : dist p.2 p₀.2 < ε / (2 * max γ 1) := by
    have hle : δ ≤ ε / (2 * max γ 1) := min_le_left _ _
    exact lt_of_lt_of_le hp_snd_delta hle
  have hνdist :
      dist (grad p.1) (grad p₀.1) < ε / 2 :=
    hδν hp_fst
  have hdist_bound :
      dist (prox p.1 p.2) (prox p₀.1 p₀.2) ≤
        γ * dist p.2 p₀.2 + dist (grad p.1) (grad p₀.1) :=
    hbound p.1 p₀.1 p.2 p₀.2
  have hγ_le_max : γ ≤ max γ 1 := le_max_left γ 1
  have hgsmall : γ * dist p.2 p₀.2 < ε / 2 := by
    calc
      γ * dist p.2 p₀.2 ≤ max γ 1 * dist p.2 p₀.2 :=
        mul_le_mul_of_nonneg_right hγ_le_max dist_nonneg
      _ < max γ 1 * (ε / (2 * max γ 1)) :=
        mul_lt_mul_of_pos_left hp_snd hmax_pos
      _ = ε / 2 := by
        field_simp [(ne_of_gt hmax_pos)]
  exact lt_of_le_of_lt hdist_bound (by linarith)

/-- A fixed state-oracle prox selector is measurable when its uncurried form is continuous.

This packages the standard continuity-to-measurability bridge for a prox selector
whose stepsize has already been fixed, so the remaining arguments are the current
state and oracle vector.

Layer: Model | Gap: Level 0 (prox-step measurability from joint continuity)
Proof: apply Mathlib's `Continuous.measurable` theorem to the uncurried selector
  on the product Borel space.
Source: Mathlib topology and Borel measurability APIs for continuous maps
Used in: randomized stochastic mirror descent prox-step measurability for the
  fixed-stepsize state-oracle recursion
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, randomized stochastic mirror descent -/
theorem measurable_proxStep_of_continuous_state_oracle
    {P E : Type*} [TopologicalSpace P] [MeasurableSpace P] [BorelSpace P]
    [TopologicalSpace E] [MeasurableSpace E] [BorelSpace E]
    [SecondCountableTopologyEither P E]
    (prox : P → E → P)
    (hprox : Continuous (fun p : P × E => prox p.1 p.2)) :
    Measurable (fun p : P × E => prox p.1 p.2) := by
  exact hprox.measurable

end SOptLib

namespace SOptLib

/-- Composite mirror-prox objective with a linear oracle term, Bregman term,
and simple additive objective component.

For an abstract candidate type `P`, evaluation map `eval : P → E`, divergence
`V`, and simple term `h`, this names the source objective
`u ↦ ⟪g, eval u⟫ + γ⁻¹ V x u + h u`.

Layer: Model | Concept: Prox
Proof: (definitional construction; abstract composite mirror-prox objective
  combining an inner-product oracle term, inverse-stepsize divergence term,
  and simple additive objective component)
Source: Mathlib inner product space notation and real scalar algebra APIs
Used in: nonconvex stochastic mirror descent composite prox-step objective
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def paperProxObjective
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (eval : P → E) (V : P → P → ℝ) (h : P → ℝ)
    (x : P) (g : E) (γ : ℝ) (u : P) : ℝ :=
  ⟪g, eval u⟫_ℝ + γ⁻¹ * V x u + h u

/-- Argmin predicate for a composite mirror-prox objective.

For an abstract candidate type `P`, evaluation map `eval : P → E`, divergence
`V`, and simple term `h`, this names the condition that `xplus` minimizes the
objective `u ↦ ⟪g, eval u⟫ + γ⁻¹ V x u + h u` over all candidates.

Layer: Model | Concept: Prox
Proof: (definitional construction; global argmin wrapper for the abstract composite mirror-prox objective)
Source: Mathlib order argmin predicates and inner-product model objective APIs
Used in: nonconvex stochastic mirror descent composite prox-step argmin predicate
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
def IsPaperProxPoint
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (eval : P → E) (V : P → P → ℝ) (h : P → ℝ)
    (x : P) (g : E) (γ : ℝ) (xplus : P) : Prop :=
  IsMinOn (SOptLib.paperProxObjective eval V h x g γ) Set.univ xplus

/-- Composite prox objective with a linear oracle term, inverse-stepsize Bregman term,
and simple additive objective component.

For an abstract candidate type `P`, evaluation map `eval : P → E`, divergence
`V`, and simple term `h`, this names the source objective
`u ↦ ⟪g, eval u⟫ + γ⁻¹ V x u + h u`.

Layer: Model | Concept: Prox
Proof: (definitional construction; abstract composite prox objective combining
  an inner-product oracle term, inverse-stepsize divergence term, and simple
  additive objective component)
Source: Mathlib inner product space notation and real scalar algebra APIs
Used in: nonconvex stochastic mirror descent composite prox-step objective
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def proxObjective
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (h : P → ℝ) (eval : P → E)
    (x : P) (g : E) (γ : ℝ) (u : P) : ℝ :=
  ⟪g, eval u⟫_ℝ + γ⁻¹ * V x u + h u

/-- Argmin predicate for an abstract composite prox objective.

For a candidate type `P`, oracle vector space `E`, and parameterized prox
objective, this names the condition that `xplus` minimizes `objective x g γ`
over all candidates.

Layer: Model | Concept: Prox
Proof: (definitional construction; global argmin wrapper for a parameterized
  composite prox objective over the universal feasible set)
Source: Mathlib order argmin predicates for objective minimization over sets
Used in: nonconvex stochastic mirror descent composite prox-step argmin predicate
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
def IsProxPoint
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (objective : P → E → ℝ → P → ℝ)
    (x : P) (g : E) (γ : ℝ) (xplus : P) : Prop :=
  IsMinOn (objective x g γ) Set.univ xplus

namespace PaperProxSelector

/-- A selector returning a point bundled with its step certificate satisfies the
step predicate at the selected point.

Layer: Model | Gap: Level 0 (certified prox selector specification)
Proof: project the proof component from the subtype returned by the selector.
Source: Mathlib subtype API for bundled witnesses and specifications
Used in: stochastic mirror descent prox-map certificate projection
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem isProx {P Param : Type*} (isStep : Param → P → Prop)
    (selector : ∀ p : Param, {z : P // isStep p z}) :
    ∀ p : Param, isStep p (selector p).1 :=
  fun p => (selector p).2

end PaperProxSelector

/-- Exact projected-gradient mapping obtained by evaluating a projected-gradient mapping at
the true gradient.

This abstracts the paper-local definition `g_X(x) = P_X(x, ∇f(x), γ)` away from
the concrete optimization setup while retaining the positive-stepsize proof
argument used by prox-based projected-gradient mappings.

Layer: Model | Concept: Prox
Proof: (definitional construction; specialize an abstract projected-gradient mapping to the supplied true-gradient field)
Source: Mathlib dependent function application over real step-size parameters
Used in: nonconvex stochastic mirror descent exact projected-gradient stationarity mapping
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def exactProjectedGradient
    {P E : Type*}
    (grad : P → E)
    (projectedGradient : (x : P) → E → (gamma : ℝ) → 0 < gamma → E)
    (x : P) (gamma : ℝ) (hgamma : 0 < gamma) : E :=
  projectedGradient x (grad x) gamma hgamma

/-- Projected-gradient mapping induced by an evaluation map and a prox selector.

For an abstract feasible-point type `P`, ambient vector space `E`, evaluation
map `eval`, and selected prox point `prox x g gamma`, this names the vector
`gamma⁻¹ • (eval x - eval (prox x g gamma))` used as the generalized projected
gradient mapping.

Layer: Model | Concept: Prox
Proof: (definitional construction; inverse-stepsize scaling of the displacement from the current point to the selected prox point)
Source: Mathlib normed vector space scalar action and subtraction APIs
Used in: nonconvex stochastic mirror descent projected-gradient mapping definition for prox-step stationarity
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def projectedGradient
    {P E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (eval : P → E) (prox : P → E → ℝ → P)
    (x : P) (g : E) (gamma : ℝ) : E :=
  gamma⁻¹ • (eval x - eval (prox x g gamma))

/-- The abstract projected-gradient mapping unfolds to the scaled prox displacement.

This simp lemma keeps algorithm-local projected-gradient notation reducible to
the inverse-stepsize-scaled difference between the current point and its selected
prox point.

Layer: Model | Gap: Level 0 (projected-gradient mapping unfolding)
Proof: by rfl after unfolding `projectedGradientMapping`.
Source: Mathlib normed vector space scalar action and subtraction APIs
Used in: nonconvex stochastic mirror descent projected-gradient mapping definition for prox-step stationarity
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
@[simp]
theorem projectedGradient_apply
    {P E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (eval : P → E) (prox : P → E → ℝ → P)
    (x : P) (g : E) (gamma : ℝ) :
    projectedGradient eval prox x g gamma =
      gamma⁻¹ • (eval x - eval (prox x g gamma)) := by
  rfl

/-- The abstract projected-gradient mapping unfolds to the scaled displacement from a prox point.

For an abstract feasible-point type `P`, ambient vector space `E`, evaluation
map `eval`, and selected prox point `prox x g gamma`, the mapping is exactly
`gamma⁻¹ • (eval x - eval (prox x g gamma))`.

Layer: Model | Gap: Level 0 (projected-gradient mapping definitional unfolding)
Proof: by rfl after unfolding projectedGradientMapping.
Source: Mathlib normed vector space scalar action and subtraction APIs
Used in: nonconvex stochastic mirror descent projected-gradient mapping definition for prox-step stationarity
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem projectedGradient_eq
    {P E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (eval : P → E) (prox : P → E → ℝ → P)
    (x : P) (g : E) (gamma : ℝ) :
    projectedGradient eval prox x g gamma =
      gamma⁻¹ • (eval x - eval (prox x g gamma)) := by
  rfl

/-- The exact projected-gradient mapping is measurable in the state variable.

If the ambient evaluation map, true-gradient field, and fixed-stepsize prox
selector are measurable, then the inverse-stepsize-scaled prox displacement
`x ↦ gamma⁻¹ • (eval x - eval (prox x (grad x) gamma))` is measurable.

Layer: Model | Gap: Level 1 (projected-gradient state measurability)
Proof: compose the measurable prox selector with the measurable state-gradient
  pairing, then use measurability of subtraction and constant scalar
  multiplication in the ambient normed vector space.
Source: Mathlib Borel measurability API for products, subtraction, and scalar
  multiplication in normed additive groups
Used in: nonconvex stochastic mirror descent exact projected-gradient
  stationarity mapping at validation output states
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem exactProjectedGradient_measurable_state
    {P E : Type*} [MeasurableSpace P] [MeasurableSpace E]
    [NormedAddCommGroup E] [NormedSpace ℝ E] [BorelSpace E] [MeasurableSub₂ E]
    (eval : P → E) (prox : P → E → ℝ → P) (grad : P → E) (gamma : ℝ)
    (heval : Measurable eval)
    (hgrad : Measurable grad)
    (hprox : Measurable (fun p : P × E => prox p.1 p.2 gamma)) :
    Measurable (fun x : P =>
      SOptLib.projectedGradient eval prox x (grad x) gamma) := by
  have hpair : Measurable (fun x : P => (x, grad x)) :=
    measurable_id.prodMk hgrad
  have hprox_state : Measurable (fun x : P => prox x (grad x) gamma) :=
    hprox.comp hpair
  have hprox_eval : Measurable (fun x : P => eval (prox x (grad x) gamma)) :=
    heval.comp hprox_state
  simpa [SOptLib.projectedGradient] using
    (heval.sub hprox_eval).const_smul gamma⁻¹

/-- Empirical projected-gradient mapping from an abstract empirical oracle average.

For an abstract projected-gradient map, empirical average indexed by a run and
output selector, and output-dependent stepsize, this names the empirical
projected-gradient quantity used to test stationarity at a candidate point.

Layer: Model | Concept: Prox
Proof: (definitional construction; projected-gradient map applied to the empirical oracle average and selected stepsize)
Source: Mathlib normed vector space function application APIs and Lan projected-gradient stationarity notation
Used in: nonconvex stochastic mirror descent empirical stationarity selector at the randomized run output
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/output/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
noncomputable def empiricalProjectedGradient
    {Run Out X Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (projectedGradient : X → E → ℝ → E)
    (empiricalAverage : Run → Out → X → Ω → E) (stepsize : Out → ℝ)
    (run : Run) (out : Out) (x : X) (ω : Ω) : E :=
  projectedGradient x (empiricalAverage run out x ω) (stepsize out)

/-- The empirical projected-gradient mapping unfolds to the projected-gradient
map evaluated at the empirical average and the output-dependent stepsize.

Layer: Model | Gap: Level 0 (empirical projected-gradient unfolding)
Proof: by rfl after unfolding `empiricalProjectedGradient`.
Source: Mathlib normed vector space function application APIs and Lan projected-gradient stationarity notation
Used in: nonconvex stochastic mirror descent empirical stationarity selector at the randomized run output
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec/output/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
@[simp]
theorem empiricalProjectedGradient_apply
    {Run Out X Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (projectedGradient : X → E → ℝ → E)
    (empiricalAverage : Run → Out → X → Ω → E) (stepsize : Out → ℝ)
    (run : Run) (out : Out) (x : X) (ω : Ω) :
    empiricalProjectedGradient projectedGradient empiricalAverage stepsize run out x ω =
      projectedGradient x (empiricalAverage run out x ω) (stepsize out) := by
  rfl

/-- A carrier composite prox objective agrees with the paper prox objective
when the supplied divergence is the Bregman expression generated by `nu`.

This packages the definitional bridge between an abstract composite prox
objective using `V` and the paper's expanded objective on a feasible-set
carrier, whose divergence term is written from `nu` and a carrier gradient.

Layer: Model | Gap: Level 0 (composite prox objective formula bridge)
Proof: unfold the two staged objective definitions and rewrite the supplied
  divergence by the Bregman-form compatibility hypothesis.
Source: Mathlib inner-product notation and real algebra simplification APIs
Used in: nonconvex stochastic mirror descent prox-step objective normalization
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic mirror descent -/
theorem proxObjective_eq_paperProxObjective
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {X : Set E} (h nu : {x : E // x ∈ X} → ℝ)
    (V : {x : E // x ∈ X} → {x : E // x ∈ X} → ℝ)
    (grad : {x : E // x ∈ X} → E)
    (hV : ∀ x u, V x u = nu u - nu x - ⟪grad x, u.1 - x.1⟫_ℝ)
    (x : {x : E // x ∈ X}) (g : E) (γ : ℝ)
    (u : {x : E // x ∈ X}) :
    SOptLib.proxObjective V h
        (fun u : {x : E // x ∈ X} => (u.1 : E)) x g γ u =
      SOptLib.paperProxObjective
        (eval := fun u : {x : E // x ∈ X} => (u.1 : E))
        (V := fun x u => nu u - nu x - ⟪grad x, u.1 - x.1⟫_ℝ)
        (h := h) x g γ u := by
  rw [SOptLib.proxObjective, SOptLib.paperProxObjective, hV x u]

/-- Pointwise equal composite prox objectives have equivalent global argmin predicates.

This is the objective-level bridge used when an algorithm-local prox predicate
and a paper-local prox predicate wrap the same candidate minimization problem
through different objective names.

Layer: Model | Gap: Level 0 (composite prox argmin predicate normalization)
Proof: rewrite both endpoint and comparison objective evaluations with the
  supplied pointwise equality, then discharge the two `IsMinOn` predicates by
  simplification.
Source: Mathlib order argmin predicates for real-valued objective minimization
Used in: nonconvex stochastic mirror descent prox-step predicate normalization
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic mirror descent -/
theorem isProxPoint_iff_isPaperProxPoint
    {P : Type*} (objective₁ objective₂ : P → ℝ) (z : P)
    (hobjective : ∀ u : P, objective₁ u = objective₂ u) :
    IsMinOn objective₁ Set.univ z ↔ IsMinOn objective₂ Set.univ z := by
  rw [isMinOn_univ_iff, isMinOn_univ_iff]
  constructor
  · intro hz y
    simpa [hobjective z, hobjective y] using hz y
  · intro hz y
    simpa [hobjective z, hobjective y] using hz y

/-- Selected point from a bundled composite prox argmin map.

For an abstract candidate type `P`, evaluation map `eval : P -> E`, divergence
`V`, and simple term `h`, this returns the point component of a prox map that
bundles each selected point with its global minimizing certificate.

Layer: Model | Concept: Prox
Proof: (definitional construction; projection of the selected point from a
  bundled composite prox argmin map at a positive stepsize)
Source: Mathlib subtype projections and order argmin predicates for real-valued
  inner-product objectives
Used in: nonconvex stochastic mirror descent prox-step selector from the
  algorithmic argmin map
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def proxPoint
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (h : P → ℝ) (eval : P → E)
    (proxMap :
      ∀ p : P × E × {γ : ℝ // 0 < γ},
        {z : P //
          IsMinOn
            (fun u : P => ⟪p.2.1, eval u⟫_ℝ + p.2.2.1⁻¹ * V p.1 u + h u)
            Set.univ z})
    (x : P) (g : E) (γ : ℝ) (hγ : 0 < γ) : P :=
  (proxMap (x, g, ⟨γ, hγ⟩)).1

end SOptLib

/-- Root-namespace compatibility alias for the literal mirror-prox objective.

Mirrors `SOptLib.literalMirrorObjective` at the root namespace so callers
that use the unqualified name still resolve.

Layer: Model | Concept: MirrorDescent
Proof: (definitional construction; root-namespace delegation to
  `SOptLib.literalMirrorObjective`).
Source: Mathlib inner product space notation and real scalar algebra APIs
Used in: stochastic mirror descent prox-step literal objective expansion at
  root-namespace callsites
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def literalMirrorObjective
    {E Xint P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (Vlit : Xint → P → ℝ) (eval : P → E) (x : Xint) (g : E) (γ : ℝ) (y : P) : ℝ :=
  SOptLib.literalMirrorObjective Vlit eval x g γ y

/-- Expanded formula for the root-namespace literal mirror-prox objective.

States that the root-namespace alias unfolds to the canonical paper formula
`γ · ⟪g, eval y⟫_ℝ + Vlit x y` definitionally.

Layer: Model | Gap: Level 0 (root-namespace literal mirror objective unfolding)
Proof: by rfl after unfolding the root-namespace `literalMirrorObjective`.
Source: Mathlib inner product space notation and real algebra APIs
Used in: stochastic mirror descent prox-step objective normalization at
  root-namespace callsites
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem literalMirrorObjective_def
    {E Xint P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (Vlit : Xint → P → ℝ) (eval : P → E) (x : Xint) (g : E) (γ : ℝ) (y : P) :
    literalMirrorObjective Vlit eval x g γ y = γ * ⟪g, eval y⟫_ℝ + Vlit x y := by
  rfl

/-- Root-namespace bridge from the literal mirror-prox objective to the
canonical paper-mirror objective.

Given a point-map compatibility witness `hV` between the carrier potential
`Vlit` and the paper potential `V`, the root-namespace literal objective at
`(x, g, γ, y)` agrees with the paper objective at `(toPoint x, g, γ, y)`.

Layer: Model | Gap: Level 0 (root-namespace literal-to-paper objective bridge)
Proof: direct delegation to `SOptLib.literalMirrorObjective_eq_paperMirrorObjective`
  through the point-map compatibility hypothesis.
Source: Mathlib simplification and rewriting APIs for real inner-product expressions
Used in: stochastic mirror descent bridge from literal prox objectives to carrier
  paper objectives at root-namespace callsites
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem literalMirrorObjective_eq_paperMirrorObjective
    {E Xint P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (Vlit : Xint → P → ℝ) (toPoint : Xint → P) (eval : P → E)
    (hV : ∀ x y, V (toPoint x) y = Vlit x y)
    (x : Xint) (g : E) (γ : ℝ) (y : P) :
    literalMirrorObjective Vlit eval x g γ y =
      SOptLib.paperMirrorObjective V eval (toPoint x) g γ y := by
  exact SOptLib.literalMirrorObjective_eq_paperMirrorObjective
    V Vlit toPoint eval hV x g γ y

/-- Backward-compatible mirror-step alias for the canonical stochastic mirror descent prox selector.

Layer: Model | Concept: MirrorDescent
Proof: (definitional construction; canonical mirror-step wrapper that returns
  the supplied prox selector value unchanged).
Source: FOML stochastic mirror descent chapter notation for prox-generated mirror steps
Used in: stochastic mirror descent canonical update compatibility with prox-step statements
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
noncomputable def mirrorStep
    {P E : Type*} (proxStep : P → E → ℝ → P) (x : P) (g : E) (γ : ℝ) : P :=
  proxStep x g γ

/-- The paper mirror-step alias agrees definitionally with the canonical prox-step selector.

Layer: Model | Gap: Level 0 (mirrorStep proxStep alias definitional equality)
Proof: by rfl after unfolding mirrorStep.
Source: Mathlib logic and definitional equality APIs
Used in: stochastic mirror descent mirror-step notation compatibility for prox-step updates
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
theorem mirrorStep_eq_proxStep
    {P E : Type*} (proxStep : P → E → ℝ → P) (x : P) (g : E) (γ : ℝ) :
    mirrorStep proxStep x g γ = proxStep x g γ := by
  rfl

namespace SOptLib

/-- The backward-compatible mirror-step alias is definitionally the canonical
prox selector.

This is the `SOptLib`-namespace re-export of the root-level `mirrorStep_eq_proxStep`
fact, used so that callers under `open SOptLib` can refer to the equality without
the `_root_` prefix.

Layer: Model | Gap: Level 0 (SOptLib re-export of mirrorStep proxStep alias equality)
Proof: direct delegation to the root-namespace `mirrorStep_eq_proxStep`.
Source: Mathlib logic and definitional equality APIs
Used in: stochastic mirror descent mirror-step notation compatibility for
  prox-step updates inside the `SOptLib` namespace
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem mirrorStep_eq_proxStep
    {E P : Type*} (proxStep : P → E → ℝ → P) (x : P) (g : E) (γ : ℝ) :
    _root_.mirrorStep proxStep x g γ = proxStep x g γ := by
  exact _root_.mirrorStep_eq_proxStep proxStep x g γ

end SOptLib

/-- The mirror-step alias preserves the abstract prox argmin predicate.

For any prox-step selector satisfying `IsMirrorStep`, the backward-compatible
`mirrorStep` wrapper satisfies the same mirror-step argmin specification at
each state, gradient, and stepsize.

Layer: Model | Gap: Level 0 (mirror-step alias preserves argmin specification)
Proof: unfold `mirrorStep` and discharge the goal by simplification from the
  supplied prox-step specification.
Source: Mathlib simplifier and definitional unfolding APIs
Used in: stochastic mirror descent mirror step chosen by an argmin predicate
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem mirrorStep_isMirrorStep
    {E P : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {V : P → P → ℝ} {eval : P → E}
    (proxStep : P → E → ℝ → P)
    (h_proxStep : ∀ x g γ, SOptLib.IsMirrorStep V eval x g γ (proxStep x g γ))
    (x : P) (g : E) (γ : ℝ) :
    SOptLib.IsMirrorStep V eval x g γ (mirrorStep proxStep x g γ) := by
  simpa [mirrorStep] using h_proxStep x g γ

/-- Measurability transfers from a prox-step selector to a pointwise equal mirror-step alias.

Layer: Model | Gap: Level 0 (mirrorStep/proxStep measurability alias)
Proof: convert the prox-step measurability proof along pointwise equality, then
  close the generated functional equality goal by extensionality.
Source: Mathlib measure theory measurability APIs and function extensionality
Used in: stochastic mirror descent measurable mirror-step selector obtained from
  the prox-step implementation
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem mirrorStep_measurable_of_eq_proxStep
    {P E : Type*} [MeasurableSpace P] [MeasurableSpace E]
    {proxStep mirrorStep : P → E → ℝ → P}
    (h_proxStep : Measurable (fun p : P × E × ℝ => proxStep p.1 p.2.1 p.2.2))
    (h_eq : ∀ x g γ, mirrorStep x g γ = proxStep x g γ) :
    Measurable (fun p : P × E × ℝ => mirrorStep p.1 p.2.1 p.2.2) := by
  convert h_proxStep using 1
  ext p
  exact h_eq p.1 p.2.1 p.2.2

/-- A packaged mirror-step selector minimizes the paper mirror objective pointwise.

If `mirrorStep x g γ` is certified by `IsMirrorStep` for every iterate, gradient,
and stepsize, then it is an argmin of `paperMirrorObjective V eval x g γ` against
every candidate `y`.

Layer: Model | Gap: Level 0 (mirror-step argmin unpacking)
Proof: unfold the abstract mirror-step certificate through `isMirrorStep_iff`;
  the forward direction supplies the required pointwise objective inequality.
Source: Mathlib order theory for real-valued minimization inequalities
Used in: stochastic mirror descent mirrorStep minimizes paperMirrorObjective over the carrier type
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
theorem mirrorStep_minimizes
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (eval : P → E) (mirrorStep : P → E → ℝ → P)
    (h_mirrorStep_isMirrorStep :
      ∀ x g γ, SOptLib.IsMirrorStep V eval x g γ (mirrorStep x g γ))
    (x : P) (g : E) (γ : ℝ) (y : P) :
    SOptLib.paperMirrorObjective V eval x g γ (mirrorStep x g γ) ≤
      SOptLib.paperMirrorObjective V eval x g γ y := by
  exact (SOptLib.isMirrorStep_iff (V := V) (eval := eval) x g γ
      (mirrorStep x g γ)).1 (h_mirrorStep_isMirrorStep x g γ) y

namespace SOptLib

/-- Abstract literal mirror-step argmin predicate for a packaged prox objective.

Layer: Model | Concept: Prox
Proof: (definitional construction; wraps the literal mirror-step objective as an
  `IsMinOn` predicate over `Set.univ`)
Source: Mathlib order extrema predicates and set API
Used in: stochastic mirror descent literal mirror-step argmin specification
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
def IsLiteralMirrorStep
    {Xint E P : Type*}
    (objective : Xint → E → ℝ → P → ℝ) (x : Xint) (g : E) (γ : ℝ) (z : P) : Prop :=
  IsMinOn (objective x g γ) Set.univ z

/-- Literal mirror-step optimality over all candidates is pointwise objective domination.

Expands the abstract `IsLiteralMirrorStep` argmin predicate into the concrete
condition that the selected point has objective value no larger than every
candidate in the full space.

Layer: Model | Gap: Level 0 (universal argmin predicate expansion)
Proof: by rewriting `IsLiteralMirrorStep` and using the `IsMinOn` characterization
  over `Set.univ`.
Source: Mathlib order/set APIs for minimizers on the universal set
Used in: stochastic mirror descent mirror-step argmin normalization
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem isLiteralMirrorStep_iff
    {Xint E P : Type*}
    (objective : Xint → E → ℝ → P → ℝ) (x : Xint) (g : E) (γ : ℝ) (z : P) :
    IsLiteralMirrorStep objective x g γ z ↔
      ∀ y : P, objective x g γ z ≤ objective x g γ y := by
  rw [IsLiteralMirrorStep, isMinOn_univ_iff]

/-- Transport mirror-step argmin witnesses from the paper objective to the literal objective.

If the paper mirror-step selector minimizes the carrier objective on `Set.univ`
and the literal objective is pointwise equal after `toPoint` reindexing, then
the same selected point satisfies the literal mirror-step argmin predicate.

Layer: Model | Gap: Level 0 (argmin predicate transport under objective reindexing)
Proof: rewrite both objective values using the pointwise equality and unfold
  minimization on `Set.univ` via `isMinOn_univ_iff`.
Source: Mathlib order predicates and `IsMinOn` optimization APIs
Used in: stochastic mirror descent `mirrorStep` verification for the literal
  interior objective
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic mirror descent -/
theorem isLiteralMirrorStep_of_isMirrorStep
    {I E P : Type*}
    (paper : P → E → ℝ → P → ℝ)
    (literal : I → E → ℝ → P → ℝ)
    (toPoint : I → P)
    (step : P → E → ℝ → P)
    (hstep : ∀ x : P, ∀ g : E, ∀ γ : ℝ,
      IsMinOn (paper x g γ) Set.univ (step x g γ))
    (hEq : ∀ x : I, ∀ g : E, ∀ γ : ℝ, ∀ y : P,
      literal x g γ y = paper (toPoint x) g γ y) :
    ∀ x : I, ∀ g : E, ∀ γ : ℝ,
      IsLiteralMirrorStep literal x g γ (step (toPoint x) g γ) := by
  intro x g γ
  refine (isMinOn_univ_iff).2 ?_
  intro y
  have hpaper : paper (toPoint x) g γ (step (toPoint x) g γ)
      ≤ paper (toPoint x) g γ y := (isMinOn_univ_iff.mp (hstep (toPoint x) g γ)) y
  simpa [hEq x g γ (step (toPoint x) g γ), hEq x g γ y] using hpaper

/-- A raw mirror-prox block selector lifted to a positive-stepsize selector.

Given a selector defined for every real stepsize, this names the corresponding
selector on positive stepsizes by retaining the same selected point and carrying
the positivity proof in the type.

Layer: Model | Concept: Prox
Proof: (definitional construction; apply the raw real-stepsize selector and
  retain the positive-stepsize proof only in the wrapper type)
Source: Mathlib dependent function application over positive real stepsizes
Used in: stochastic block mirror descent positive-stepsize one-block prox update
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
noncomputable def positiveStepsizeMirrorProxBlock
    {P E : Type*} (raw : P → E → ℝ → P)
    (x : P) (g : E) (gamma : ℝ) (_hgamma : 0 < gamma) : P :=
  raw x g gamma

/-- The positive-stepsize mirror-prox block selector unfolds to the raw selector.

Layer: Model | Gap: Level 0 (positive-stepsize mirror-prox selector unfolding)
Proof: by rfl after unfolding `positiveStepsizeMirrorProxBlock`.
Source: Mathlib dependent function application over positive real stepsizes
Used in: stochastic block mirror descent positive-stepsize one-block prox update
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
@[simp]
theorem positiveStepsizeMirrorProxBlock_apply
    {P E : Type*} (raw : P → E → ℝ → P)
    (x : P) (g : E) (gamma : ℝ) (hgamma : 0 < gamma) :
    positiveStepsizeMirrorProxBlock raw x g gamma hgamma = raw x g gamma := by
  rfl

/-- A compact unique argmin selector for a mirror objective is measurable.

For the mirror objective `gamma * <g, eval y> + V x y`, joint continuity follows
from continuity of `V` and `eval`; compactness, the canonical `proxStep`
minimality certificate, and uniqueness make the selected point Borel-measurable
in `(x, g, gamma)`.

Layer: Model | Gap: Level 1 (mirror-objective compact argmin selector measurability)
Proof: build joint continuity of the named mirror objective from the continuity
  of the divergence and evaluation maps, then apply compact unique-argmin
  selector measurability.
Source: Mathlib compactness, product-topology continuity, inner-product
  continuity, and Borel measurability APIs
Used in: stochastic block mirror descent one-block prox selector measurability
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem mirrorObjective_argmin_selector_measurable_of_continuous_unique
    {P E : Type*} [TopologicalSpace P] [MeasurableSpace P] [BorelSpace P]
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [MeasurableSpace E] [BorelSpace E] [OpensMeasurableSpace (P × E × ℝ)]
    {V : P → P → ℝ} {eval : P → E}
    (hcompact : IsCompact (Set.univ : Set P))
    (hV : Continuous (fun p : P × P => V p.1 p.2))
    (heval : Continuous eval)
    (hunique : ∀ x g γ z z',
      (∀ y, SOptLib.paperMirrorObjective V eval x g γ z ≤
        SOptLib.paperMirrorObjective V eval x g γ y) →
      (∀ y, SOptLib.paperMirrorObjective V eval x g γ z' ≤
        SOptLib.paperMirrorObjective V eval x g γ y) →
      z = z') :
    Measurable (fun p : P × E × ℝ =>
      SOptLib.proxStep hcompact hV heval p.1 p.2.1 p.2.2) := by
  classical
  letI : CompactSpace P := isCompact_univ_iff.mp hcompact
  refine proxStep_measurable_of_joint_continuous_unique
    (F := SOptLib.paperMirrorObjective V eval)
    (sel := SOptLib.proxStep hcompact hV heval) ?_ ?_ ?_
  · exact SOptLib.paperMirrorObjective_joint_continuous hV heval
  · intro x g γ y
    exact SOptLib.proxStep_minimizes hcompact hV heval x g γ y
  · exact hunique

/-- A positive-stepsize mirror-prox selector minimizing the scaled mirror objective
also minimizes the unscaled inverse-stepsize prox objective.

The theorem converts minimization of `γ * ⟪g, eval ·⟫ + V x ·` into minimization
of `⟪g, eval ·⟫ + γ⁻¹ * V x ·` by multiplying the objective comparison by the
positive inverse stepsize and normalizing the real algebra.

Layer: Model | Gap: Level 0 (positive-stepsize prox objective normalization)
Proof: expand the global `IsMinOn` predicate, multiply the supplied scaled
  objective comparison by the nonnegative inverse stepsize, and simplify using
  `γ ≠ 0`.
Source: Mathlib ordered-field algebra and SOptLib mirror/prox objective APIs
Used in: stochastic block mirror descent one-block prox selector objective normalization
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec/steps/2/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem positiveStepsizeMirrorProxBlock_isMinOn_unscaled
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (eval : P → E) (raw : P → E → ℝ → P)
    (hraw : ∀ (x : P) (g : E) (γ : ℝ) (y : P),
      SOptLib.paperMirrorObjective V eval x g γ (raw x g γ) ≤
        SOptLib.paperMirrorObjective V eval x g γ y)
    (x : P) (g : E) (γ : ℝ) (hγ : 0 < γ) :
    IsMinOn (SOptLib.proxObjective V (fun _ : P => 0) eval x g γ) Set.univ
      (positiveStepsizeMirrorProxBlock raw x g γ hγ) := by
  rw [isMinOn_univ_iff]
  intro y
  have hpaper :
      SOptLib.paperMirrorObjective V eval x g γ (raw x g γ) ≤
        SOptLib.paperMirrorObjective V eval x g γ y :=
    hraw x g γ y
  have hscaled :
      γ⁻¹ * (γ * ⟪g, eval (raw x g γ)⟫_ℝ + V x (raw x g γ)) ≤
        γ⁻¹ * (γ * ⟪g, eval y⟫_ℝ + V x y) := by
    refine mul_le_mul_of_nonneg_left ?_ (le_of_lt (inv_pos.mpr hγ))
    simpa [SOptLib.paperMirrorObjective] using hpaper
  have hne : γ ≠ 0 := ne_of_gt hγ
  simpa [positiveStepsizeMirrorProxBlock, SOptLib.proxObjective,
    SOptLib.paperMirrorObjective, mul_add, mul_assoc, hne] using hscaled

/-- The zero-simple-term prox objective expands to its linear term plus inverse-scaled divergence.

For a candidate type `P`, evaluation map `eval`, divergence `V`, base point `x`,
oracle vector `g`, stepsize `γ`, and candidate `u`, the composite prox objective
with simple term `0` is exactly `⟪g, eval u⟫ + γ⁻¹ * V x u`.

Layer: Model | Gap: Level 0 (zero composite prox objective expansion)
Proof: by rfl after unfolding `SOptLib.proxObjective` and simplifying the zero
  simple term.
Source: Mathlib inner product space notation and real algebra APIs
Used in: stochastic block mirror descent one-block prox objective expansion
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec/steps/2/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem proxObjective_zero_eq
    {P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (V : P → P → ℝ) (eval : P → E) (x : P) (g : E) (γ : ℝ) (u : P) :
    SOptLib.proxObjective V (fun _ : P => 0) eval x g γ u =
      ⟪g, eval u⟫_ℝ + γ⁻¹ * V x u := by
  simp [SOptLib.proxObjective]

/-- A compact continuous mirror-prox subproblem has a minimizer for the inverse-stepsize
prox objective.

The compact extreme-value theorem gives a minimizer of the zero simple-term
objective `SOptLib.proxObjective V (fun _ => 0) eval x g γ` from continuity of
the fixed-base divergence section and the evaluation map.

Layer: Model | Gap: Level 1 (compact inverse-stepsize prox argmin existence)
Proof: apply `IsCompact.exists_isMinOn` to the continuous prox objective.
Source: Mathlib compact extreme-value theorem and ordered-field algebra APIs
Used in: stochastic block mirror descent one-block compact prox subproblem existence
Book citation: book/FOML/StochasticBlockMirrorDescent.json#/algorithm_spec/steps/2/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic block mirror descent -/
theorem proxObjective_exists_isMinOn_compact
    {P E : Type*} [TopologicalSpace P] [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    {V : P → P → ℝ} {eval : P → E}
    (hcompact : IsCompact (Set.univ : Set P))
    (heval : Continuous eval) (x : P)
    (hVx : Continuous (fun u : P => V x u)) (g : E) (γ : ℝ) :
    ∃ y : P, IsMinOn (SOptLib.proxObjective V (fun _ : P => 0) eval x g γ) Set.univ y := by
  have hobjective :
      Continuous (SOptLib.proxObjective V (fun _ : P => 0) eval x g γ) := by
    have hinner : Continuous (fun u : P => ⟪g, eval u⟫_ℝ) :=
      continuous_const.inner heval
    have hprox : Continuous (fun u : P => γ⁻¹ * V x u) :=
      continuous_const.mul hVx
    have hzero : Continuous (fun _ : P => (0 : ℝ)) :=
      continuous_const
    simpa [SOptLib.proxObjective] using (hinner.add hprox).add hzero
  rcases hcompact.exists_isMinOn
      (⟨x, trivial⟩ : (Set.univ : Set P).Nonempty)
      hobjective.continuousOn with
    ⟨y, _hy, hymin⟩
  exact ⟨y, hymin⟩

/-- Constrained composite prox-step predicate for a parameterized objective.

`IsCompositeProxStepOn X proxObjective t xPrev xUnder g z` says that the
selected point `z` is feasible for `X` and minimizes the composite prox
objective determined by the current parameter, previous point, search point,
and oracle vector over that same feasible set.

Layer: Model | Concept: Prox
Proof: (definitional construction; constrained composite prox-step predicate
  combining feasibility with an `IsMinOn` certificate for the parameterized
  prox objective)
Source: Mathlib order argmin predicates for real-valued objective minimization
  over sets
Used in: accelerated stochastic approximation composite prox update contract
Book citation: book/FOML/StochasticAcceleratedGradientDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, accelerated stochastic approximation -/
def IsCompositeProxStepOn
    {T E : Type*} (X : Set E) (proxObjective : T → E → E → E → E → ℝ)
    (t : T) (xPrev xUnder g z : E) : Prop :=
  z ∈ X ∧ IsMinOn (proxObjective t xPrev xUnder g) X z

/-- Accelerated composite prox objective with a linear oracle term, a simple
additive term, and two Bregman-like regularizers.

For an abstract candidate type `P`, evaluation map `eval : P → E`, divergence
`V`, and simple term `h`, this names the subproblem objective
`x ↦ γ_t (⟪g, eval x⟫ + h x + μ V xUnder x) + V xPrev x`.

Layer: Model | Concept: Prox
Proof: (definitional construction; accelerated two-center composite prox
  objective combining a weighted linearized composite model and previous-point
  regularization)
Source: accelerated stochastic approximation prox subproblems and Mathlib real
  inner-product notation
Used in: accelerated stochastic gradient descent composite prox update before
  applying the prox three-point descent inequality
Book citation: book/FOML/StochasticAcceleratedGradientDescent.json#/algorithm_spec/steps/1/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic accelerated gradient descent -/
noncomputable def acceleratedCompositeProxObjective
    {T P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (gamma : T → ℝ) (mu : ℝ) (h : P → ℝ) (V : P → P → ℝ) (eval : P → E)
    (t : T) (xPrev xUnder : P) (g : E) (x : P) : ℝ :=
  gamma t * (⟪g, eval x⟫_ℝ + h x + mu * V xUnder x) + V xPrev x

/-- The accelerated composite prox objective unfolds to its two-center formula.

Layer: Model | Gap: Level 0 (accelerated composite prox objective unfolding)
Proof: by rfl after unfolding `acceleratedCompositeProxObjective`.
Source: accelerated stochastic approximation prox subproblems and Mathlib real
  inner-product notation
Used in: accelerated stochastic gradient descent rewriting of the prox update
  objective into the Lemma 3.5 two-regularizer form
Book citation: book/FOML/StochasticAcceleratedGradientDescent.json#/algorithm_spec/steps/1/math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic accelerated gradient descent -/
@[simp]
theorem acceleratedCompositeProxObjective_def
    {T P E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    (gamma : T → ℝ) (mu : ℝ) (h : P → ℝ) (V : P → P → ℝ) (eval : P → E)
    (t : T) (xPrev xUnder : P) (g : E) (x : P) :
    acceleratedCompositeProxObjective gamma mu h V eval t xPrev xUnder g x =
      gamma t * (⟪g, eval x⟫_ℝ + h x + mu * V xUnder x) + V xPrev x := by
  rfl

end SOptLib
