-- Release verification entry: import every module in the frozen library.
import SOptLib
import SOptLib.Analysis.BregmanFromCocoercivity
import SOptLib.Analysis.ConvexSmoothExtension
import SOptLib.Analysis.OpenCocoercivity
import SOptLib.Axioms.BaillonHaddad
import SOptLib.Glue.Algebra
import SOptLib.Glue.Analysis
import SOptLib.Glue.Calculus
import SOptLib.Glue.Martingale
import SOptLib.Glue.Probability
import SOptLib.Layer0.ConditionalGradient
import SOptLib.Layer0.ConvexFOC
import SOptLib.Layer0.Objective
import SOptLib.Layer0.Oracle
import SOptLib.Layer0.Subgradient
import SOptLib.Layer1.Complexity
import SOptLib.Layer1.Descent
import SOptLib.Layer1.Proximal
import SOptLib.Layer1.Telescope
import SOptLib.Model.BlockSampling
import SOptLib.Model.Bregman
import SOptLib.Model.Budget
import SOptLib.Model.Carrier
import SOptLib.Model.Complexity
import SOptLib.Model.ConditionalExpectation
import SOptLib.Model.ConditionalGradient
import SOptLib.Model.Diameter
import SOptLib.Model.Fenchel
import SOptLib.Model.Filtration
import SOptLib.Model.IsSimpleConvexTermOn
import SOptLib.Model.Iterates
import SOptLib.Model.Norms
import SOptLib.Model.Objective
import SOptLib.Model.ParameterChoices
import SOptLib.Model.Prox
import SOptLib.Model.Saddle
import SOptLib.Model.Selection
import SOptLib.Model.SimpleConvexTermExpr
import SOptLib.Model.Stationarity
import SOptLib.Model.StochasticOracle
import SOptLib.Model.Subdifferential
import SOptLib.Model.TailBounds
import SOptLib.Model.TailProbability
import SOptLib.Model.Validation
