import Mathlib.Algebra.BigOperators.Intervals
import Mathlib.Probability.Process.Adapted
import SOptLib.Model.BlockSampling

open MeasureTheory ProbabilityTheory

namespace SOptLib

open MeasureTheory ProbabilityTheory


/-- Natural filtration generated by the prefix of a measurable sample stream.

Layer: Model | Concept: Filtration
Proof: (definitional construction; sample-prefix-generated filtration on a stochastic stream)
Source: Mathlib filtration and generated sigma-algebra primitives
Used in: stochastic mirror descent sample filtration
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan stochastic mirror descent -/
noncomputable def filtration
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (ξ : ℕ → Ω → S)
    (hξ_measurable : ∀ n, Measurable (ξ n)) :
    Filtration ℕ (by infer_instance : MeasurableSpace Ω) where
  seq t := ⨆ j < t, MeasurableSpace.comap (ξ j)
    (by infer_instance : MeasurableSpace S)
  mono' _ _ hij := iSup₂_mono' fun j hj => ⟨j, lt_of_lt_of_le hj hij, le_rfl⟩
  le' t := iSup₂_le fun j _ => (hξ_measurable j).comap_le

/-- Defining equation for the sample-prefix filtration.

Layer: Model | Gap: Level 0 (generated filtration field equation)
Proof: projection reduction
Source: Mathlib filtration and generated sigma-algebra primitives
Used in: stochastic mirror descent sample filtration
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan stochastic mirror descent -/
@[simp]
theorem filtration_seq
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (ξ : ℕ → Ω → S)
    (hξ_measurable : ∀ n, Measurable (ξ n)) (t : ℕ) :
    (filtration ξ hξ_measurable).seq t =
      ⨆ j < t, MeasurableSpace.comap (ξ j)
        (by infer_instance : MeasurableSpace S) := by
  rfl

/-- A sample coordinate is measurable with respect to the generated prefix filtration
as soon as that prefix contains the coordinate.

Layer: Model | Gap: Level 0 (sample measurability in generated prefix filtration)
Proof: rewrite measurability as a `comap`-subspace inequality and include the
  coordinate generator into the finite prefix `iSup` using `le_iSup_of_le`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: stochastic mirror descent proof that the sampled noise at step `s` is
  measurable with respect to the prefix filtration generated by past samples
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
theorem measurable_sample_le_prefixFiltration
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (ξ : ℕ → Ω → S)
    (hξ : ∀ n, Measurable (ξ n))
    (n : ℕ) :
    Measurable[(SOptLib.filtration ξ hξ).seq (n + 1)] (ξ n) := by
  refine Measurable.of_comap_le ?_
  change
    MeasurableSpace.comap (ξ n) (by infer_instance : MeasurableSpace S) ≤
      ⨆ j < n + 1,
        MeasurableSpace.comap (ξ j) (by infer_instance : MeasurableSpace S)
  exact le_iSup_of_le n
    (le_iSup_of_le (Nat.lt_succ_self n) le_rfl)

/-- Finite block of all mini-batch sample coordinates before a strict time cutoff.

For a batch-size schedule, a run identifier, and a paper time `k`, this is the
finite set of triples `(run, t, r)` with `1 ≤ t ≤ k - 1` and
`1 ≤ r ≤ batchSize t`.

Layer: Model | Concept: Filtration
Proof: (definitional construction; finite bi-union of mini-batch coordinate intervals)
Source: Mathlib finite sets, interval finsets, and image/bi-union APIs
Used in: nonconvex stochastic mirror descent strict-past sample filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, nonconvex stochastic mirror descent -/
noncomputable def strictPastMiniBatchSampleBlock
    (batchSize : ℕ → ℕ) (run : ℕ) (k : ℕ) : Finset (ℕ × ℕ × ℕ) :=
  (Finset.Icc 1 (k - 1)).biUnion
    (fun t => (Finset.Icc 1 (batchSize t)).image (fun r => (run, t, r)))

/-- Membership in the strict-past mini-batch block is exactly the coordinate bounds.

The finite block contains precisely the samples from the selected run whose
paper time is between `1` and `k - 1`, and whose mini-batch coordinate is within
the batch size at that time.

Layer: Model | Gap: Level 0 (strict-past mini-batch block membership)
Proof: unfold the finite block, split `biUnion` and `image` membership, and
  repackage the interval bounds on the time and mini-batch coordinate.
Source: Mathlib finite sets, interval membership, and product-coordinate APIs
Used in: nonconvex stochastic mirror descent strict-past sample filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, nonconvex stochastic mirror descent -/
@[simp]
theorem mem_strictPastMiniBatchSampleBlock
    (batchSize : ℕ → ℕ) (run : ℕ) (k : ℕ) (q : ℕ × ℕ × ℕ) :
    q ∈ strictPastMiniBatchSampleBlock batchSize run k ↔
      q.1 = run ∧ 1 ≤ q.2.1 ∧ q.2.1 ≤ k - 1 ∧
        1 ≤ q.2.2 ∧ q.2.2 ≤ batchSize q.2.1 := by
  classical
  unfold strictPastMiniBatchSampleBlock
  constructor
  · intro hq
    rcases Finset.mem_biUnion.mp hq with ⟨t, ht, hqt⟩
    rcases Finset.mem_image.mp hqt with ⟨r, hr, rfl⟩
    simp only [Finset.mem_Icc] at ht hr
    exact ⟨rfl, ht.1, ht.2, hr.1, hr.2⟩
  · rintro ⟨hq₁, hqt₁, hqt₂, hqr₁, hqr₂⟩
    apply Finset.mem_biUnion.mpr
    refine ⟨q.2.1, ?_, ?_⟩
    · exact Finset.mem_Icc.mpr ⟨hqt₁, hqt₂⟩
    · apply Finset.mem_image.mpr
      refine ⟨q.2.2, Finset.mem_Icc.mpr ⟨hqr₁, hqr₂⟩, ?_⟩
      cases q
      simp_all

/-- Finite optimization sample block up to a stopping time for one run.

For a batch-size schedule, a run identifier, and a stopping time `R`, this is
the finite set of triples `(run, k, i)` with `1 ≤ k ≤ R` and
`1 ≤ i ≤ batchSize k`.

Layer: Model | Concept: Filtration
Proof: (definitional construction; finite bi-union of stopping-time mini-batch coordinate intervals)
Source: Mathlib finite sets, interval finsets, and image/bi-union APIs
Used in: nonconvex stochastic mirror descent randomized-output optimization sample footprint
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, nonconvex stochastic mirror descent -/
noncomputable def finiteOptimizationSampleBlock
    (batchSize : ℕ → ℕ) (run : ℕ) (stop : ℕ) : Finset (ℕ × ℕ × ℕ) :=
  (Finset.Icc 1 stop).biUnion
    (fun k => (Finset.Icc 1 (batchSize k)).image (fun i => (run, k, i)))

/-- Membership in an optimization sample block is exactly its run, time, and mini-batch bounds.

The finite block contains precisely the samples from the selected run whose
optimization time is between `1` and the stopping time, and whose mini-batch
coordinate is within the batch-size schedule at that time.

Layer: Model | Gap: Level 0 (stopped optimization sample block membership)
Proof: unfold the finite block, split `biUnion` and `image` membership, and
  repackage the interval bounds on the time and mini-batch coordinate.
Source: Mathlib finite sets, interval membership, and product-coordinate APIs
Used in: nonconvex stochastic mirror descent randomized-output sample block disjointness for validation independence
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, nonconvex stochastic mirror descent -/
@[simp]
theorem mem_finiteOptimizationSampleBlock
    (batchSize : ℕ → ℕ) (run stop : ℕ) (q : ℕ × ℕ × ℕ) :
    q ∈ finiteOptimizationSampleBlock batchSize run stop ↔
      q.1 = run ∧ 1 ≤ q.2.1 ∧ q.2.1 ≤ stop ∧
        1 ≤ q.2.2 ∧ q.2.2 ≤ batchSize q.2.1 := by
  classical
  unfold finiteOptimizationSampleBlock
  constructor
  · intro hq
    rcases Finset.mem_biUnion.mp hq with ⟨k, hk, hqk⟩
    rcases Finset.mem_image.mp hqk with ⟨i, hi, rfl⟩
    simp only [Finset.mem_Icc] at hk hi
    exact ⟨rfl, hk.1, hk.2, hi.1, hi.2⟩
  · rintro ⟨hq₁, hqk₁, hqk₂, hqi₁, hqi₂⟩
    apply Finset.mem_biUnion.mpr
    refine ⟨q.2.1, ?_, ?_⟩
    · exact Finset.mem_Icc.mpr ⟨hqk₁, hqk₂⟩
    · apply Finset.mem_image.mpr
      refine ⟨q.2.2, Finset.mem_Icc.mpr ⟨hqi₁, hqi₂⟩, ?_⟩
      cases q
      simp_all

/-- Sigma-algebra generated by a finite block of sample coordinates.

For an abstract sample family indexed by `I`, this is the measurable space on
the base probability space generated by the finitely many coordinates listed in
`block`.

Layer: Model | Concept: Filtration
Proof: (definitional construction; finite indexed supremum of coordinate
  comap sigma-algebras)
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic mirror descent randomized-output validation
  freshness through its finite optimization sample footprint
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
@[reducible]
noncomputable def sampleBlockMeasurableSpace
    {Ω S I : Type*} [MeasurableSpace S]
    (ξ : I → Ω → S) (block : Finset I) : MeasurableSpace Ω :=
  ⨆ q : {q // q ∈ block},
    MeasurableSpace.comap (fun ω => ξ q.1 ω)
      (by infer_instance : MeasurableSpace S)

/-- Sigma-algebra generated by a finite block of sample coordinates.

For a sample stream `ξ`, an index flattener `idx`, and a finite coordinate
block, this names the measurable space generated by all coordinates in the
block.

Layer: Model | Concept: Filtration
Proof: (definitional construction; finite indexed supremum of coordinate
  comap sigma-algebras)
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic mirror descent strict-past mini-batch sample
  filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
@[reducible]
noncomputable def strictPastSampleBlockMeasurableSpace
    {Ω Ξ : Type*} [MeasurableSpace Ξ]
    (ξ : ℕ → Ω → Ξ) (idx : ℕ × ℕ × ℕ → ℕ)
    (block : Finset (ℕ × ℕ × ℕ)) : MeasurableSpace Ω :=
  ⨆ q : {q // q ∈ block},
    MeasurableSpace.comap (fun ω => ξ (idx q.1) ω)
      (by infer_instance : MeasurableSpace Ξ)

/-- A coordinate in a finite sample block is measurable for the sigma-algebra
generated by that block.

For a sample stream `ξ`, an abstract coordinate indexer `idx`, and a finite
block of coordinates, the selected coordinate is one of the generators in the
finite-block supremum.

Layer: Model | Gap: Level 0 (sample-coordinate measurability in generated finite block filtration)
Proof: rewrite measurability as a `comap`-subspace inequality and include the
  selected coordinate generator into the indexed supremum with `le_iSup`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic mirror descent strict-past mini-batch sample
  filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
theorem sampleBlock_coordinate_measurable
    {Ω Ξ β : Type*} [MeasurableSpace Ξ]
    (ξ : ℕ → Ω → Ξ) (idx : β → ℕ) (block : Finset β)
    {q : β} (hq : q ∈ block) :
    Measurable[
      ⨆ q' : {q // q ∈ block},
        MeasurableSpace.comap (fun ω => ξ (idx q'.1) ω)
          (by infer_instance : MeasurableSpace Ξ)]
      (fun ω => ξ (idx q) ω) := by
  exact measurable_iff_comap_le.mpr (by
    simpa using
      le_iSup
        (fun q' : {q // q ∈ block} =>
          MeasurableSpace.comap (fun ω => ξ (idx q'.1) ω)
            (by infer_instance : MeasurableSpace Ξ))
        ⟨q, hq⟩)

/-- Every coordinate in a finite sample block is measurable for the sigma-algebra generated by that block.

The coordinate subspace appears as one generator in the finite-block supremum,
so measurability follows by the universal order characterization of `comap`.

Layer: Model | Gap: Level 0 (sample-coordinate measurability in generated block filtration)
Proof: rewrite measurability as a `comap`-subspace inequality and include the
  selected coordinate generator into the indexed supremum with `le_iSup`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic mirror descent strict-past mini-batch sample
  filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
theorem strictPastSampleBlockMeasurableSpace_coordinate_measurable
    {Ω Ξ : Type*} [MeasurableSpace Ξ]
    (ξ : ℕ → Ω → Ξ) (idx : ℕ × ℕ × ℕ → ℕ)
    (block : Finset (ℕ × ℕ × ℕ)) {q : ℕ × ℕ × ℕ}
    (hq : q ∈ block) :
    Measurable[strictPastSampleBlockMeasurableSpace ξ idx block]
      (fun ω => ξ (idx q) ω) := by
  unfold strictPastSampleBlockMeasurableSpace
  exact sampleBlock_coordinate_measurable ξ idx block hq

/-- A sample coordinate is measurable with respect to any generated prefix
filtration whose strict cutoff contains that coordinate.

Layer: Model | Gap: Level 0 (strict-prefix sample-coordinate measurability)
Proof: rewrite measurability as a `comap`-subspace inequality, unfold the
  generated prefix filtration, and include the coordinate generator into the
  strict prefix `iSup` using the hypothesis `i < n`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: stochastic conditional-gradient and mirror-descent proofs that a
  previously drawn sample coordinate is measurable with respect to the strict
  sample-history filtration before conditioning on a fresh sample
Book citation: book/FOML/StochasticNonconvexConditionalGradient.json#/algorithm_spec/steps/0
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic nonconvex conditional gradient -/
theorem measurable_sample_of_lt_prefixFiltration
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (ξ : ℕ → Ω → S) (hξ : ∀ n, Measurable (ξ n))
    {n i : ℕ} (hi : i < n) :
    Measurable[(SOptLib.filtration ξ hξ).seq n] (ξ i) := by
  refine Measurable.of_comap_le ?_
  unfold SOptLib.filtration
  exact le_iSup_of_le i (le_iSup_of_le hi le_rfl)

/-- A finite sample-block sigma-algebra generated by measurable coordinates is
below the ambient measurable space.

For an abstract sample family indexed by `I`, if every coordinate in a finite
block is measurable for the ambient measurable space on `Omega`, then the
finite-block measurable space generated by that `Finset I` is a sub-sigma-
algebra of the ambient space.

Layer: Model | Gap: Level 0 (finite sample-block ambient sub-sigma-algebra)
Proof: unfold the finite-block sigma-algebra as an indexed supremum of coordinate
  comaps, then bound each generator by ambient measurability and close by
  `iSup_le`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: stochastic conditional-gradient finite sample-block measurability and
  stochastic mirror descent finite mini-batch history measurability
Book citation: book/FOML/StochasticNonconvexConditionalGradient.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic nonconvex conditional gradient -/
theorem sampleBlockMeasurableSpace_le
    {Omega Xi I : Type*} [MeasurableSpace Omega] [MeasurableSpace Xi]
    (xi : I → Omega → Xi) (block : Finset I)
    (hxi : ∀ i, i ∈ block → Measurable (xi i)) :
    sampleBlockMeasurableSpace xi block ≤
      (by infer_instance : MeasurableSpace Omega) := by
  rw [sampleBlockMeasurableSpace]
  exact iSup_le fun q => (hxi q.1 q.2).comap_le

/-- Finite sample-block sigma-algebras are monotone in the coordinate block.

If every coordinate index in `A` is also in `B`, then the sigma-algebra generated
by the sample coordinates in `A` is below the sigma-algebra generated by the
coordinates in `B`.

Layer: Model | Gap: Level 0 (finite sample-block filtration monotonicity)
Proof: unfold `sampleBlockMeasurableSpace` and include each generator from the
  smaller subtype-indexed supremum into the larger one using the block inclusion.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic conditional gradient enlargement of finite sample
  footprints for iterate and oracle-estimator measurability
Book citation: book/FOML/NonconvexStochasticConditionalGradient.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic nonconvex conditional gradient -/
theorem sampleBlockMeasurableSpace_mono
    {Ω Ξ I : Type*} [MeasurableSpace Ξ]
    (ξ : I → Ω → Ξ) {A B : Finset I} (hAB : A ⊆ B) :
    sampleBlockMeasurableSpace ξ A ≤ sampleBlockMeasurableSpace ξ B := by
  classical
  rw [sampleBlockMeasurableSpace, sampleBlockMeasurableSpace]
  exact iSup_le (fun q =>
    le_iSup_of_le (⟨q.1, hAB q.2⟩ : {q // q ∈ B}) le_rfl)

/-- A finite sample-block sigma-algebra is below the sigma-algebra generated by
any containing set of coordinate sigma-algebras.

If every coordinate index in the finite block lies in `s`, then the sigma-
algebra generated by that finite block is below the `iSup` over the coordinate
sigma-algebras indexed by `s`.

Layer: Model | Gap: Level 0 (finite sample-block to set-indexed filtration inclusion)
Proof: unfold `sampleBlockMeasurableSpace`, then include each subtype-indexed
  finite-block generator into the set-indexed `iSup` using the supplied
  membership inclusion.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex variance-reduced mirror descent strict-past mini-batch
  sample filtration for iterate measurability
Book citation: book/FOML/NonconvexVarianceReducedMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex variance-reduced mirror descent -/
theorem sampleBlockMeasurableSpace_le_iSup_of_subset
    {Ω Ξ I : Type*} [MeasurableSpace Ξ]
    (ξ : I → Ω → Ξ) (block : Finset I) {s : Set I}
    (hblock : ↑block ⊆ s) :
    sampleBlockMeasurableSpace ξ block ≤
      ⨆ i ∈ s,
        MeasurableSpace.comap (ξ i) (by infer_instance : MeasurableSpace Ξ) := by
  rw [sampleBlockMeasurableSpace]
  exact iSup_le fun q =>
    le_iSup_of_le q.1 (le_iSup_of_le (hblock q.2) le_rfl)

/-- The one-based finite prefix vector of a measurable stream is measurable
with respect to the generated strict prefix filtration.

For a stream `ξ : ℕ → Ω → S`, the map sending `ω` to the dependent function
`r ↦ ξ (r - 1) ω` on `{r // 1 ≤ r ∧ r ≤ k}` is measurable with respect to the
filtration generated by the zero-based coordinates before `k`.

Layer: Model | Gap: Level 1 (one-based finite prefix measurability)
Proof: reduce dependent-product measurability to coordinate measurability with
  `measurable_pi_lambda`, then apply the generated prefix-filtration coordinate
  lemma to each coordinate `r - 1 < k`.
Source: Mathlib measurable-space product measurability and generated
  filtration coordinate APIs
Used in: random primal-dual gradient conditioning on the finite sampled block
  history before taking a fresh block expectation
Book citation: book/FOML/RandomPrimalDualGradient.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, random primal-dual gradient -/
theorem measurable_one_based_prefix_of_prefix_filtration
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (ξ : ℕ → Ω → S) (hξ : ∀ n, Measurable (ξ n)) (k : ℕ) :
    Measurable[(SOptLib.filtration ξ hξ).seq k]
      (fun ω : Ω => fun r : {r : ℕ // 1 ≤ r ∧ r ≤ k} => ξ (r.1 - 1) ω) := by
  classical
  refine @measurable_pi_lambda
    Ω
    {r : ℕ // 1 ≤ r ∧ r ≤ k}
    (fun _ : {r : ℕ // 1 ≤ r ∧ r ≤ k} => S)
    ((SOptLib.filtration ξ hξ).seq k)
    (fun _ => by infer_instance)
    (fun ω r => ξ (r.1 - 1) ω)
    ?_
  intro r
  have hlt : r.1 - 1 < k := by
    omega
  exact SOptLib.measurable_sample_of_lt_prefixFiltration ξ hξ hlt

end SOptLib

-- Merged from Staging/sampleWindowMeasurableSpace_eq_comap.lean
open MeasureTheory

namespace SOptLib

-- Generalization plan (G0):
-- concept/name: sample-window generated sigma-algebra as a comap; orig was
--   `paperStrictPastSigma_eq_strictPastWindow_comap`, renamed to expose the
--   finite coordinate-window measurable-space identity rather than the paper
--   strict-past conditioning label.
-- generality used: arbitrary source type, arbitrary measurable sample type, and
--   an arbitrary Nat-indexed sample stream; no probability measure,
--   independence, integrability, convexity, smoothness, or algorithm-state
--   assumptions are used.
-- portable call pattern: finite-memory stochastic proofs condition on a
--   generated sample history and then switch to a `Fin`-indexed sample window;
--   the sample stream, offset, and stopping time change while the
--   generated-sigma-algebra/comap conclusion stays the same.
-- counterargument checked: not merely paper traceability because the same
--   finite-window sigma-algebra identity is needed by iid freshness,
--   finite-window determinism, and conditional-expectation measurability
--   arguments; not a pure wrapper because it proves both directions of the
--   generated-coordinate/product-comap equality.
-- coverage search: searched `sampleWindow measurable space comap Fin iSup` in
--   SOptLib/Mathlib and LeanSearch for finite coordinate-window comap
--   identities. Mathlib `MeasureTheory.Filtration.piFinset_eq_comap_restrict`
--   covers restriction of an actual Pi-space by a `Finset`; SOptLib
--   `sampleBlockMeasurableSpace` and coordinate measurability lemmas cover
--   finite block generators, but none states this arbitrary-stream
--   half-open Nat-window equality against `SOptLib.sampleWindow`.
-- minimal hypotheses: all already minimal; the original concrete block path,
--   one-based lower bound, and paper strict-past name are replaced by an
--   arbitrary stream and half-open `[offset, stop)` Nat window.

/-- A half-open sample-window sigma-algebra is the comap of the finite sample window.

For any stream `xi`, the sigma-algebra generated by the coordinates with
`offset <= j < stop` is exactly the pullback sigma-algebra of the
`Fin (stop - offset)` window `sampleWindow xi offset (stop - offset)`.

Layer: Model | Gap: Level 1 (sample-window sigma-algebra comap identity)
Proof: prove both inclusions. Each scalar coordinate is a product-coordinate
  projection of the finite window, and the finite window is measurable because
  all of its coordinates are among the half-open generated coordinates.
Source: Mathlib measurable-space comap, Pi-product measurability, and complete
  lattice APIs
Used in: randomized gradient extrapolation conditioning on a strict finite
  sampled-block history before applying a fresh-block law
Book citation: book/FOML/RandomGradientExtrapolation.json#/key_lemmas/3/statement_math
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, randomized gradient extrapolation method -/
theorem sampleWindowMeasurableSpace_eq_comap
    {Ω Sample : Type*} [MeasurableSpace Sample]
    (xi : ℕ → Ω → Sample) (offset stop : ℕ) :
    (⨆ (j : ℕ) (_hj : offset ≤ j ∧ j < stop),
        MeasurableSpace.comap (xi j)
          (by infer_instance : MeasurableSpace Sample)) =
      MeasurableSpace.comap
        (SOptLib.sampleWindow xi offset (stop - offset))
        (by infer_instance : MeasurableSpace (Fin (stop - offset) → Sample)) := by
  classical
  let past : MeasurableSpace Ω :=
    ⨆ (j : ℕ) (_hj : offset ≤ j ∧ j < stop),
      MeasurableSpace.comap (xi j)
        (by infer_instance : MeasurableSpace Sample)
  let K : Ω → Fin (stop - offset) → Sample :=
    SOptLib.sampleWindow xi offset (stop - offset)
  have hleft : past ≤ MeasurableSpace.comap K inferInstance := by
    dsimp [past]
    refine iSup_le ?_
    intro j
    refine iSup_le ?_
    intro hj
    let r : Fin (stop - offset) := ⟨j - offset, by omega⟩
    have hK_meas : Measurable[MeasurableSpace.comap K inferInstance] K :=
      Measurable.of_comap_le le_rfl
    have hcoord_meas : Measurable[MeasurableSpace.comap K inferInstance]
        (fun ω : Ω => K ω r) :=
      (measurable_pi_apply r).comp hK_meas
    have hidx : offset + (j - offset) = j := by omega
    simpa [K, SOptLib.sampleWindow, r, hidx] using hcoord_meas.comap_le
  have hright : MeasurableSpace.comap K inferInstance ≤ past := by
    have hK_past : @Measurable Ω (Fin (stop - offset) → Sample)
        past inferInstance K := by
      letI : MeasurableSpace Ω := past
      change Measurable K
      refine measurable_pi_lambda (f := K) ?_
      intro r
      refine Measurable.of_comap_le ?_
      have hj : offset ≤ offset + r.1 ∧ offset + r.1 < stop := by
        constructor <;> omega
      simpa [past, K, SOptLib.sampleWindow] using
        (le_iSup_of_le (offset + r.1) (le_iSup_of_le hj le_rfl) :
          MeasurableSpace.comap (xi (offset + r.1))
            (by infer_instance : MeasurableSpace Sample) ≤
            ⨆ (j : ℕ) (_hj : offset ≤ j ∧ j < stop),
              MeasurableSpace.comap (xi j)
                (by infer_instance : MeasurableSpace Sample))
    exact hK_past.comap_le
  exact le_antisymm hleft hright

/-- A function has a representative measurable for a chosen sigma-algebra, up to
almost-everywhere equality under an ambient measure.

Layer: Model | Concept: law-scoped measurable representative for a sub-sigma-algebra
Proof: (definitional construction; existentially package a source-measurable representative and ambient-measure almost-everywhere equality)
Source: Mathlib `Measurable` with an explicit source sigma-algebra and `Filter.EventuallyEq` under a measure's almost-everywhere filter
Used in: adapted stochastic-process arguments whose law supplies measurable versions without global off-stream kernel measurability
Book citation: book/STORM/StochasticRecursiveMomentum.json#/key_lemmas/1
Origin algorithm: Cutkosky and Orabona, Momentum-Based Variance Reduction in Non-Convex SGD, STOchastic Recursive Momentum (STORM) -/
def HasAEMeasurableRepresentative
    {Ω β : Type*} [mΩ : MeasurableSpace Ω] [MeasurableSpace β]
    (m : MeasurableSpace Ω) (f : Ω → β) (μ : @Measure Ω mΩ) : Prop :=
  ∃ f' : Ω → β, Measurable[m] f' ∧ f =ᵐ[μ] f'

end SOptLib
