import Mathlib.Algebra.BigOperators.Intervals
import Mathlib.Probability.Process.Adapted

open MeasureTheory ProbabilityTheory

namespace SOptLib

open MeasureTheory ProbabilityTheory


/-- Natural filtration generated by the prefix of a measurable sample stream.

Layer: Model | Concept: Filtration
Proof: (definitional construction; sample-prefix-generated filtration on a stochastic stream)
Source: Mathlib filtration and generated sigma-algebra primitives
Used in: stochastic mirror descent sample filtration
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan stochastic mirror descent -/
noncomputable def filtration
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (ξ : ℕ → Ω → S)
    (hξ_measurable : ∀ n, Measurable (ξ n)) :
    Filtration ℕ (by infer_instance : MeasurableSpace Ω) where
  seq t := ⨆ j < t, MeasurableSpace.comap (ξ j)
    (by infer_instance : MeasurableSpace S)
  mono' _ _ hij := iSup₂_mono' fun j hj => ⟨j, lt_of_lt_of_le hj hij, le_rfl⟩
  le' t := iSup₂_le fun j _ => (hξ_measurable j).comap_le

/-- Defining equation for the sample-prefix filtration.

Layer: Model | Gap: Level 0 (generated filtration field equation)
Proof: projection reduction
Source: Mathlib filtration and generated sigma-algebra primitives
Used in: stochastic mirror descent sample filtration
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan stochastic mirror descent -/
@[simp]
theorem filtration_seq
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (ξ : ℕ → Ω → S)
    (hξ_measurable : ∀ n, Measurable (ξ n)) (t : ℕ) :
    (filtration ξ hξ_measurable).seq t =
      ⨆ j < t, MeasurableSpace.comap (ξ j)
        (by infer_instance : MeasurableSpace S) := by
  rfl

/-- A sample coordinate is measurable with respect to the generated prefix filtration
as soon as that prefix contains the coordinate.

Layer: Model | Gap: Level 0 (sample measurability in generated prefix filtration)
Proof: rewrite measurability as a `comap`-subspace inequality and include the
  coordinate generator into the finite prefix `iSup` using `le_iSup_of_le`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: stochastic mirror descent proof that the sampled noise at step `s` is
  measurable with respect to the prefix filtration generated by past samples
Book citation: book/FOML/StochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, stochastic mirror descent -/
theorem measurable_sample_le_prefixFiltration
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (ξ : ℕ → Ω → S)
    (hξ : ∀ n, Measurable (ξ n))
    (n : ℕ) :
    Measurable[(SOptLib.filtration ξ hξ).seq (n + 1)] (ξ n) := by
  refine Measurable.of_comap_le ?_
  change
    MeasurableSpace.comap (ξ n) (by infer_instance : MeasurableSpace S) ≤
      ⨆ j < n + 1,
        MeasurableSpace.comap (ξ j) (by infer_instance : MeasurableSpace S)
  exact le_iSup_of_le n
    (le_iSup_of_le (Nat.lt_succ_self n) le_rfl)

/-- Finite block of all mini-batch sample coordinates before a strict time cutoff.

For a batch-size schedule, a run identifier, and a paper time `k`, this is the
finite set of triples `(run, t, r)` with `1 ≤ t ≤ k - 1` and
`1 ≤ r ≤ batchSize t`.

Layer: Model | Concept: Filtration
Proof: (definitional construction; finite bi-union of mini-batch coordinate intervals)
Source: Mathlib finite sets, interval finsets, and image/bi-union APIs
Used in: nonconvex stochastic mirror descent strict-past sample filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, nonconvex stochastic mirror descent -/
noncomputable def strictPastMiniBatchSampleBlock
    (batchSize : ℕ → ℕ) (run : ℕ) (k : ℕ) : Finset (ℕ × ℕ × ℕ) :=
  (Finset.Icc 1 (k - 1)).biUnion
    (fun t => (Finset.Icc 1 (batchSize t)).image (fun r => (run, t, r)))

/-- Membership in the strict-past mini-batch block is exactly the coordinate bounds.

The finite block contains precisely the samples from the selected run whose
paper time is between `1` and `k - 1`, and whose mini-batch coordinate is within
the batch size at that time.

Layer: Model | Gap: Level 0 (strict-past mini-batch block membership)
Proof: unfold the finite block, split `biUnion` and `image` membership, and
  repackage the interval bounds on the time and mini-batch coordinate.
Source: Mathlib finite sets, interval membership, and product-coordinate APIs
Used in: nonconvex stochastic mirror descent strict-past sample filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, nonconvex stochastic mirror descent -/
@[simp]
theorem mem_strictPastMiniBatchSampleBlock
    (batchSize : ℕ → ℕ) (run : ℕ) (k : ℕ) (q : ℕ × ℕ × ℕ) :
    q ∈ strictPastMiniBatchSampleBlock batchSize run k ↔
      q.1 = run ∧ 1 ≤ q.2.1 ∧ q.2.1 ≤ k - 1 ∧
        1 ≤ q.2.2 ∧ q.2.2 ≤ batchSize q.2.1 := by
  classical
  unfold strictPastMiniBatchSampleBlock
  constructor
  · intro hq
    rcases Finset.mem_biUnion.mp hq with ⟨t, ht, hqt⟩
    rcases Finset.mem_image.mp hqt with ⟨r, hr, rfl⟩
    simp only [Finset.mem_Icc] at ht hr
    exact ⟨rfl, ht.1, ht.2, hr.1, hr.2⟩
  · rintro ⟨hq₁, hqt₁, hqt₂, hqr₁, hqr₂⟩
    apply Finset.mem_biUnion.mpr
    refine ⟨q.2.1, ?_, ?_⟩
    · exact Finset.mem_Icc.mpr ⟨hqt₁, hqt₂⟩
    · apply Finset.mem_image.mpr
      refine ⟨q.2.2, Finset.mem_Icc.mpr ⟨hqr₁, hqr₂⟩, ?_⟩
      cases q
      simp_all

/-- Finite optimization sample block up to a stopping time for one run.

For a batch-size schedule, a run identifier, and a stopping time `R`, this is
the finite set of triples `(run, k, i)` with `1 ≤ k ≤ R` and
`1 ≤ i ≤ batchSize k`.

Layer: Model | Concept: Filtration
Proof: (definitional construction; finite bi-union of stopping-time mini-batch coordinate intervals)
Source: Mathlib finite sets, interval finsets, and image/bi-union APIs
Used in: nonconvex stochastic mirror descent randomized-output optimization sample footprint
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, nonconvex stochastic mirror descent -/
noncomputable def finiteOptimizationSampleBlock
    (batchSize : ℕ → ℕ) (run : ℕ) (stop : ℕ) : Finset (ℕ × ℕ × ℕ) :=
  (Finset.Icc 1 stop).biUnion
    (fun k => (Finset.Icc 1 (batchSize k)).image (fun i => (run, k, i)))

/-- Membership in an optimization sample block is exactly its run, time, and mini-batch bounds.

The finite block contains precisely the samples from the selected run whose
optimization time is between `1` and the stopping time, and whose mini-batch
coordinate is within the batch-size schedule at that time.

Layer: Model | Gap: Level 0 (stopped optimization sample block membership)
Proof: unfold the finite block, split `biUnion` and `image` membership, and
  repackage the interval bounds on the time and mini-batch coordinate.
Source: Mathlib finite sets, interval membership, and product-coordinate APIs
Used in: nonconvex stochastic mirror descent randomized-output sample block disjointness for validation independence
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for Machine Learning, nonconvex stochastic mirror descent -/
@[simp]
theorem mem_finiteOptimizationSampleBlock
    (batchSize : ℕ → ℕ) (run stop : ℕ) (q : ℕ × ℕ × ℕ) :
    q ∈ finiteOptimizationSampleBlock batchSize run stop ↔
      q.1 = run ∧ 1 ≤ q.2.1 ∧ q.2.1 ≤ stop ∧
        1 ≤ q.2.2 ∧ q.2.2 ≤ batchSize q.2.1 := by
  classical
  unfold finiteOptimizationSampleBlock
  constructor
  · intro hq
    rcases Finset.mem_biUnion.mp hq with ⟨k, hk, hqk⟩
    rcases Finset.mem_image.mp hqk with ⟨i, hi, rfl⟩
    simp only [Finset.mem_Icc] at hk hi
    exact ⟨rfl, hk.1, hk.2, hi.1, hi.2⟩
  · rintro ⟨hq₁, hqk₁, hqk₂, hqi₁, hqi₂⟩
    apply Finset.mem_biUnion.mpr
    refine ⟨q.2.1, ?_, ?_⟩
    · exact Finset.mem_Icc.mpr ⟨hqk₁, hqk₂⟩
    · apply Finset.mem_image.mpr
      refine ⟨q.2.2, Finset.mem_Icc.mpr ⟨hqi₁, hqi₂⟩, ?_⟩
      cases q
      simp_all

/-- Sigma-algebra generated by a finite block of sample coordinates.

For an abstract sample family indexed by `I`, this is the measurable space on
the base probability space generated by the finitely many coordinates listed in
`block`.

Layer: Model | Concept: Filtration
Proof: (definitional construction; finite indexed supremum of coordinate
  comap sigma-algebras)
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic mirror descent randomized-output validation
  freshness through its finite optimization sample footprint
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
@[reducible]
noncomputable def sampleBlockMeasurableSpace
    {Ω S I : Type*} [MeasurableSpace S]
    (ξ : I → Ω → S) (block : Finset I) : MeasurableSpace Ω :=
  ⨆ q : {q // q ∈ block},
    MeasurableSpace.comap (fun ω => ξ q.1 ω)
      (by infer_instance : MeasurableSpace S)

/-- Sigma-algebra generated by a finite block of sample coordinates.

For a sample stream `ξ`, an index flattener `idx`, and a finite coordinate
block, this names the measurable space generated by all coordinates in the
block.

Layer: Model | Concept: Filtration
Proof: (definitional construction; finite indexed supremum of coordinate
  comap sigma-algebras)
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic mirror descent strict-past mini-batch sample
  filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
@[reducible]
noncomputable def strictPastSampleBlockMeasurableSpace
    {Ω Ξ : Type*} [MeasurableSpace Ξ]
    (ξ : ℕ → Ω → Ξ) (idx : ℕ × ℕ × ℕ → ℕ)
    (block : Finset (ℕ × ℕ × ℕ)) : MeasurableSpace Ω :=
  ⨆ q : {q // q ∈ block},
    MeasurableSpace.comap (fun ω => ξ (idx q.1) ω)
      (by infer_instance : MeasurableSpace Ξ)

/-- A coordinate in a finite sample block is measurable for the sigma-algebra
generated by that block.

For a sample stream `ξ`, an abstract coordinate indexer `idx`, and a finite
block of coordinates, the selected coordinate is one of the generators in the
finite-block supremum.

Layer: Model | Gap: Level 0 (sample-coordinate measurability in generated finite block filtration)
Proof: rewrite measurability as a `comap`-subspace inequality and include the
  selected coordinate generator into the indexed supremum with `le_iSup`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic mirror descent strict-past mini-batch sample
  filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
theorem sampleBlock_coordinate_measurable
    {Ω Ξ β : Type*} [MeasurableSpace Ξ]
    (ξ : ℕ → Ω → Ξ) (idx : β → ℕ) (block : Finset β)
    {q : β} (hq : q ∈ block) :
    Measurable[
      ⨆ q' : {q // q ∈ block},
        MeasurableSpace.comap (fun ω => ξ (idx q'.1) ω)
          (by infer_instance : MeasurableSpace Ξ)]
      (fun ω => ξ (idx q) ω) := by
  exact measurable_iff_comap_le.mpr (by
    simpa using
      le_iSup
        (fun q' : {q // q ∈ block} =>
          MeasurableSpace.comap (fun ω => ξ (idx q'.1) ω)
            (by infer_instance : MeasurableSpace Ξ))
        ⟨q, hq⟩)

/-- Every coordinate in a finite sample block is measurable for the sigma-algebra generated by that block.

The coordinate subspace appears as one generator in the finite-block supremum,
so measurability follows by the universal order characterization of `comap`.

Layer: Model | Gap: Level 0 (sample-coordinate measurability in generated block filtration)
Proof: rewrite measurability as a `comap`-subspace inequality and include the
  selected coordinate generator into the indexed supremum with `le_iSup`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic mirror descent strict-past mini-batch sample
  filtration for iterate measurability
Book citation: book/FOML/NonconvexStochasticMirrorDescent.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, nonconvex stochastic mirror descent -/
theorem strictPastSampleBlockMeasurableSpace_coordinate_measurable
    {Ω Ξ : Type*} [MeasurableSpace Ξ]
    (ξ : ℕ → Ω → Ξ) (idx : ℕ × ℕ × ℕ → ℕ)
    (block : Finset (ℕ × ℕ × ℕ)) {q : ℕ × ℕ × ℕ}
    (hq : q ∈ block) :
    Measurable[strictPastSampleBlockMeasurableSpace ξ idx block]
      (fun ω => ξ (idx q) ω) := by
  unfold strictPastSampleBlockMeasurableSpace
  exact sampleBlock_coordinate_measurable ξ idx block hq

/-- A sample coordinate is measurable with respect to any generated prefix
filtration whose strict cutoff contains that coordinate.

Layer: Model | Gap: Level 0 (strict-prefix sample-coordinate measurability)
Proof: rewrite measurability as a `comap`-subspace inequality, unfold the
  generated prefix filtration, and include the coordinate generator into the
  strict prefix `iSup` using the hypothesis `i < n`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: stochastic conditional-gradient and mirror-descent proofs that a
  previously drawn sample coordinate is measurable with respect to the strict
  sample-history filtration before conditioning on a fresh sample
Book citation: book/FOML/StochasticNonconvexConditionalGradient.json#/algorithm_spec/steps/0
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic nonconvex conditional gradient -/
theorem measurable_sample_of_lt_prefixFiltration
    {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (ξ : ℕ → Ω → S) (hξ : ∀ n, Measurable (ξ n))
    {n i : ℕ} (hi : i < n) :
    Measurable[(SOptLib.filtration ξ hξ).seq n] (ξ i) := by
  refine Measurable.of_comap_le ?_
  unfold SOptLib.filtration
  exact le_iSup_of_le i (le_iSup_of_le hi le_rfl)

/-- A finite sample-block sigma-algebra generated by measurable coordinates is
below the ambient measurable space.

For an abstract sample family indexed by `I`, if every coordinate in a finite
block is measurable for the ambient measurable space on `Omega`, then the
finite-block measurable space generated by that `Finset I` is a sub-sigma-
algebra of the ambient space.

Layer: Model | Gap: Level 0 (finite sample-block ambient sub-sigma-algebra)
Proof: unfold the finite-block sigma-algebra as an indexed supremum of coordinate
  comaps, then bound each generator by ambient measurability and close by
  `iSup_le`.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: stochastic conditional-gradient finite sample-block measurability and
  stochastic mirror descent finite mini-batch history measurability
Book citation: book/FOML/StochasticNonconvexConditionalGradient.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic nonconvex conditional gradient -/
theorem sampleBlockMeasurableSpace_le
    {Omega Xi I : Type*} [MeasurableSpace Omega] [MeasurableSpace Xi]
    (xi : I → Omega → Xi) (block : Finset I)
    (hxi : ∀ i, i ∈ block → Measurable (xi i)) :
    sampleBlockMeasurableSpace xi block ≤
      (by infer_instance : MeasurableSpace Omega) := by
  rw [sampleBlockMeasurableSpace]
  exact iSup_le fun q => (hxi q.1 q.2).comap_le

/-- Finite sample-block sigma-algebras are monotone in the coordinate block.

If every coordinate index in `A` is also in `B`, then the sigma-algebra generated
by the sample coordinates in `A` is below the sigma-algebra generated by the
coordinates in `B`.

Layer: Model | Gap: Level 0 (finite sample-block filtration monotonicity)
Proof: unfold `sampleBlockMeasurableSpace` and include each generator from the
  smaller subtype-indexed supremum into the larger one using the block inclusion.
Source: Mathlib measure-theory measurable-space comap and complete-lattice APIs
Used in: nonconvex stochastic conditional gradient enlargement of finite sample
  footprints for iterate and oracle-estimator measurability
Book citation: book/FOML/NonconvexStochasticConditionalGradient.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic nonconvex conditional gradient -/
theorem sampleBlockMeasurableSpace_mono
    {Ω Ξ I : Type*} [MeasurableSpace Ξ]
    (ξ : I → Ω → Ξ) {A B : Finset I} (hAB : A ⊆ B) :
    sampleBlockMeasurableSpace ξ A ≤ sampleBlockMeasurableSpace ξ B := by
  classical
  rw [sampleBlockMeasurableSpace, sampleBlockMeasurableSpace]
  exact iSup_le (fun q =>
    le_iSup_of_le (⟨q.1, hAB q.2⟩ : {q // q ∈ B}) le_rfl)

-- Promoted from SAPD Phase 3 staging (batch 1): finite shifted-prefix bridge.

-- Generalization plan (G0):
-- G0.1 naming: measurable_borel_finPrefix_shiftedPrefixFiltration
--   (orig was: measurable_borel_finPrefix_shiftedPrefixFiltration); the name
--   describes Borel-measurable functions of a finite sample prefix for a
--   shifted natural prefix filtration, with no SAPD or paper-local marker.
-- G0.2 typeclass level used:
--   E: none; the proof is purely measure-theoretic and does not involve a
--     normed or inner-product carrier.
--   measure: no measure parameter is needed; the statement is sigma-algebra
--     measurability for an arbitrary measurable sample space.
--   convexity: none; this is a filtration measurability lemma.
-- G0.3 reusability — could instantiate:
--   1. stochastic accelerated primal-dual martingale-noise measurability from
--      source finite sample-prefix representations.
--   2. stochastic mirror descent or stochastic conditional-gradient proofs
--      converting prefix-coordinate formulas into adapted scalar processes.
-- G0.4 search trace:
--   queries: ["finite prefix filtration measurable",
--     "Measurable Fin pi comap filtration"]
--   top hits: ["SOptLib.measurable_sample_le_prefixFiltration",
--     "StochasticAcceleratedPrimalDualSetup.prefixBorel_measurable_paperPrefixFiltration",
--     "SOptLib.measurable_sample_of_lt_prefixFiltration",
--     "SOptLib.measurable_pi_subtype_restrict_of_mem_map",
--     "SOptLib.measurable_finset_sum_kernel_comp_of_coordinate_measurable"]
--   coverage: partial — existing SOptLib hits prove single-coordinate
--     measurability or finite-product restriction/sum closure, but none turns
--     a measurable map of the full `Fin t` sample prefix into measurability
--     with respect to a shifted generated prefix filtration.
-- G0.4 not-a-thin-wrapper rationale: the theorem packages coordinate-prefix
--   measurability, finite dependent-product measurability, offset shifting,
--   and measurable composition into one reusable filtration bridge.
-- G0.5 structural-content rationale: the stream, offset, finite horizon,
--   product-valued prefix map, and arbitrary measurable postprocessing map are
--   all load-bearing in downstream adaptedness proofs.
-- G0.5c thin-wrapper self-detect: clean — body has a multi-step proof
--   assembling generated-filtration coordinate measurability with finite
--   product sigma-algebra closure and composition.
-- G0.5d minimal-hypothesis check: all already minimal; only measurable-space
--   typeclasses and coordinate measurability of the shifted stream are used.



/-- A measurable function of a finite shifted sample prefix is measurable for
the corresponding generated prefix filtration.

For a measurable sample stream `xi`, any offset, and any finite horizon `t`, the
map sending `omega` to the vector of samples `xi (j + offset) omega` for
`j : Fin t` is measurable with respect to the natural prefix filtration of the
shifted stream. Hence every measurable postprocessing of that vector is
prefix-measurable.

Layer: Model | Gap: Level 1 (finite shifted sample-prefix measurability)
Proof: each coordinate is one of the generators of the shifted prefix
  filtration; the finite product sigma-algebra is then controlled by the
  coordinate comap bounds, and measurable composition closes the result.
Source: Mathlib measure-theory measurable-space comap, finite product
  measurable-space, and SOptLib generated sample-prefix filtration APIs
Used in: stochastic accelerated primal-dual martingale-noise measurability from
  finite sample-prefix representations
Book citation: book/FOML/StochasticAcceleratedPrimalDual.json#/algorithm_spec
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, stochastic accelerated primal-dual -/
theorem measurable_borel_finPrefix_shiftedPrefixFiltration
    {Ω S α : Type*} [MeasurableSpace Ω] [MeasurableSpace S] [MeasurableSpace α]
    (xi : ℕ → Ω → S) (hxi : ∀ t, Measurable (xi t))
    (offset t : ℕ) (phi : (Fin t → S) → α) (hphi : Measurable phi) :
    Measurable[(SOptLib.filtration (fun j ω => xi (j + offset) ω)
        (fun j => hxi (j + offset))).seq t]
      (fun ω => phi (fun j : Fin t => xi (j.1 + offset) ω)) := by
  let shifted : ℕ → Ω → S := fun j ω => xi (j + offset) ω
  have hshifted : ∀ j, Measurable (shifted j) := fun j => hxi (j + offset)
  have hprefix :
      @Measurable Ω (Fin t → S)
        ((SOptLib.filtration shifted hshifted).seq t) (by infer_instance)
        (fun ω => fun j : Fin t => shifted j.1 ω) := by
    refine measurable_iff_comap_le.mpr ?_
    rw [MeasurableSpace.pi, MeasurableSpace.comap_iSup]
    refine iSup_le ?_
    intro j
    have hcoord :
        Measurable[(SOptLib.filtration shifted hshifted).seq t]
          (fun ω => shifted j.1 ω) := by
      exact SOptLib.measurable_sample_of_lt_prefixFiltration shifted hshifted j.2
    simpa [Function.comp_def] using hcoord.comap_le
  simpa [shifted] using hphi.comp hprefix

end SOptLib
