import SOptLib.Model.Iterates

namespace SOptLib

-- Generalization plan (G0):
-- concept/name: sampled oracle descent step; orig was rsgdStepWithStepsize.
-- generality used: arbitrary sample space Omega, state type E, and time-index
--   type T; only `[Sub E]` and `[SMul Real E]` are needed for the update
--   expression. No measure, measurability, independence, smoothness,
--   convexity, norm, or finite-dimensional assumptions are used.
-- portable call pattern: stochastic gradient, mirror-descent-in-Euclidean
--   coordinates, validation, and randomized-output proofs supply their own
--   natural-time conversion, stepsize schedule, sampled oracle-value process,
--   and initial state while reusing the same descent transition and generated
--   recursive-process zero/successor equations.
-- counterargument checked: not paper-local traceability because the statement
--   is the common sampled-oracle descent transition `x - gamma_t • G_t(x,omega)`;
--   not covered by the bare `recursiveIterateProcess` API, which does not name
--   the oracle descent transition or its process specialization.
-- coverage search: queried "recursive iterate process zero successor equations
--   descent step stepsize oracle" and "sampled oracle descent step recursive
--   process initial successor"; top hits were SOptLib.recursiveIterateProcess,
--   SOptLib.recursiveIterateProcess_zero, SOptLib.recursiveIterateProcess_succ,
--   SOptLib.iterateProcess_bridge_of_recursiveProcess, and
--   SOptLib.recursiveProcess_succ_eq_sample_update, all partial rather than
--   this named descent-step/process specialization.
-- minimal hypotheses: all already minimal; subtraction and real scalar
--   multiplication are exactly the operations appearing in the update.

/-- One sampled-oracle descent transition with a scheduled stepsize.

At natural recursion counter `k`, the update converts to the public time
`timeOfNat k`, queries the sampled oracle at the current state, and subtracts
the scheduled scalar multiple of that oracle value.

Layer: Model | Concept: sampled oracle descent step
Proof: (definitional construction; time-indexed stochastic descent update)
Source: Mathlib subtraction and real scalar-action notation together with
  stochastic first-order sampled-oracle update formulas
Used in: randomized stochastic gradient descent recursive iterate definitions
  exposing the update `x_{k+1} = x_k - gamma_k G(x_k, xi_k)`
Book citation: book/FOML/NonconvexStochasticFirstOrder.json#/algorithm_spec/steps/1
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic gradient descent -/
noncomputable def sampledOracleDescentStep
    {Omega E T : Type*} [Sub E] [SMul Real E]
    (timeOfNat : Nat -> T) (gamma : T -> Real)
    (oracleValue : T -> E -> Omega -> E)
    (k : Nat) (x : E) (omega : Omega) : E :=
  let t := timeOfNat k
  x - gamma t • oracleValue t x omega

/-- The sampled-oracle descent step unfolds to its scheduled oracle update.

Layer: Model | Gap: Level 0 (sampled oracle descent-step unfolding)
Proof: by rfl after unfolding `sampledOracleDescentStep`.
Source: Mathlib subtraction and real scalar-action notation
Used in: randomized stochastic gradient descent proofs that rewrite the
  generated transition to the source update equation
Book citation: book/FOML/NonconvexStochasticFirstOrder.json#/algorithm_spec/steps/1
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic gradient descent -/
@[simp]
theorem sampledOracleDescentStep_def
    {Omega E T : Type*} [Sub E] [SMul Real E]
    (timeOfNat : Nat -> T) (gamma : T -> Real)
    (oracleValue : T -> E -> Omega -> E)
    (k : Nat) (x : E) (omega : Omega) :
    sampledOracleDescentStep timeOfNat gamma oracleValue k x omega =
      x - gamma (timeOfNat k) • oracleValue (timeOfNat k) x omega := by
  rfl

/-- Canonical recursive process generated by sampled-oracle descent steps.

Layer: Model | Concept: sampled oracle descent process
Proof: (definitional construction; primitive recursion driven by
  `sampledOracleDescentStep`)
Source: SOptLib recursive iterate processes and stochastic first-order
  sampled-oracle update formulas
Used in: randomized stochastic gradient descent iterate processes generated
  from an initial point and a scheduled sampled oracle
Book citation: book/FOML/NonconvexStochasticFirstOrder.json#/algorithm_spec/steps/1
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic gradient descent -/
noncomputable def sampledOracleDescentProcess
    {Omega E T : Type*} [Sub E] [SMul Real E]
    (timeOfNat : Nat -> T) (gamma : T -> Real)
    (oracleValue : T -> E -> Omega -> E) (initial : E) :
    Nat -> Omega -> E :=
  recursiveIterateProcess initial
    (sampledOracleDescentStep timeOfNat gamma oracleValue)

/-- A sampled-oracle descent process starts at its initial state.

Layer: Model | Gap: Level 0 (sampled oracle descent-process initial value)
Proof: by rfl after unfolding `sampledOracleDescentProcess` and
  `recursiveIterateProcess`.
Source: SOptLib recursive iterate process initial-value API
Used in: randomized stochastic gradient descent proofs identifying the first
  generated iterate with the supplied initial point
Book citation: book/FOML/NonconvexStochasticFirstOrder.json#/algorithm_spec/initialization
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic gradient descent -/
@[simp]
theorem sampledOracleDescentProcess_zero
    {Omega E T : Type*} [Sub E] [SMul Real E]
    (timeOfNat : Nat -> T) (gamma : T -> Real)
    (oracleValue : T -> E -> Omega -> E) (initial : E)
    (omega : Omega) :
    sampledOracleDescentProcess timeOfNat gamma oracleValue initial 0 omega =
      initial := by
  rfl

/-- A sampled-oracle descent process unfolds at successor time.

Layer: Model | Gap: Level 0 (sampled oracle descent-process successor equation)
Proof: by rfl after unfolding `sampledOracleDescentProcess`,
  `recursiveIterateProcess`, and `sampledOracleDescentStep`.
Source: SOptLib recursive iterate process successor API and sampled stochastic
  first-order update formulas
Used in: randomized stochastic gradient descent proofs exposing one generated
  oracle-descent update before measurability, martingale, or descent estimates
Book citation: book/FOML/NonconvexStochasticFirstOrder.json#/algorithm_spec/steps/1
Origin algorithm: Lan, First-order and Stochastic Optimization Methods for
  Machine Learning, two-phase randomized stochastic gradient descent -/
@[simp]
theorem sampledOracleDescentProcess_succ
    {Omega E T : Type*} [Sub E] [SMul Real E]
    (timeOfNat : Nat -> T) (gamma : T -> Real)
    (oracleValue : T -> E -> Omega -> E) (initial : E)
    (k : Nat) (omega : Omega) :
    sampledOracleDescentProcess timeOfNat gamma oracleValue initial (k + 1) omega =
      sampledOracleDescentStep timeOfNat gamma oracleValue k
        (sampledOracleDescentProcess timeOfNat gamma oracleValue initial k omega)
        omega := by
  rfl

end SOptLib
